### ISSUE TITLE
Citizens Tab Player Bug

### ISSUE THREAD

**Issue by Mottekmalocher** [CodeCrafter47/BungeeTabListPlus#102]
I have some buggs with BungeeCordTablistPlus and Multiverse-Core some players are on the top left and the other were list at fillplayers position how can i fix it or would you fix it?
![tabbug](https://cloud.githubusercontent.com/assets/18620577/14752240/73e28a2e-08ce-11e6-9f66-14750cab0240.png)

**Comment by CodeCrafter47** [comment]
I don't think this is related to the Multiverse-Core plugin.

Which version of BungeeTabListPlus are you using?
Does the tab list have 60 slots?
Are you using 1.8 or 1.9?

**Comment by Mottekmalocher** [comment]
Plugin Version: 2.4.4
Minecraft Version: 1.8.8
Yes the Tab Size/Slots is 60 (tab_size: 60)

When i remove Multiverse-Core form the Plugins folder it would be normal but when i put Multiverse-Core into the Plugins folder and reimport my worlds and restart all servers the tab list buggs (i also tried to reset the multiverse core config but the same ploblem did happen)

ScreenShot without Multiverse-Core
![tabbug2](https://cloud.githubusercontent.com/assets/18620577/14761386/f0726ce4-095f-11e6-873f-09f8e60b5fbb.png)
Other Plugins List:
WorldEdit, LogBlock, DisableJoinMessage, Chairs, MaintenanceManager, WorldGuard, ProtocolLib, NoCheatPlus, LibsDisguises, SignEdit, PermissionsEx, NoteBlockAPI, CommandSync, ServerMusic, ItemJoin, Invsee_v1.0.3, Vault, PlayerMarkers, BungeeTabListPlus, EnjinMinecraftPlugin, UltraCosmetics, Herochat, LWC, HolographicDisplays, Citizens, ASkyBlock, Shopkeepers, ChestCommands, Parkour, ServerSigns

**Comment by Leiath** [comment]
See if it works without Citizens whil multiuniverse is installed. I disabled Citizens on mine to fix this.

**Comment by Mottekmalocher** [comment]
I tried is yesterday but i would try it now again xD

**Comment by Mottekmalocher** [comment]
ok now without citizens it works xD but why not yesterday !?

Thanks 4 your help ;)

best regards Motte
