### ISSUE TITLE
Plugin stops working after proxy restart

### ISSUE THREAD

**Issue by Cjrawrdan** [CodeCrafter47/BungeeTabListPlus#103]
Hello,
    It seems that every time my proxy restarts, the BungeeTabListPlus stops working and won't even enable within the server. I've tried wiping the plugin's configs and replacing the plugin but, nothing seems to be working.

This is what shows up in my console regarding BungeeTabListPlus:
[New Text Document.txt](https://github.com/CodeCrafter47/BungeeTabListPlus/files/233623/New.Text.Document.txt)

**Comment by CodeCrafter47** [comment]
The serverAlias option is a map not a list.
Use
```
serverAlias: {}
```
if you don't want to set an aliases.
Don't use square brackets.
