### ISSUE TITLE
Pex Group Problems

### ISSUE THREAD

**Issue by Briareos82** [CodeCrafter47/BungeeTabListPlus#107]
Hello, i have a Problem with Player they have more then one pex group.

Example:

Groups
VIP + Vote_1
when the Player have only the group VIP he will be seen in the TabList, when he have booth he is invisible in the TabList

Could some one Help?

**Comment by CodeCrafter47** [comment]
Can you provide some information about the rank and ladder you assigned to your groups?

**Comment by Briareos82** [comment]
We work with group wights
Vote_1 10 Votegroup you will get by 150 Votes
Vote_2 11 Votegroup you will get by 350 Votes
Vote_3 12 Votegroup you will get by 700 Votes
Lumi 20 default group
VIP 30
VIP+ 40
VIP++ 50
Supporter 60
Protector 70
Moderator 80
Admin 100

When you have x Votes you will get a Votegroup added

**Comment by Briareos82** [comment]
reminder

**Comment by CodeCrafter47** [comment]
which ladders are you using?

**Comment by Briareos82** [comment]
The Team ranks have an non ranked ledder
The Vote ranks are ranked with ledder Vote

**Comment by Briareos82** [comment]
for tests i get all groups a rank and a ledder but no change
Team Ranks have the ledder support
Player Ranks have the ledder player
Vote Ranks have the ledder vote

if some one get the vote group added he isnt seen in tablist

**Comment by Briareos82** [comment]
problem solved the weight by us was wrong 1 is higher then 2

Thx CodeCrafter47 for help
