### ISSUE TITLE
PlaceholderAPI placeholders no longer working

### ISSUE THREAD

**Issue by dyaizon** [CodeCrafter47/BungeeTabListPlus#109]
Since updating to 1.9 and updating both BTLP and PlaceholderAPI to the latest versions, I'm having an issue with PlaceholderAPI variables not being filled in. There's no output in the console logs - apart from both initializing successfully.

BTLP v2.4.5
PlaceholderAPI v2.5.0

Screenshot of tablist: http://imgur.com/HSi6BhP
Relevant tablist .yml: http://pastebin.com/y613Su7H

**Comment by CodeCrafter47** [comment]
Please verify PlaceholderAPI is working correctly by using `/papi parse %statistic_time_played%`.
If it doesn't replace the placeholder use `/papi ecloud download Statistic` and try again.

**Comment by dyaizon** [comment]
Ah, that's it. Just being slow to figure stuff out as usual.

Needed to do more with PlaceholderAPI after the update - now resolved - thanks for the help! (more helpful than the placeholderAPI docs!!)

Sorry for the errant issue!
