### ISSUE TITLE
Sponge modular data-providers

### ISSUE THREAD

**Issue by ghacproductions** [CodeCrafter47/BungeeTabListPlus#110]
It's great to see that you released your spongebridge-version. However, is it planned to structure the data-providers like on the bukkit side (modules)?

Greets,

**Comment by CodeCrafter47** [comment]
That's an interesting thought. The reason why this structure exists for the bukkit side is because it simplifies creating hooks for different plugins. The sponge bridge doesn't hook into any other sponge plugins right now. When adding hooks into other plugins it will probably make sense to switch to a more modular structure.

**Comment by ghacproductions** [comment]
I built a SpongeBridge myself around 1.5 months ago (but with some internal stuff, so I could not create a pull-request as it would not work on other servers) but I find the idea of structuring the data providers quite good as it manages to add own/existing plugins to BTLP. I'm quite sure there are/will be sponge plugins that might be usefull.

**Comment by CodeCrafter47** [comment]
I plan on adding placeholders for Sponge plugins as people request them. Probably a hook for PermissionsEx would also be useful, so BungeeTabListPlus can sort the players using permission group priorities. However I didn't add that yet as I'd rather avoid supporting just a single permission plugin. Maybe someone will write something similar to Vault for Sponge one day.

BungeeTabListPlus also offers an [API](https://github.com/CodeCrafter47/BungeeTabListPlus/blob/master/api-sponge/src/main/java/codecrafter47/bungeetablistplus/api/sponge/BungeeTabListPlusSpongeAPI.java) to add your own placeholders. Using it is the preferred way to add placeholder for your custom plugins. The API I made for the sponge bridge is almost identical to the one BungeeTabListPlus provides on Bukkit.

**Comment by CodeCrafter47** [comment]
All data providers have been moved to an external repository: <https://github.com/CodeCrafter47/minecraft-data-api>.

The same structure is used for the Sponge data providers as for the Bukkit data providers. There aren't any plugin specific data provider for Sponge plugins yet though.
