### ISSUE TITLE
MC-Version = Unknown

### ISSUE THREAD

**Issue by PacksGamingHD** [CodeCrafter47/BungeeTabListPlus#114]
basically in tab MC Version: unknown shows and that happens after the update to 5.1

**Comment by CodeCrafter47** [comment]
Which Minecraft version are you using?

**Comment by PacksGamingHD** [comment]
1.10 for bungee and 1.9.4 for all the servers with viaversion

**Comment by CodeCrafter47** [comment]
Version 2.5.0 and later of BungeeTabListPlus do correctly recognize 1.10 clients.
