### ISSUE TITLE
Wrong Hearts Displayed

### ISSUE THREAD

**Issue by markthree** [CodeCrafter47/BungeeTabListPlus#115]
Using the health scoreboard in vanilla Minecraft, wrong hearts are shown in the tablist. 
![image](https://cloud.githubusercontent.com/assets/20269990/16546949/6c9f4584-4129-11e6-8705-7828666b1c54.png)
![image](https://cloud.githubusercontent.com/assets/20269990/16546959/ac041416-4129-11e6-93f5-7ee3dbd03414.png)

**Comment by CodeCrafter47** [comment]
Are you using version 2.5.2 of the plugin? If not please update.

**Comment by markthree** [comment]
I have updated to 2.5.2 in case this bug was fixed. Unfortunately it wasn't fixed. This server is running in offline mode, and this certain one is a 1.9.4 spigot server with IP forwarding enabled to the BungeeCord.

**Comment by CodeCrafter47** [comment]
Can you check whether [the latest dev-build](http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/) fixed it?

**Comment by markthree** [comment]
It seems like it has been fixed after playing with it for a while! Thanks
