### ISSUE TITLE
colored prefixes with Sponge(pex installed)

### ISSUE THREAD

**Issue by hunter688** [CodeCrafter47/BungeeTabListPlus#117]
In the bungee have permissionSource: AUTO but in the tablist have no colors from pex prefixes defined in the sponge server. Sponge bridge is installed, for example sho poperly balance, tps...

Bukkit servers with pex are ok...

**Comment by CodeCrafter47** [comment]
The Sponge bridge doesn't support prefixes yet.

**Comment by CodeCrafter47** [comment]
Prefixes are now supported via the ${player sponge_prefix} placeholder.
c1710d95e5240fbbb7739ea08cc559e0110266c4
