### ISSUE TITLE
Wrong order when using the new Tablist API

### ISSUE THREAD

**Issue by kaenganxt** [CodeCrafter47/BungeeTabListPlus#120]
I was re-writing my custom tablist to the new api as I encountered some weird behaviour. Sometimes the list seems to be right, so I took a screenshot of the expected behaviour:
![Expected](http://puu.sh/qwzFQ/1942835ea8.jpg)
But most of the time, the list appears like this:
![Problem](http://puu.sh/qwzDY/bab31af128.jpg)
The user (me) is taken out of the list and completely appended to the end. The player is added like this to the list:
`tab.setSlot(1, 0, BungeeTabListPlusAPI.getIconFromPlayer(p), Players.getListName(p), p.getPing());`
where p is a ProxiedPlayer and getListName returns the aqua colored name. Since the entry is completely taken out of the list, the other columns are moved one slot up. I confirmed while testing, that the index passed to AbstractTabListLogic::setSlot is correct, so the fault has to be somewhere in there. Since my tab list code is quite complicated i wrote a simpler version with the following slot filling code:
```
for (int i = 0; i < 20; i++) {
     for (int j = 0; j < 3; j++) {
         tab.setSlot(i, j, QUESTION, i + "." + j, 0);
    }
}
```
Here's not the problem of re-sorting the list, but for two players, the first sees the correct version:
![Correct](http://puu.sh/qwOv5/9fbaeb3b9f.jpg)
For the other player, the non-fake player section is sorted wrongly:
![Wrong order](http://puu.sh/qwNpr/bf41022394.jpg)

These two errors seem to have the same reason. I already tried to figure out where it comes from, but since the code in AbstractTabListLogic is quite complicated I did not find the reason.
Thanks for your help.

**Comment by CodeCrafter47** [comment]
You might also have a look at #113. The changes to the config might allow you to create your custom tab list without a custom plugin.
