### ISSUE TITLE
Maven and CI down

### ISSUE THREAD

**Issue by JokHornsby** [CodeCrafter47/BungeeTabListPlus#122]
As far as I can tell, both http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/ and http://nexus.codecrafter47.dyndns.eu/content/repositories/public/ are both down. Are there plans to bring them back up, or is this intentional?

**Comment by CodeCrafter47** [comment]
That wasn't intentional. I restarted the server, now both services are running again.
