### ISSUE TITLE
Random steve/alex icons

### ISSUE THREAD

**Issue by Fhlazer** [CodeCrafter47/BungeeTabListPlus#127]
After "Designing" my own tablist, some of the icons show up as random steve or alex skin faces. I know i haven't done it wrong, because one of the icons is the same file (default/arrow), but only 2/3 times it shows up as the actual texture. heres my default.yml (its an .txt cause .yml was not supported)
[default.txt](https://github.com/CodeCrafter47/BungeeTabListPlus/files/489846/default.txt)

**Comment by CodeCrafter47** [comment]
That's because 2/3 time you have "default/arrow.png" which works and one time "default/arrow" which doesn't.
