### ISSUE TITLE
My skin /picture doesnt work 

### ISSUE THREAD

**Issue by HaziqahZuhairah** [CodeCrafter47/BungeeTabListPlus#128]
![received_293070107740539](https://cloud.githubusercontent.com/assets/22427339/18814897/c930ada4-8352-11e6-8e06-4c655bfa690c.jpeg)

Tablist : 
[default.txt](https://github.com/CodeCrafter47/BungeeTabListPlus/files/491602/default.txt)

Config : 

[default.txt](https://github.com/CodeCrafter47/BungeeTabListPlus/files/491601/default.txt)

**Comment by CodeCrafter47** [comment]
Go to **BungeeCords** config.yml and set `online_mode` to `true`.

That's the only way of fixing it. The Icons in the tab list will never appear on cracked servers.

**Comment by HaziqahZuhairah** [comment]
so my server only premium players can play?

**Comment by HaziqahZuhairah** [comment]
is there another way to fix this??

**Comment by HaziqahZuhairah** [comment]
can u make... the picture appears... just the pictures not skin... my tablist will be ugly if doesnt have picture.. @@

**Comment by HaziqahZuhairah** [comment]
before this... Icons already appears.... but now not appears..

**Comment by CodeCrafter47** [comment]
You can use a plugin like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/). That will make the icons work for players with a premium minecraft account.

**Comment by HaziqahZuhairah** [comment]
TQ sir..

**Comment by HaziqahZuhairah** [comment]
wan put that plugin at bungee server?? or lobby server??

**Comment by CodeCrafter47** [comment]
https://github.com/games647/FastLogin#how-to-install

**Comment by HaziqahZuhairah** [comment]
so do i need login plugin for crack players? or not?

**Comment by CodeCrafter47** [comment]
The way I understand it you do not remove any of your previous plugins, just add the FastLogin plugin.

So if you previously had an auth plugin you keep it. FastLogin should automatically login premium players.

**Comment by HaziqahZuhairah** [comment]
can u give step for it? i already try but cant.. can give step to setup...

**Comment by HaziqahZuhairah** [comment]
I try follow the web... but i cant... i dont understand..

**Comment by HaziqahZuhairah** [comment]
And i try already... but its not show picture or skin.. @@

**Comment by CodeCrafter47** [comment]
I'm sorry but I can't help you installing that plugin. I never used that plugin myself. I was just telling you that it exists and that it will allow premium players to see the icons (cracked players still won't see them). If you require help installing it I recommend you ask at the appropriate places.
