### ISSUE TITLE
How to implement for vanish! (selfcoded plugin)

### ISSUE THREAD

**Issue by Nesseley** [CodeCrafter47/BungeeTabListPlus#129]
Hi, Im using a plugin wich my developer has made.

How can we make it so we dissapear from TAB when we are in vanish? Or is this not possible?

Thanks in beforehand.
- Nesseley

**Comment by CodeCrafter47** [comment]
That's not possible yet :(

There have been requests to expose a vanish API but it didn't happen yet.

**Comment by Nesseley** [comment]
Maybe add a quick fix?
/tlp hide/unhide with a permission

We can easely just make /vanish also execute that command on my server

**Comment by Nesseley** [comment]
and a permission to see hidden players!

**Comment by CodeCrafter47** [comment]
There are commands to hide players from the tab list: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Commands>.

However the player must execute these commands on BungeeCord.

Vanished players are visible to players with the `bungeetablistplus.seevanished` permission be default. This can be changed using the `hiddenPlayers` option of a player set: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerSets>

**Comment by Nesseley** [comment]
Awesome! This fixed all of my problems, thank you soo much for a quik answer!
