### ISSUE TITLE
How exactly should I create custom variable?

### ISSUE THREAD

**Issue by CzlowiekKuktas** [CodeCrafter47/BungeeTabListPlus#130]
Hi, how to create custom variable and get it to the tablist? I'm trying to do it, but I don't understand the wiki. I registered the variable in the Bukkit plugin and I don't know what should I do next.

**Comment by CodeCrafter47** [comment]
The next step is to use the variable in your config.

Assuming you've registered a variable called `my_variable` then you can use `${viewer my_variable}` and `${player my_variable}` in your config.

**Comment by CzlowiekKuktas** [comment]
Thanks, it works just with viewer btw.

**Comment by CodeCrafter47** [comment]
The one with viewer resolves the variable for the player looking at the tab list.

The one with player only works inside the playerComponent option and resolves the placeholder for a player listed on the tab list.
