### ISSUE TITLE
Prefixes not working when player has multiple groups

### ISSUE THREAD

**Issue by Projekt4769** [CodeCrafter47/BungeeTabListPlus#135]
TAB-list prefixes don't appear when player has multiple BungeeCord groups. My guess is that BTLP looks for first/last group the player has and gives the prefix according to that, because it doesn't appear when the other group hasn't any prefix set in the config.

`permissionSource: BUNGEE`

Using BTLP v2.6.1 and BungeeCord #1189.

**Comment by CodeCrafter47** [comment]
If a player has more than one group there is no way the plugin can tell which one is supposed to be the main group as BungeeCord does not implement any group priority system. If you need such complex permission setups you should consider using a dedicated permission plugin.

**Comment by Projekt4769** [comment]
True, but wouldn't it be possible to loop through player's groups and apply the prefix if it has been set?

**Comment by CodeCrafter47** [comment]
There's no point in that. The `prefixes` config option will be removed soon which will in a way resolve this issue.

The `prefixes` config option only affects tab list configuration files using the old (pre 2.6.0) format. It will be removed when support for the old configs is removed, which will most likely be with the 2.8.0 update.
