### ISSUE TITLE
Loading config spam in the console

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#137]
Hi, when I switch to the server  with BTLP instlalled my console spams a lot with  [BungeeTabListPlus] Loading default.yml.

**Comment by CodeCrafter47** [comment]
The plugin reloads the configuration files sometimes when it is required. An example is when the plugin discovers new placeholders registered by a custom bukkit plugin using the bukkit bridge API. The plugin can only learn about these when a player connects to the bukkit server.

**Comment by CzlowiekKuktas** [comment]
Does it have to spam the console?

**Comment by CodeCrafter47** [comment]
The output of the plugin when loading config files is less vebose in the latest version. It will only create log entries if it encounters an error with any of the config files.
