### ISSUE TITLE
BTLP messes the tablist

### ISSUE THREAD

**Issue by CzlowiekKuktas** [CodeCrafter47/BungeeTabListPlus#138]
When I switch from a server with BTLP tablist to a server with tablist from bukkit plugin it messes the tablist, when I switch from that server to another server with bukkit tablist it is ok.

**Comment by CodeCrafter47** [comment]
> it messes the tablist
Can you describe that in more detail?

Also which version of BungeeTabListPlus are you using? Is this using an 1.7 client again?

**Comment by CzlowiekKuktas** [comment]
Yes, 1.7. I use the newest version of the plugin.

**Comment by CodeCrafter47** [comment]
Can you try the latest dev-build?

<https://ci.codecrafter47.de/job/BungeeTabListPlus/lastSuccessfulBuild/artifact/bootstrap-bungee/target/BungeeTabListPlus-2.6.5-SNAPSHOT.jar>

**Comment by CzlowiekKuktas** [comment]
It looks like it is fixed. :)
