### ISSUE TITLE
60 slots on 1.7 80 slots on 1.8

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#139]
Is it possible to create tab with 60 slots for 1.7 players and tab with 80 slots for 1.8 players?

**Comment by CodeCrafter47** [comment]
```yaml
showTo: |-
  ${viewer client_version} == "1.7"
```
or
```yaml
showTo: |-
  ${viewer client_version} == "1.8" or ${viewer client_version} == "1.9" or ${viewer client_version} == "1.10"
```

**Comment by CodeCrafter47** [comment]
I've made some corrections to the above comment, 1.7 clients are either identified as "1.7.5" or "1.7.10".

**Comment by SinlesFlyer376** [comment]
how do i use showTo?

**Comment by CodeCrafter47** [comment]
This might help <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/MultipleTablists>.
