### ISSUE TITLE
Tablist bugged

### ISSUE THREAD

**Issue by timothydavidhart** [CodeCrafter47/BungeeTabListPlus#14]
http://prntscr.com/5zs62p the vaible {factionMembersOnline} isn't working please help

**Comment by CodeCrafter47** [comment]
The variable is called {onlineFactionMembers}.

**Comment by CodeCrafter47** [comment]
Fixed it in the wiki.

**Comment by timothydavidhart** [comment]
Thanks

**Comment by timothydavidhart** [comment]
It is still buggy
