### ISSUE TITLE
Is it possible to sort tab list by vault prefix?

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#142]
Is it at all possible to sort tab list by vault prefix? So everyone who has a green &2 prefix is together, everyone who has a red &4 prefix is together, etc. I noticed there is vaultGroupInfo which kind of does the job, but I have a dozen or so ranks. So all it is doing is sorting the tab list by rank name alphabetically rather than all colors that are the same together.

With just Essentials and no BungeeTabListPlus, it sorts my local player tab list by colors with nicked users (users who have a '~nick' name) all last.

**Comment by CodeCrafter47** [comment]
vaultGroupInfo actually sorts players by the weight of their primary group. You can change the weight with your permission plugin and that way you can influence how players are sorted.

Anyway an option to sort players by their prefix would make a nice addition.

**Comment by mibby** [comment]
Sorting by prefix would be wonderful. :) I have multiple groups with some color overlap. Can't figure out how to add 'weight' to their primary group unless you mean by utilizing a ladder system. In which case, already done but can't necessarily match weight to have all colors grouped together. So an option to sort by prefix would be appreciated.

**Comment by CodeCrafter47** [comment]
2ee5894559a0dd4218c8b6cd9a4b291fa8f89e91
