### ISSUE TITLE
VanishNoPacket hidden players stacking heads / wiki update / config hook toggle.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#144]
PaperSpigot dev 883 (Spigot 1.10.2)
Waterfall (BungeeCord) dev 59
BungeeTabListPlus dev 661 (BukkitBridge & Bungee version)

Config.
http://paste.ubuntu.com/23282043/

TabList
http://paste.ubuntu.com/23282049/

Players who are vanished via VanishNoPacket have their head icons stacking on the bottom right if they don't have permission to see hidden players. They are able to see all vanished players' stacked heads though.
![link](http://i.imgur.com/u0YWNbD.png)

---

Would it be possible to have a config toggle to disable the VanishNoPacket hook? I'd like for all players to be visible at all times to everyone. Received a few complaints from people that they couldn't see themselves or other staff who were vanished using VanishNoPacket. 

---

Wiki seems to be missing info about the `bungeetablistplus.seevanished` permission node. Had to do some digging to figure out why my Admins could see vanished players but everyone else couldn't. :P May need to update the wiki with info about that permission.

**Comment by CodeCrafter47** [comment]
The head of every player playing on the same spigot server as you are must appear on the tab list to avoid gameplay issues. If your config doesn't do that then the plugin will just put the icons on  the bottom right.

Configuring the tab list to have a size of 80 slots will avoid the issue.

How to configure the plugin to always show invisible players is explained on the following wiki page: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerSets>. The info about the `bungeetablistplus.seevanished` permission can be found there too.

**Comment by CodeCrafter47** [comment]
Closing this issue as the question has been answered.
