### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by CzlowiekKuktas** [CodeCrafter47/BungeeTabListPlus#145]
Won't it be laggy if I had something around 500 variables on the whole network?

**Comment by CzlowiekKuktas** [comment]
I don't know, it's a big amount of variables to refresh every second.

**Comment by CodeCrafter47** [comment]
I'd say that the performance will be acceptable. The plugin will only query the variables which are displayed on the tab list which should not be that much (i.e. I don't think you can fit 500 variables on the tab list).

**Comment by CzlowiekKuktas** [comment]
500 variables not on 1 tablist, on the whole server, all tablists.

**Comment by CodeCrafter47** [comment]
I'd say 500 is okay.

Even if there is lag(which I wouldn't expect below 100 players) it will only affect the tab list and not the rest of the game.

**Comment by CzlowiekKuktas** [comment]
Well, I have 200-300 players online. Ok, if I will have too much CPU usage or something like that I will tell. :)
