### ISSUE TITLE
Reload command

### ISSUE THREAD

**Issue by ghost** [CodeCrafter47/BungeeTabListPlus#146]
The reload command doesn't register new custom variables from Bukkit.

**Comment by CodeCrafter47** [comment]
These are registered the first time a player connects to the particular bukkit server.

**Comment by CzlowiekKuktas** [comment]
It is not. I tried restarting bukkit server, but only after i restarded bungeecord new variable appearws.

**Comment by CodeCrafter47** [comment]
Should be fixed by c1710d95e5240fbbb7739ea08cc559e0110266c4
