### ISSUE TITLE
Ghost Players in Hub

### ISSUE THREAD

**Issue by Fluxty** [CodeCrafter47/BungeeTabListPlus#149]
I think this may be a potential incompatibility with MoveMeNow on Bungeecord? Players who disconnect are sometimes left as ghosts in the hub and there is a broken pipe error on disconnect. This happens with all version of BTLP:

` lost connection: Internal Exception: java.io.IOException: Broken pipe`

**Comment by Camouflage100** [comment]
Also having this same issue; except it's not just when they're kicked or anything. The network doesn't have MoveMeNow, but it does have a constant 50+ players joining and leaving so it could simulate the same issues that MoveMeNow is presenting.

**Comment by Fluxty** [comment]
We're getting around 1000-3000 unique logins per day over here; we got rid of BTLP and the problem disappeared.

**Comment by CodeCrafter47** [comment]
To investigate this issue I need either
1. more information: a full server log and a heap dump, or
2. a simple way to reproduce the issue.

Otherwise there's nothing I can do to help you.

**Comment by ArtNRG** [comment]
@CodeCrafter47 i have this issue, look at the [screenshot](https://pp.userapi.com/c639827/v639827829/29459/bSYNQTSEIzo.jpg).
Users log in there and press the button that run [MyCmd](https://www.spigotmc.org/resources/mycommand.22272/) command 
`'gotosurvival':
  command: /gotosurvival
  permission-required: false
  type: BUNGEE_TP
  server_name: survival`
1 person should stay there, all others should switch to another bungee server.

**Comment by CodeCrafter47** [comment]
I'm closing this issue as there has been no progress for three years. If you still have the issue please provide the information I require to investigate and fix the issue as indicated in my previous comment. In that case I will re-open the issue.
