### ISSUE TITLE
Always Disconnected

### ISSUE THREAD

**Issue by kidZDragoon** [CodeCrafter47/BungeeTabListPlus#150]
Error Log in BungeeCord: http://pastebin.com/WugWtQwX

I'm using the latest BungeeTabListPlus version (2.6.4)

List BungeeCord plugins:
AntiBot, BungeeAuthMeBridge, BungeeShout, BungeeStaffChat, BungeeTabListPlus, BVotifier, MoveMeNow, ServerListPlus, SkinsRestorer.

Please help, it only occurs on Lobby Server, and restarting the lobby won't fix it

**Comment by CodeCrafter47** [comment]
Please test whether this still occurs if you remove BungeeTabListPlus.

**Comment by kidZDragoon** [comment]
Disabling BungeeTabListPlus BukkitBridge in Lobby and showing Tab List to all server except lobby, still have the same errors: http://pastebin.com/QsUmr7N3

Did I must remove the BungeeTabListPlus from the Bungee to test it out?

EDIT: I noticed that if a player that have issue like that, it will most likely make other players in the lobby disconnect too.

**Comment by CodeCrafter47** [comment]
Yes you must remove the plugin from BungeeCord too.

**Comment by kidZDragoon** [comment]
After removing the BungeeTabListPlus: http://pastebin.com/TxXpDrnc

**Comment by CodeCrafter47** [comment]
Since it occurs without BungeeTabListPlus it's not an issue of BungeeTabListPlus. You can report the issue to BungeeCord,
