### ISSUE TITLE
TPS stuck after a crash of a server

### ISSUE THREAD

**Issue by lululombard** [CodeCrafter47/BungeeTabListPlus#151]
Hi there !
I have an issue : the TPS are stuck to the last number before the crash of a server (or even sometimes a reboot) until I restart the proxy (even /btlp reload doesn't do anything).

I'm running the last version of the plugin and bridge on my proxy and all my servers :
![btlp](https://cloud.githubusercontent.com/assets/2182934/20244751/f3886450-a98d-11e6-8e73-a96df834642c.png)

And the issue I'm facing (bottom row second colomn, TPS stuck at 1,4 while the server is running at 20 constant) :
![2016-11-13_10 43 59](https://cloud.githubusercontent.com/assets/2182934/20244762/3633eaae-a98e-11e6-8ce0-be1bb1d5fbba.png)

Thanks.

**Comment by CodeCrafter47** [comment]
Fixed by c1710d95e5240fbbb7739ea08cc559e0110266c4
