### ISSUE TITLE
1.11 compatibility 

### ISSUE THREAD

**Issue by i9hdkill** [CodeCrafter47/BungeeTabListPlus#152]
Seems like Tablist is not yet compatibel with 1.11
Using 1.11 Bungee + spigot 1.10.2 + ProtocolSupport:
http://prnt.sc/d76roe

**Comment by FlorianFun** [comment]
Confirmed. Tested on a "vanilla" BungeeCord #1200 and vanilla Spigot 1.8.8 (+ ViaVersion).
BungereTabListPlus v2.6.4.

**Comment by i9hdkill** [comment]
Turned out to be a bungee bug https://github.com/SpigotMC/BungeeCord/pull/1992
