### ISSUE TITLE
Could not detect bridge, tablist does not work

### ISSUE THREAD

**Issue by Xayanix** [CodeCrafter47/BungeeTabListPlus#154]
As above, i have installed BukkitBridge and BTLP says that i didn't.

Screenshots: http://scr.hu/0duk/an87m, http://scr.hu/0duk/56tea
Version: 2.6.4

**Comment by CodeCrafter47** [comment]
Are there any real issues other than BungeeTabListPlus saying something you disagree with?

**Comment by Xayanix** [comment]
Log is clear.
I am running RedisBungee and it is weird because on 3 out 5 proxies BTLP works fine, but on other 2 not.
On every proxy there are exactly same plugins and configurations. I will try to update config to 2.6.4.

**Comment by Xayanix** [comment]
I just noticed right now, that BungeeTablistPlus can't initialize Bridge when they are some players on server. Im running multibungee.

**Comment by CodeCrafter47** [comment]
You have a point there. When designing the bridge plugin I wasn't thinking of multiple BungeeCord instances. For what I can tell such a setup breaks the status command and the tps placeholder, also placeholders from PlaceholderAPI as well as Placeholder registered through the bukkit side API won't work on some BungeeCord instances. However prefixes from Vault, and most of the other built-in placeholders that require that bridge plugin should work fine.

**Comment by Xayanix** [comment]
I need only my own created placeholders from my plugin.
Is there any solution?

**Comment by CodeCrafter47** [comment]
I'll fix this issue soon.

**Comment by Xayanix** [comment]
Still waiting...

**Comment by CodeCrafter47** [comment]
I'm working on it.

**Comment by CodeCrafter47** [comment]
Should be fixed by c1710d95e5240fbbb7739ea08cc559e0110266c4
