### ISSUE TITLE
Sorting players by rank

### ISSUE THREAD

**Issue by Feerko** [CodeCrafter47/BungeeTabListPlus#155]
Hello

i have a problem with a sorting players by rank. I tried many ways, unsuccessfully.

here is my config http://pastebin.com/raw/73JtqWTs

I really care about this, thanks :)

**Comment by CodeCrafter47** [comment]
Your config file is correct.

You need to install BungeeTabListPlus_BukkitBridge and Vault on all spigot servers.

To sort the players BungeeTabListPlus queries the weight or rank property of the primary group from your permission plugin. Make sure you set one of these properties for every group (which property to use depends on what your permission plugin offers). You can find further explanations (specific to PEX) on the following wiki page: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PermissionsEx>.

**Comment by PurpleTape** [comment]
Hey, CodeCrafter47.
I have same problem but to exclude new issue I want ask you here. What about sorting of LuckyPerms group? I want to say that BungeeTabListPlus and LuckyPerms run on the same server (bungeecord), so do I need use bridge plugin here?

**Comment by CodeCrafter47** [comment]
If you're running LuckPerms on BungeeCord you can use the `LuckPermsGroupInfo` in which case you don't need the bridge plugin.

**Comment by PurpleTape** [comment]
I use latest version of LP and BungeeTabListPlus, setup option playerOrder as "LuckPermsGroupInfo,youFirst,alphabetically", but still not luck

**Comment by CodeCrafter47** [comment]
Use the `/lpb group <group> setweight` command to check the weight of your groups.

**Comment by PurpleTape** [comment]
Thank you for ur answers. I tried two ways: first I set weight as this ADMIN 2; MODER 1; DEFAULT 0. Command "lp group <group> info" show right weight. But still no sort. Next I tried reverse weight like ADMIN 0; MODER 1; DEFAULT 2, but got same result.

LP: 4.0.49
BTLP: 2.8.3

**Comment by CodeCrafter47** [comment]
Make sure you're using the `/lpb` (not `/lp`) command. LuckPerms must be running on BungeeCord.

**Comment by PurpleTape** [comment]
I have same plugins folder for all servers (include bungee). Did it as symbolic link

**Comment by CodeCrafter47** [comment]
Not sure whether that's the correct way to do it.

However I suggest you try using some of the built-in LuckPerms placeholders, just to see whether BungeeTabListPlus is able to get any data from LuckPerms: `${viewer luckperms_prefix}`, `${player luckperms_prefix}`, `${viewer luckperms_suffix}`, `${player luckperms_suffix}`, `${viewer luckperms_primary_group}`, `${player luckperms_primary_group}`.

**Comment by PurpleTape** [comment]
Yes, I use `${player luckperms_prefix}${player name}${player luckperms_suffix}`

**Comment by CodeCrafter47** [comment]
If the prefixes work, then ordering players by weight should work too. If not then chances are the the groups weights aren't configured properly. In some cases it makes a difference whether you set the weight meta value of a group instead of setting the weight value. However I'm being told that setting the weight meta value is a bad thing to do and is not all all necessary on recent versions of LuckPerms.

**Comment by PurpleTape** [comment]
How does sorting work? The more weight - the higher the position?

**Comment by CodeCrafter47** [comment]
I think it's lowest weight first, but not 100% sure. If you want to reverse it there's `LuckPermsGroupInfoReversed`.

**Comment by Sulphinx** [comment]
This might be like a EXTREMELY old error, but i cant seem to configure it correctly?
Could anyone please give me a example of their config with this?

**Comment by Andre601** [comment]
> This might be like a EXTREMELY old error, but i cant seem to configure it correctly? Could anyone please give me a example of their config with this?

Please don't reply to already closed issues (Especially those that are several years old).
You should instead ask in the Discord server (Linked on the spigot page) or make a new issue.
