### ISSUE TITLE
Packet 0/72 (ii) was larger than I expected, found 113 bytes extra whilst reading packet 72

### ISSUE THREAD

**Issue by Sollembum78** [CodeCrafter47/BungeeTabListPlus#156]
Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/72 (ii) was larger than I expected, found 113 bytes extra whilst reading packet 72

This error doesn't let people using 1.11 to connect to my 1.10 ViaVersion BungeeCord network.

I use latest BungeeCord, my servers are spigot 1.10 but I use ViaVersion on them to play both versions. 

I had ViaVersion on bungee and had no problems with tab, but there were performance issues, now I have ViaVersion on all the spigot servers, but not on Bungee, and now when people connect from 1.10 everything is ok, but from 1.11 it gives this error. And if I exclude hub server in config and provide default tab - players can join, as soon as they connect to something with this global tab - they get this error and kick.

**Comment by Sollembum78** [comment]
Discovered that problem cause is header-footer section, if I turn it off it lets to join with no problems. But why - have no idea.

**Comment by CodeCrafter47** [comment]
Update BungeeCord.

**Comment by Sollembum78** [comment]
Yea, that helped, thanks. I missed latest Bungee release couple of days ago.
