### ISSUE TITLE
Dynamic_size

### ISSUE THREAD

**Issue by dracnis** [CodeCrafter47/BungeeTabListPlus#157]
Can't create dynamic tablist size with séparate admin from other players.

**Comment by CodeCrafter47** [comment]
How would you expect that too look? Dynamic size tab list intentionally does not allow for custom slots. You can however use the playerOrder option to sort players.

**Comment by dracnis** [comment]
but player order don't work with prefix and we want fonda displayed before admin and that can't work.
juste need show fonda before admin ...

**Comment by CodeCrafter47** [comment]
There is a way to do that now: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/DYNAMIC_SIZE_FIXED_COLUMNS
