### ISSUE TITLE
Townysupport

### ISSUE THREAD

**Issue by enterih** [CodeCrafter47/BungeeTabListPlus#158]
Could you add support for Towny 
With Town Onlinecount, nation onlinecount, Town/Nation Name 
?
Thanks very much.

PS: Can you speak German?

**Comment by CodeCrafter47** [comment]
I do speak German. But I'll still answer your question in English so other poeple who happen to find this are more likely able to understand it.

Currently there is support for towny through PlaceholderAPI.

There are generic instructions on how to use placeholders from PlaceholderAPI in BungeeTabListPlus on the wiki: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlaceholderAPI>. I recommend you read these.

Currently PlaceholderAPI contains the following placeholders for the Towny plugin:
```
%towny_town%
%towny_friends%
%towny_nation%
%towny_title%
%towny_town_residents%
%towny_town_size%
%towny_town_tag%
%towny_town_balance%
%towny_town_mayor%
%towny_surname%
%towny_town_rank%
%towny_nation_rank%
``` 

If you want for example use the `%towny_town%` placeholder then you need to use `${viewer towny_town}` or `${player towny_town}` in BungeeTabListPlus's config.

**Comment by CodeCrafter47** [comment]
Closing this issue as the question has been answered.
