### ISSUE TITLE
4th Column is not populated when playercount drops.

### ISSUE THREAD

**Issue by JamieSinn** [CodeCrafter47/BungeeTabListPlus#161]
https://www.ecocitycraft.com/forum/threads/bug-report-tab.160438/

**Comment by CodeCrafter47** [comment]
It doesn't show the fourth column as it is configured to only show three columns. It does however show the fourth column sometimes (i.e. it does this if more than 60 players are on a single server, this includes hidden players and citizens). Then number of slots in the tab list needs to be higher than the number of players on a single server to prevent client bugs, so this behavior cannot be changed.

Configuring the plugin to always show the fourth column would fix the issue.

**Comment by andrewkm** [comment]
@CodeCrafter47 

How exactly would we configure to always show 4?

What if there are for example 200 on a single server? would it derp out even more?

**Comment by CodeCrafter47** [comment]
You can set the size option to 80, then it will always show 4 columns.

If size is set to 80 there won't be any issues anymore. This is because the client displays only the first 80 entries of the tab list, which allows the plugin to add more entries as required without breaking anything.

**Comment by andrewkm** [comment]
So just line 117 to:
size: 80 # 80 slots -> 4 columns, 20 rows

That's it?

**Comment by andrewkm** [comment]
Now it just looks weird af lol

http://i.imgur.com/0v0avmV.png
