### ISSUE TITLE
Vanished players appear on tab

### ISSUE THREAD

**Issue by JamieSinn** [CodeCrafter47/BungeeTabListPlus#164]
Essentials Vanish (/ev) still shows players on the tablist.

Vanished (VNP) does not show.

Could you add a hook into Ess to check for vanished there too? Just so that our administration team can be fully vanished if needed.

Thanks!

**Comment by JamieSinn** [comment]
For a video reference:
https://www.youtube.com/watch?v=6uY5rJvNjwk

**Comment by CodeCrafter47** [comment]
There is a hook for essentials. Are you sure you don't have the `bungeetablistplus.seevanished` permission which allows you to see vanished player?

**Comment by JamieSinn** [comment]
We grant no bungeetablist permissions at all. Nor do we negate any

**Comment by CodeCrafter47** [comment]
I tested it right now, seems to work just fine. Obviously it doesn't work in your video, but unless I can reproduce that I can't fix it.

**Comment by JamieSinn** [comment]
I'll see if I can collect some more info

**Comment by JamieSinn** [comment]
Resolved in latest versions.
