### ISSUE TITLE
Error when joining Sponge server

### ISSUE THREAD

**Issue by Eufranio** [CodeCrafter47/BungeeTabListPlus#166]
Whenever I try to join my SpongeForge server (with BungeeTabListPlus installed), I am kicked and the console shows this error: https://hastebin.com/bebavewasa.vbs

**Comment by CodeCrafter47** [comment]
I can't reproduce the issue. Does this issue also occur without any other plugins and mods?

**Comment by Eufranio** [comment]
This error appeared only once, nothing anymore, I'm going to close this issue and reopen if I manage how to reproduce.
