### ISSUE TITLE
PlayerSets

### ISSUE THREAD

**Issue by RickkyChan** [CodeCrafter47/BungeeTabListPlus#168]
When I was making a new tablist my playersets doesnt work
Can some help me?

http://pastebin.com/pCyPUQeH

**Comment by CodeCrafter47** [comment]
Your config file is fine.

Please note that the server names in these lines:
```yaml
      ${player server} == "hub"
```
need to exactly match the server names in BungeeCord's config.yml.

**Comment by RickkyChan** [comment]
Its all the same.

**Comment by RickkyChan** [comment]
nvm i already fixed it, i forget the uppercases lol.
