### ISSUE TITLE
BukkitBridge problem

### ISSUE THREAD

**Issue by Lammendam** [CodeCrafter47/BungeeTabListPlus#169]
Have this error in console:
15:21:35 [WARNING] [BungeeTabListPlus] Invalid skin requested: 
15:21:37 [INFO] [BungeeTabListPlus] Loading lobby.yml
15:21:37 [INFO] [BungeeTabListPlus] Loading server.yml
15:21:38 [INFO] [BungeeTabListPlus] Loading lobby.yml
15:21:38 [INFO] [BungeeTabListPlus] Loading server.yml
15:21:38 [INFO] [BungeeTabListPlus] Loading lobby.yml
15:21:38 [INFO] [BungeeTabListPlus] Loading server.yml
15:21:39 [INFO] [BungeeTabListPlus] Loading lobby.yml
15:21:39 [INFO] [BungeeTabListPlus] Loading server.yml
15:21:40 [INFO] [BungeeTabListPlus] Loading lobby.yml
15:21:40 [INFO] [BungeeTabListPlus] Loading server.yml

I have only two ymls for tablists, but plugin loading it many times when I enter to a server with BungeeTabListPlus_BukkitBridge. The TabLists works well but...
After couple of minutes my BungeeCord server crashes.

**Comment by CodeCrafter47** [comment]
It is perfectly normal that the config files are reloaded a few times after initially connecting to a server with the bridge plugin.

Please provide more information regarding the crash.

**Comment by Lammendam** [comment]
Umm.. i'm very sorry 'cause i've just moved my proxy server on the new hosting and forgot to correctly write query port into config file. I'm idiot =D
But I'm very glad for your fast response, im sorry for shaking your time...
