### ISSUE TITLE
Suggestion: PremiumVanish

### ISSUE THREAD

**Issue by InfamousYT** [CodeCrafter47/BungeeTabListPlus#170]
Hi there,

I have recently purchased [PremiumVanish](https://www.spigotmc.org/resources/premiumvanish-stay-hidden-bungee-support.14404/) and have realised that when I'm in vanish, other players can still see me in the tab menu. I was wondering if there is a configuration file I could edit, or if you could add this.

Thank you in advanced,

InfamousYT.

**Comment by CodeCrafter47** [comment]
You need to install BungeeTabListPlus_BukkitBridge.jar on the Spigot servers where you installed PremiumVanish. Then you will be hidden from the tab list when vanished.

The default configuration of BungeeTabListPlus allows players with the `bungeetablistplus.seevanished` permission to see hidden players. However that behaviour can be customized. You can specify for each player set whether hidden players should be included or not. You can find more info on the wiki: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerSets>.
