### ISSUE TITLE
[maybe] BungeeTabListPlus is registering too many channels

### ISSUE THREAD

**Issue by Eufranio** [CodeCrafter47/BungeeTabListPlus#172]
In my Lobby server, where I use BTLP, sometimes when a player join/switch servers/quit, I get the Too many channels registered message. I've opened a issue here https://github.com/Xephi/AuthMeReloaded/issues/967 and they pointed me to BTLP. Can you help me?

**Comment by CodeCrafter47** [comment]
BungeeTabListPlus is only registering a single channel called `BTLP`.
