### ISSUE TITLE
CustomPlaceholder Bug

### ISSUE THREAD

**Issue by Lammendam** [CodeCrafter47/BungeeTabListPlus#173]
I'm using BungeeTabListPlus Bukkit Bridge on one of my spigot servers. Sometimes happens that newbie player don't have prefix in tab-list. I use custom placeholders in my tablist config file for this server. Usually all new players have custom prefix in tablist, but happens that some players don't have prefix untill their permission group list will updated.
Screenshot here. http://prntscr.com/duvozu

**Comment by CodeCrafter47** [comment]
Would you mind sharing your configuration files for BungeeTabListPlus and the information which version of it you're using. Otherwise it's almost impossible to tell what's wrong.

**Comment by Lammendam** [comment]
Im using BungeeTablistPlus version 2.6.5 SNAPSHOT. BungeeTablistPlus BukkitBridge - same version.
Here my main config file of plugin: pastebin.com/03UJRuG6
and here my config file for tablist of survival server: pastebin.com/eyMScGZL

**Comment by CodeCrafter47** [comment]
Since this issue doesn't seem to be there in version 2.6.4, it's probably because of the updated bukkit bridge in the dev-build. I'll have a look into it.

**Comment by CodeCrafter47** [comment]
Latest dev-build might fix your issue.

See b48c59cb5461e686a016406f363b5c52130e2ae2

**Comment by Lammendam** [comment]
Okay, thanx, i'll tell you if this will work buggy.
Do I need to change something in config or tab-list file?

**Comment by CodeCrafter47** [comment]
There's no need to change the config.

**Comment by Lammendam** [comment]
Works good, i've not seen any bugs with this.
