### ISSUE TITLE
Issue with primary group Sponge / Luckperms

### ISSUE THREAD

**Issue by Rubbertjuh** [CodeCrafter47/BungeeTabListPlus#182]
Hello, 
I'm trying to grab the primary group with the placeholder:
${viewer vault_primary_group}

However, the correct primary group does not show up
https://gyazo.com/1d565cddd011686584de60b29151dd3d
https://gyazo.com/707028c5daae362292f3421255e82777

Luck perms version: LuckPerms-Sponge-2.17.58
BungeeTabListPlus version: BungeeTabListPlus_SpongeBridge-2.7.1-SNAPSHOT
Sponge version: spongeforge-1.10.2-2221-5.1.0-BETA-2119

Not sure what is going on here, any feedback is welcome!
Thank you for your time, if you need more information, please do tell

**Comment by CodeCrafter47** [comment]
Looks similar to #175. That issue has been fixed though.

**Comment by Rubbertjuh** [comment]
I saw #175 , it's not working for me though =/

**Comment by Rubbertjuh** [comment]
Fixed by setting weights in LuckPerms. 
Command:
/lp group <groupname> setweight <weight>

Higher number = Higher priority
