### ISSUE TITLE
Bug PlayerOrder Rank Vault

### ISSUE THREAD

**Issue by thebastien007** [CodeCrafter47/BungeeTabListPlus#185]
Hey,
I have a problem with the playerorder on rank vault.
The players aren't distributed under their ranks in the tab
Image: [https://image.noelshack.com/fichiers/2017/07/1487015486-tab.png](https://image.noelshack.com/fichiers/2017/07/1487015486-tab.png)
My tab: [http://pastebin.com/0jZ0VNM5](http://pastebin.com/0jZ0VNM5)
Thank's for help =)
Bastien

**Comment by CodeCrafter47** [comment]
When using the `vaultGroupInfo` option, BungeeTabListPlus uses the weight property of the primary group of the player to order the players. Please make sure you set that property in your permission plugin.

**Comment by thebastien007** [comment]
ok, and how to make on GroupManager ?? There isn't the option for the weight ?

**Comment by CodeCrafter47** [comment]
`/mangaddv <group> weight <weight>`

**Comment by thebastien007** [comment]
It's good, thank's you
