### ISSUE TITLE
Can't use prefixes/suffixes placeholders with LuckPerms

### ISSUE THREAD

**Issue by Eufranio** [CodeCrafter47/BungeeTabListPlus#187]
I have this component:

`
  playerComponent: {text: "${viewer vault_prefix}${player display_name}", icon: "${player skin}", ping: "${player ping}"}
`

This should show the player prefix before his name. However, it's not happening, and instead the player name just goes white in the tablist. I'm using LuckPerms if matter, and the player suffixes/prefixes are working in other places, even show in /papi parse %vault_prefix%.

**Comment by CodeCrafter47** [comment]
1. You need to use `${player vault_prefix}` there.
2. Please make sure you have BungeeTabListPlus_BukkitBridge and Vault installed on your Bukkit/ Spigot servers.

**Comment by Eufranio** [comment]
The same happens when using the one you said, and I'm using both BTLP and BTLP-BukkitBridge.

**Comment by CodeCrafter47** [comment]
If the prefix only contains color codes try using `${player name}` instead of `${player display_name}`.

**Comment by Eufranio** [comment]
Same.

**Comment by CodeCrafter47** [comment]
What does the output of `/btlp status` say?

**Comment by Eufranio** [comment]
![image](http://image.prntscr.com/image/2fa326103f4048f7a0aae75c094f8c26.png)

**Comment by Eufranio** [comment]
Sorry, I was using an older version. Updating, hopefully, fixes the issue!
