### ISSUE TITLE
Variables per server

### ISSUE THREAD

**Issue by DanielAlves123** [CodeCrafter47/BungeeTabListPlus#188]
Can you make variables per server?

**Comment by CodeCrafter47** [comment]
I plan to add that.

**Comment by DanielAlves123** [comment]
When this will be added? It will be very powerful function. :D

**Comment by CodeCrafter47** [comment]
It's planned for the 2.8.0 release.

**Comment by DanielAlves123** [comment]
When will we see 2.8.0 version?

**Comment by CodeCrafter47** [comment]
I don't know yet. When all [these issues](https://github.com/CodeCrafter47/BungeeTabListPlus/milestone/5) are fixed and I've implemented some other things I have in mind.
