### ISSUE TITLE
Sponge Player Join Error

### ISSUE THREAD

**Issue by PoisonedPanther** [CodeCrafter47/BungeeTabListPlus#189]
I'm running a Sponge server behind a Bungeecord proxy, and when players try to join the Sponge server with BungeeTabListPlus, they get the error "A fatal error has occured, this connection is terminated" and lose connection entirely. The FML log isolated from where I try to join is [here](http://pastebin.com/D1KxYC6Q), and the full FML log is [here](http://pastebin.com/D1KxYC6Q). This occurs with and without other mods and plugins.

**Comment by CodeCrafter47** [comment]
Are you running the same version of BungeeTabListPlus on Sponge and BungeeCord?

**Comment by PoisonedPanther** [comment]
Yeah I am, but when testing again today, changing absolutely nothing, it fixed itself. No idea what changed, but I'll close the issue.
