### ISSUE TITLE
Tab list shows old name and new name after name change

### ISSUE THREAD

**Issue by SullyTheUnusual** [CodeCrafter47/BungeeTabListPlus#19]
After a player changes their name, the tab list shows both their old and new names.

**Comment by CodeCrafter47** [comment]
screenshot?

**Comment by TheLecturer** [comment]
![2015-03-25_22 43 32](https://cloud.githubusercontent.com/assets/5038092/6870090/96313d22-d491-11e4-8ed0-0ed0c25d7361.png)

Zakishiro is the new name.
Rakaron is the old name.

We have discovered there are (for reasons unknown) multiple .dat files for this user in the playerdata folder, one with a Mojang-UUID, and one with a different UUID (that fails a UUID lookup).   Pre-1.8, both of these dat files contained the name "Rakaron". Post-1.8 upgrade and post-name-change, one still contains "Rakaron", the other (Mojang-compliant one) contains "Zakishiro".

**Comment by SullyTheUnusual** [comment]
http://bit.ly/1xkg7fv

Welcome on top shows new name, tab list shows old name.

**Comment by CodeCrafter47** [comment]
default.yml?

**Comment by SullyTheUnusual** [comment]
http://pastie.org/10059345

**Comment by CodeCrafter47** [comment]
Maybe the user set his nick to Rakaron?

**Comment by SullyTheUnusual** [comment]
We don't allow/use nicknames.

**Comment by TheLecturer** [comment]
This appears to have been resolved by removing the additional (non-Mojang-UUID) .dat file from the playerdata folder.
You can probably close this ticket.
