### ISSUE TITLE
java.io.EOFException on BTLP-SpongeBridge

### ISSUE THREAD

**Issue by Eufranio** [CodeCrafter47/BungeeTabListPlus#194]
When I installed BTLP_SpongeBridge on my Sponge server, this started happening and kicking everyone: https://hastebin.com/uzujopipuz.rb

**Comment by CodeCrafter47** [comment]
Are you using the same version of BungeeTabListPlus on Sponge & BungeeCord?

**Comment by Eufranio** [comment]
Hmm, I'm not, another issue of me not updating things :X

you could add an auto-updater...
