### ISSUE TITLE
Player apparead on the tablist?

### ISSUE THREAD

**Issue by DanielAlves123** [CodeCrafter47/BungeeTabListPlus#197]
Hi, 1 player appeared on my tablist. I'm using 1.8 version and the latest BTLP plugins. Screenshot: http://screenshot.sh/mMAseVgqO6fQg. It was 80 slot tablist.

**Comment by CodeCrafter47** [comment]
What's wrong with a player appearing on the tab list? That is what the tab list is there for, displaying players. Can you please explain why you think there is an issue?

**Comment by DanielAlves123** [comment]
Well, my tablist should not contain any player. It happened on 1.7 server to player with 1.8.

**Comment by CodeCrafter47** [comment]
Are you using Citizens?

**Comment by DanielAlves123** [comment]
No, but I use ProtocolLib. Only 1 player appears when I hide him then show him.

**Comment by CodeCrafter47** [comment]
ProtocolLib doesn't do anything on it's own, so it's kind of unrelated.

This kind of issue should definitely not happen no matter which plugins you use.

To further analyze this issue it would be helpful if you could run the [debug version of BungeeTabListPlus](https://ci.codecrafter47.de/job/BungeeTabListPlus/lastSuccessfulBuild/artifact/bootstrap-bungee-debug/target/BungeeTabListPlus-2.7.3-SNAPSHOT-debug.jar) on your (BungeeCord) server. Please recreate the issue while running it. It creates some files in the `BungeeTabListPlus/eventlog` directory. Please send them to me after recreating the issue and properly shutting down BungeeCord.

**Comment by DanielAlves123** [comment]
With this version I don't see the tablist, just empty cells.

**Comment by CodeCrafter47** [comment]
Can you still send me the files it generated?

**Comment by DanielAlves123** [comment]
It was caused by sending WrapperPlayServerPlayerInfo to 1.8> players to show the NPCs.
