### ISSUE TITLE
luckperms placeholder on sponge server

### ISSUE THREAD

**Issue by hunter688** [CodeCrafter47/BungeeTabListPlus#199]
trying get colored nick on tablist:

<pre>
  custom_prefix:
    !conditional
    condition: ${player server} == "lobby"
    true: ${custom_prefix_vault}
    false: ${custom_prefix_luck}
  custom_prefix_vault:
    !switch
    expression: ${player vault_primary_group}
    replacements:
      "Prot": "&2"
      "Builder": "&b"
      "Mod": "vmod"
      "Admin": "vadmin"
    defaultReplacement: "vdef"
  custom_prefix_luck:
    !switch
    expression: ${player luckperms_primary_group}
    replacements:
      "prot": "&2"
      "builder": "&b"
      "mod": "lmod"
      "admin": "ladmin"
    defaultReplacement: "ldef"
</pre>

But still get default replacement, it looks like luckperms placeholder not working. Server is sponge with  2.7.2 of bungeetablistplus bridge.

Howto debug? What can be wrong?

**Comment by CodeCrafter47** [comment]
The LuckPerms placeholder requires LuckPerms installed on BungeeCord.

**Comment by hunter688** [comment]
thx, works.
