### ISSUE TITLE
Plugin not sorting players if not set to {fillplayers}

### ISSUE THREAD

**Issue by BorlCand** [CodeCrafter47/BungeeTabListPlus#20]
Hello!
I have a problem.
I set up my config file and got small bug (?maybe?).
So there are some rows from config:
```
- '[SORT=adminFirst,youFirst,alphabetically][COLUMN=0]{fillplayers:world}'
- '[SORT=adminFirst,youFirst,alphabetically][COLUMN=1]{fillplayers:world}'
```
![btlpreport](https://cloud.githubusercontent.com/assets/1250404/6994744/270cd026-db2d-11e4-8eee-d41703869924.png)

As you can see plugin didn't sort players at all :( How can I fix this?

Full tabList:
```
tabList:
- '&2&l&nEarth'
- ' '
- '&a&l&nSecond'
- '&b&l&nThird'
- '[SORT=adminFirst,youFirst,alphabetically][COLUMN=0]{fillplayers:world}'
- '[SORT=adminFirst,youFirst,alphabetically][COLUMN=1]{fillplayers:world}'
- '[MAXPLAYERS=9][SORT=adminFirst,youFirst,alphabetically][COLUMN=2]{fillplayers:second}'
- '[MAXPLAYERS=9][SORT=adminFirst,youFirst,alphabetically][COLUMN=3]{fillplayers:third}'
- '[COLUMN=2]&c&l&nNether'
- '[COLUMN=3]&f&l&nEnd'
- '[MAXPLAYERS=8][SORT=adminFirst,youFirst,alphabetically][COLUMN=2]{fillplayers:nether}'
- '[MAXPLAYERS=8][SORT=adminFirst,youFirst,alphabetically][COLUMN=3]{fillplayers:end}'
- '[ALIGN BOTTOM]{prefix}{rawname}'
- '[SKIN=LordBart2000]&b{ping}ms'
- '&b{day}/{month}/{year}'
- '[SKIN=Olaf_C]&b{time}'
```

I am using PermissionsEx permission plugin on every server (synced).
So I want players be sorted like this (group@rank):
```
admin@1
eventer@10
helper@20
vip@50
green@75
player@100 (default)
```

Shall I use BungeePerms for this?

**Comment by CodeCrafter47** [comment]
Sorting players is kind of broken in the current version. It works on the latest dev-build (http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/) thought. So you should get that.
The adminFirst sort rule will not work with PEX. It may work with BungeePerms. But it's up to you to decide whether the benefit of sorting players by rank is in relation to the work of changing the permission system.
