### ISSUE TITLE
Bukkit PlaceHolder update every second even if animations setted to 30.0 second

### ISSUE THREAD

**Issue by Pieprzyk** [CodeCrafter47/BungeeTabListPlus#203]
showTo: '${viewer server} == "survival"'

priority: 0

showHeaderFooter: false

header:
- ''

headerAnimationUpdateInterval: 100.0

footer:
- |-
  &6Line 1
  &eLine 2
- |-
  &eLine 1
  &6Line 2

footerAnimationUpdateInterval: -1.0

customPlaceholders:
  afk_tag:
    !conditional
    condition: ${player essentials_afk}
    true: '&7|&oaway'
    false: ''

playerSets:
  global:
    filter: "true"

type: FIXED_SIZE
size: 60 # 60 slots -> 3 columns, 20 rows

defaultIcon: colors/dark_gray.png
defaultPing: 0

components:
- ""
- ""
- ""

- ""

- {text: "     &5xLajt&6HC&7.pl", icon: "default/server.png", ping: 0}
  
- ""

- !animated
  interval: 20.0
  components:
  - {text: "         &6RANKING", icon: "default/server.png", ping: 0}
  - {text: "      &6ZJEDZONE", icon: "default/server.png", ping: 0} 
  - {text: "       &6WYKOPANY", icon: "default/server.png", ping: 0}

- {text: "       &7Online: &a${viewer online-players}", icon: "default/server.png", ping: 0}

- !animated
  interval: 20.0
  components:
  - {text: "         &6RANKING", icon: "default/server.png", ping: 0}
  - {text: "      &6ZJEDZONE", icon: "default/server.png", ping: 0}
  - {text: "       &6WYKOPANY", icon: "default/server.png", ping: 0}

- !animated
  interval: 20.0
  components:
  - {text: "         &6GRACZY", icon: "default/server.png", ping: 0} # 4th row, 3rd column
  - {text: "           &6KOXY", icon: "default/server.png", ping: 0} # 4th row, 3rd column
  - {text: "          &6KAMIEN", icon: "default/server.png", ping: 0} # 4th row, 3rd column

- ""

- !animated
  interval: 20.0
  components:
  - {text: "           &6GILDII", icon: "default/server.png", ping: 0}
  - {text: "         &6REFILE", icon: "default/server.png", ping: 0}
  - {text: "        &6OBSYDIAN", icon: "default/server.png", ping: 0}

- !spacer {}

- {text: "", icon: "default/server.png", ping: 0} # 4th row, 3rd column
- "" # 18th row, 2nd column
- "" # 18th row, 3rd column

#Configuration file. got a question why Bukkit is sending custom placeholder every second?
![image](https://cloud.githubusercontent.com/assets/14301746/23612492/ebd69226-027b-11e7-8294-f73a3eea5db6.png)

public class UserPointsVariable extends Variable {
    public UserPointsVariable(String name) {
        super(name);
    }

    @Override
    public String getReplacement(Player player) {
        User user = UserManager.getUser(player);
        if(user == null) {
            return "Brak";
        }
        Bukkit.broadcastMessage(TimeUtil.getDate(System.currentTimeMillis())+" placeholder bukkit update? Why? POINTS");
        return user.getRanking().getPoints()+"";
    }
}

Why that code is fired every second?

**Comment by CodeCrafter47** [comment]
It's run every second to check whether the replacement for the placeholder changed. It is only send to bungee if it changed.

The bukkit bridge does not know about the configuration of the plugin on bungee.

**Comment by Pieprzyk** [comment]
Okay but is there any option to send it like once per 30 second? Cause while I've got aboyt 700 peoples online it will send about 2500 placeholders per second im a bit scared of that, it can cause lags as I think.

**Comment by CodeCrafter47** [comment]
The Bukkit Bridge currently checks the placeholders every second. To avoid minimize the performance decrease these checks are performed in a separate thread, only placeholder which are actually used in the tab list are checked and it only sends a packet to bungee if the replacement for a placeholder changed in comparison to the previous check.

When implementing your own placeholder you should make the `getReplacement` method as fast as possible for best performance.

Adding an option to the API to set the update interval for your placeholder is planned (see #180).

On Bungee the replacements for all placeholders are cached. The tab list is updated at a fixed interval in a separate thread. Usually it is updated every one or two seconds, however this depends on the value set in `config.yml` and on the placeholders used in the tab list config. Some areas of the tab list (containing animations) are updated more frequently. The plugin will only send packets to the client if the content of the tab list actually changed.

In future interval based updates of the entire tab list will be removed, instead the plugin will only update relevant parts of the tab list when the replacement for a placeholder is changed or a player joins or leaves the server. This is currently planned for version 2.8.0.
