### ISSUE TITLE
Question / Feature request | cut off too long names

### ISSUE THREAD

**Issue by Rubbertjuh** [CodeCrafter47/BungeeTabListPlus#208]
Hello, 
I was wondering if it was possible to cut of names if they reach a certain threshold. Example would be a name of 20 characters, you don't want to have such name show up in your tablist.. Instead you want 6 chars and 3 dots for example.
How would I accomplish this? 

Looking forward hearing from you.

**Comment by CodeCrafter47** [comment]
That's not possible currently, but I can add it in future.

Characters in Minecraft are different in size, so a limit of a fixed number of characters doesn't really make sense. Instead I'd implement a option to set the limit of the length of the text in a slot measured in pixel.

**Comment by Rubbertjuh** [comment]
Thank you :)
