### ISSUE TITLE
(Suggestion) Add hability to determine on which server the fake player appears, and make it count on the external playercount.

### ISSUE THREAD

**Issue by MithrandirCraft** [CodeCrafter47/BungeeTabListPlus#210]
I would like to suggest for the hability to make the fake playername stay on a server list on the tablist, and not move between servers (which looks strange, and in some servers it's obvious if the fake name isn't an actual player). This could be done for example, like this: /btlp fake add [server] <name>

Another suggestion related to fake players I'd like to make, is for the external player ammount counter to actually update accordingly to the ammount of player names, including fake ones, just as ingame. (The ingame count is different to the serverlist count)

Yeah, my intentions are evil.

**Comment by CodeCrafter47** [comment]
I can extend the command to allow adding fake players to a specific server.

However modifying player counts other than those displayed on the tab list is outside the scope of this plugin. The reason I added the fake players feature is to make testing the plugin easier. It's not there to boost your player counts.

**Comment by MithrandirCraft** [comment]
Well the player count inside is different than the external one. You can call it outside your plugin's scope, but it can also be considered a bug.

But that just about settles it. It's clear you are not favorable of external player count modification if it implies faking the ammount of players with your plugin. Which I imagine is not a characteristic you want to attribute to your tab modifier.
