### ISSUE TITLE
Lost one Player in tablist

### ISSUE THREAD

**Issue by MarcSteak** [CodeCrafter47/BungeeTabListPlus#211]
Hello :)

We are using your Tablist and it works great except one thing.
There is always 1 player missing on the Tablist

What am I doing wrong? Can't find the Issue.

Thanks for help

https://pastebin.com/Vt9bPbmm

![2017-03-30_23 01 30](https://cloud.githubusercontent.com/assets/26802938/24526404/5543c906-159e-11e7-9911-d884a69c1c6b.png)

**Comment by CodeCrafter47** [comment]
I recommend removing all of the plugins configuration files and letting it create new ones, then customizing these. Also make sure you have the latest version of the plugin.

**Comment by MarcSteak** [comment]
thank you, fixed it for me.
