### ISSUE TITLE
Hidden player glitch

### ISSUE THREAD

**Issue by Projekt4769** [CodeCrafter47/BungeeTabListPlus#213]
What I'm trying to do is hide the lower player, but the head and slot remains visible:

![2017-04-25_22 27 47](https://cloud.githubusercontent.com/assets/10405384/25404237/ce06aa16-2a07-11e7-8f7f-3e92e097c961.png)

The other player was hidden with "/btlp hide" command.
My default.yml: https://pastebin.com/X3KDbJGU

I tested it with another tablist type, but the problem remains:

![2017-04-25_22 32 12](https://cloud.githubusercontent.com/assets/10405384/25404562/273d3e32-2a09-11e7-8cb6-36e6b01b2489.png)

And config: https://pastebin.com/qip4pqcq

Using BungeeTabListPlus v2.7.3 and BungeeCord #1229.

Any suggestions on how to get this working, or perhaps I'm doing something wrong?

**Comment by CodeCrafter47** [comment]
You need a proper vanish plugin (like SuperVanish) to avoid this effect. That is because BungeeTabListPlus can't remove a player's icon from the tab list if that player is visible to other players in game.
