### ISSUE TITLE
vanilla scoreboard health is off the edge of the list

### ISSUE THREAD

**Issue by jonthesquirrel** [CodeCrafter47/BungeeTabListPlus#215]
![2017-05-01_03 10 14](https://cloud.githubusercontent.com/assets/6022168/25577625/603dbcb8-2e1c-11e7-97ff-cc8574e3c36f.png)

The Creative server is running Spigot and the Survival server is running Vanilla. When you are on Creative you can't see the scoreboard health, and when you are on the Survival server you can see it. The issue is the hearts go off the edge of the list. Is there any way to make them more centered, like they should be?

**Comment by CodeCrafter47** [comment]
The position of the hearts depends on the length of the text in the slot with the longest text. Which is the player on the creative server. If you reduce that it will move the hearts a bit to the left.

**Comment by jonthesquirrel** [comment]
![2017-05-01_03 20 57](https://cloud.githubusercontent.com/assets/6022168/25577734/72a51c74-2e1d-11e7-9691-16e3ea9afd6c.png)
I realized the hearts cutting off was because my Minecraft window was too narrow, and thanks @CodeCrafter47  the gap between the name and the hearts goes away when there is a prefix in survival as well.
