### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by victoret7** [CodeCrafter47/BungeeTabListPlus#216]
Icons on tablist not appearing. I talked to the hosting and they say that they only use java 8 on their servers and after some researching they tell me that it isn't their fault.
https://pastebin.com/71Medp18
I'm using an example from the wiki and i only changed a little bit the names.

**Comment by CodeCrafter47** [comment]
There are basically two possible reasons why the icons won't appear:

1. You're running a cracked server or
2. You're running Minecraft 1.7 or older.

**Comment by victoret7** [comment]
Yes i have a cracked server. Isn't possible to show minecraft skulls or icons on cracked servers?

**Comment by CodeCrafter47** [comment]
It's not possible to show the icons on a cracked server.

**Comment by victoret7** [comment]
Isn't it implemented or isnt possible?

**Comment by CodeCrafter47** [comment]
It's not possible. The Minecraft client won't display the icons when connected to a cracked server.

**Comment by victoret7** [comment]
And how some servers show icons on their tablist being cracked?

**Comment by CodeCrafter47** [comment]
You can display the icons to some players which have properly bought their copy of Minecraft, if you use a plugin like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/).
