### ISSUE TITLE
pex sort by group reverse

### ISSUE THREAD

**Issue by BabelSolea** [CodeCrafter47/BungeeTabListPlus#218]
please add reverse sort variable in tablist by permissionsEX groups:

example sort:

MVP > VIP > default

MVP players
VIP players
default players

**Comment by CodeCrafter47** [comment]
What's wrong with using `vaultGroupInfoReversed`?

**Comment by BabelSolea** [comment]
i didnt saw that variable.

**Comment by BabelSolea** [comment]
showTo: "all"
priority: 100
type: DYNAMIC_SIZE

showHeaderFooter: true
header:
  text
headerAnimationUpdateInterval: 0.1
footer:
  text
footerAnimationUpdateInterval: 0.2

customPlaceholders: {}

playerSets:
  global:
    filter: "true"
    hiddenPlayers: VISIBLE_TO_ADMINS
  currentserver:
    filter: "${player server} == ${viewer server}"
    hiddenPlayers: VISIBLE_TO_ADMINS

playerSet: currentserver

playerOrder: "vaultGroupInfoReversed,alphabetically"

playerComponent: {text: "${player vault_prefix} ${player name} ${player vault_suffix}", icon: "${player skin}", ping: "${player ping}"}

so i want see in tablist:

players only from server what im
players sort top - donates bot - defaults and alphavitally after

i have issues about that bugs from plugin:
![image](https://cloud.githubusercontent.com/assets/23665302/26213462/ce0d5b8e-3c01-11e7-98e0-927b93e2ba79.png)
![image](https://cloud.githubusercontent.com/assets/23665302/26213468/d48ca154-3c01-11e7-926e-b1956cac6a53.png)

what i did wrong?

**Comment by CodeCrafter47** [comment]
I don't know what you are doing wrong.

However I can tell you that BungeeTabListPlus can't magically guess which group is more important than another. Because of that lack of skill it simply uses the `weight` property of  the players' primary groups to order them. Unfortunately this means you have to set the `weight` property for all groups.

**Comment by BabelSolea** [comment]
nice! where i need put weight property for all groups?

**Comment by BabelSolea** [comment]
yee! i found that need in PEX put per group!
1 - top
1000 - default
etc )

all working fine! thanks for help!
