### ISSUE TITLE
Can't load BungeeTabListPlus

### ISSUE THREAD

**Issue by anthonyhou04** [CodeCrafter47/BungeeTabListPlus#229]
Hi, I am using 
Bungeecord 1242
BungeeTabListPlus version 2.7.5-SNAPSHOT
LOG [https://pastebin.com/gY1J2MWi](https://pastebin.com/gY1J2MWi)
thx!

**Comment by CodeCrafter47** [comment]
To fix your issue either
1. use a BungeeCord version that supports 1.12 or
2. use BungeeTabListPlus version 2.7.3 if you don't use Minecraft 1.12

**Comment by CodeCrafter47** [comment]
Fixed with 501c35b04d285cdac30af2433811fd1ece64a608

The latest version of the plugin can now be loaded by any resent BungeeCord version, not just the ones supporting 1.12.

**Comment by anthonyhou04** [comment]
Fixed, thanks
