### ISSUE TITLE
adding hiddenServers doesn't hide the server

### ISSUE THREAD

**Issue by smmmadden** [CodeCrafter47/BungeeTabListPlus#230]
I wanted to keep all the servers/players visible but I wanted to hide my testing server since only I use it.
Using the below did not hide the server name.
![image](https://user-images.githubusercontent.com/10309346/27252882-99ef1bd4-5336-11e7-9127-97eb7737034f.png)

Instead it still shows in the FIXED_SIZE display
![image](https://user-images.githubusercontent.com/10309346/27252875-5d434de0-5336-11e7-81af-3ec4a3cf1f7d.png)

**Comment by CodeCrafter47** [comment]
As the comment in the config file above the option explains, the option hides all players on the particular servers. Nothing more, nothing less. I think it is quite well documented what that option does.

Here's what it says:

> this hides all players on the hidden servers from appearing on the tablist

You can't expect it to do anything else. Like, you don't expect cars to fly.

**Comment by smmmadden** [comment]
sarcasm aside, my question was about the hiddenServers option, not the hidden players.  From the file itself.  I only want to hide the servers that I don't want the public to know about.  The first line implies I can hide the server from the global tablist.  Is this not correct?

**servers which you wish to hide from the global tabList**
# Note that this is different from excludeServers above: this hides all players on the hidden servers from appearing
# on the tablist, whereas excluded servers' players are still on the BungeeTabListPlus tablist, but they do not see
# the global tab list
hiddenServers: 
 - tester

**Comment by smmmadden** [comment]
sarcasm aside, I'm not 12. 
My question to you was regarding the hiddenServers option.  I want to hide non-public servers from the tablist so that players don't see worlds they shouldn't know about.  The description you reference implies I am able to do it, but my results show otherwise.
**# servers which you wish to hide from the global tabList**
# Note that this is different from excludeServers above: this hides all players on the hidden servers from appearing
# on the tablist, whereas excluded servers' players are still on the BungeeTabListPlus tablist, but they do not see
# the global tab list
hiddenServers: 
 - tester

**Comment by CodeCrafter47** [comment]
In some cases the option can have the effect of preventing the server from appearing on the tab list. But that is only the case if you configure the plugin not to display servers with no players. However the purpose of the option is to remove the players from the tab list, not the servers.

It is currently not possible to explicitly remove any servers from the tab list when using the `!players_by_server` component, however I plan on adding such an option to the component, so it can be configured individually, per tab list.

**Comment by smmmadden** [comment]
Thank you, having that as an option is a real plus.  

We do plan to have additional servers that I'll be adding into the Bungee Network and having the ability to show servers for some players and not others would be exactly what I'd need.  

We have servers which are for Adults Only and some for Children only so controlling what can be seen based on a permission node or some other variable would go a long way to that end.  I've got other permissions to prevent players from joining the wrong server in play, but nothing that takes it to this level to not show the servers itself.

**Comment by cfr** [comment]
@CodeCrafter47 was this feature implemented? Adding server to hiddenServers still does not hide it.

**Comment by CodeCrafter47** [comment]
The functionality of the option in `config.yml` was not changed. However a way has been added to hide servers when using the `!players_by_server` component.

Somewhere in your tab list configuration file (`default.yml`) you have something similar to the following:
```yaml
- !players_by_server
  playerSet: all_players
  serverHeader:
  - '&b&l>&3 ${server}(${server_player_count}):'
  playerComponent: "${player name}"
  morePlayersComponent: '... and ${other_count} others'
```
There you can add a line like the following to hide some of your servers:
```yaml
  hiddenServers: [server4, server7]
```
So after that it looks like:
```yaml
- !players_by_server
  playerSet: all_players
  serverHeader:
  - '&b&l>&3 ${server}(${server_player_count}):'
  hiddenServers: [server4, server7]
  playerComponent: "${player name}"
  morePlayersComponent: '... and ${other_count} others'
```

So it's actually quite easy. All you have to do is to add a line telling the plugins which servers not to display.

**Comment by smmmadden** [comment]
I can CONFIRM that the above solution works!  I had a server called "tester" which I use for testing out plugin updates and new plugins/server builds.  Before adding in hiddenServers: [tester] it was visble.  Now after a server restart - no longer showing. :-)

Thanks!

**Comment by cdmvirt** [comment]
could there be a permission so that certain people can view that hidden server?

**Comment by CodeCrafter47** [comment]
There's no such permission. I'm not sure adding one would be a good idea, as it makes using the feature more complicated.

However it is absolutely possible to make it so that only some people can see the hidden server. On possibility is to create two tab list configuration files (there's a wiki page on the topic), one for those players who should see the servers(selected by groups, permissions or whatever you want to use) where you just remove the hiddenPlayers option, and one for the others.

**Comment by jadsspt** [comment]
This doesn't work after, Luckperms v5 support was added.

**Comment by lokka30** [comment]
> 
> 
> This doesn't work after, Luckperms v5 support was added.

@jadsspt I'm using this feature without any problems. Nothing to do with permissions. Maybe you have multiple tab lists and forgot to configure the permissions of those properly?
