### ISSUE TITLE
Sort in tab - PEX

### ISSUE THREAD

**Issue by Jesperrodnes** [CodeCrafter47/BungeeTabListPlus#231]
Hello how sort i groups in the tab like owner first and last members? i dont unterstand please help

Tab config: https://paste.md-5.net/fipomibamu.pl

Pex config: https://paste.md-5.net/racupujasa.sm

**Comment by CodeCrafter47** [comment]
Please ask your question either in the forums or on github. There is no need to ask the same question twice.
