### ISSUE TITLE
Add possibility to register server-specific placeholders

### ISSUE THREAD

**Issue by Foorack** [CodeCrafter47/BungeeTabListPlus#232]
For example ${server:game1 status}

I could only find documentation for adding player-placeholders. 😕
http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/codecrafter47.bungeetablistplus%24bungeetablistplus-api-bukkit/javadoc/

**Comment by CodeCrafter47** [comment]
There alreasy is an issue for that: #188
