### ISSUE TITLE
Error spam during permissions reload.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#235]
Occasionally during a permissions refresh I get spammed with this:

https://pastebin.com/raw/AMXYzm4U

It happens on 1 out of 15 reloads or so. Refresh as in groupmanagers /manload command. Basically it refreshes everyones permissions. Hopefully this helps you track down the error. Only BungeeTabListPlus spams like this during a perm refresh.

BungeeTabListPlus jenkins build 688
If you need any other information please do let me know.

**Comment by CodeCrafter47** [comment]
That's an issue in GroupManager.

**Comment by andrewkm** [comment]
Can you give me an idea as to what it could have to do with, within group manager?

Out of our 61 plugins, BungeeTabList is the only one causing issues with group manager.

**Comment by CodeCrafter47** [comment]
GroupManager appears to be unable to handle permission queries while refreshing permissions.

Since BungeeTabListPlus runs a lot of permission queries, sometimes a few fall into that time frame.
