### ISSUE TITLE
Request: Restore Heads in Tablist for offline-mode Servers

### ISSUE THREAD

**Issue by Phreag** [CodeCrafter47/BungeeTabListPlus#236]
Currently on a offline-mode server there are no heads showing up in the tablist.
Could it be possible to add them by packet manipulation back?

I dont know if you can do that but it would be awesome :)

**Comment by CodeCrafter47** [comment]
There's is nothing that I can do about it.

However you can use a plugin like [FastLogin](https://www.spigotmc.org/resources/fastlogin.14153/) to display the heads at least to the players with a legitimate copy of Minecraft. Displaying the heads is just a side effect of the plugin, not its main purpose. Make sure you understand what it does and you want that, before installing it.

**Comment by Phreag** [comment]
Nice, that works :)
