### ISSUE TITLE
Spigot server crash

### ISSUE THREAD

**Issue by Lammendam** [CodeCrafter47/BungeeTabListPlus#241]
I had a need to update my BungeeCord server with latest version of BungeeCord core. But when i've done this, BungeeTabListPlus has broken and won't to work. Then i gonna to update BungeeTabListPlus and his BukkitBridge on two my Spigot servers, but one of them crashes after 1-2 minutes after loading with this error log:
https://pastebin.com/Z9jnJRFs
BungeeCord latest build #1250
Spigot server with 1.11.2
BungeeTablist: 2.8.0

**Comment by CodeCrafter47** [comment]
Please try using the [latest dev-build](http://ci.codecrafter47.de/job/BungeeTabListPlus/) it should fix the issue (which I think only occurs when using Gringotts).

**Comment by Lammendam** [comment]
Thank you.
I think i should write to Gringotts author? But i dont know what exactly to write..

**Comment by CodeCrafter47** [comment]
It's an issue in BungeeTabListPlus. I've already fixed it. The fix will be included in the next release. You can get a build with the fix from http://nexus.codecrafter47.dyndns.eu/service/local/repositories/snapshots/content/codecrafter47/bungeetablistplus/BungeeTabListPlus_BukkitBridge/2.8.1-SNAPSHOT/BungeeTabListPlus_BukkitBridge-2.8.1-20170718.141943-2.jar

**Comment by Lammendam** [comment]
Yeap, that's work, with this build no server crash occur. Thank you.
