### ISSUE TITLE
Add support for Sponge PlaceholderAPI

### ISSUE THREAD

**Issue by BrainStone** [CodeCrafter47/BungeeTabListPlus#247]
It would be really cool if the PlaceholderAPI on Sponge worked the same way as the PlaceholderAPI on Spigot!

**Comment by CodeCrafter47** [comment]
d280e8a312c58dcf868ab35860257dcb0ad22fe6

**Comment by BrainStone** [comment]
Is it supposed to work like with the Spigot/Bukkit PlaceholderAPI?

Because for example using the `%economy_balance%` placeholder like this `${viewer economy_balance}` doesn't show anything.

**Comment by BrainStone** [comment]
Ah nvm. It throws an exception. I'll create an issue for it.
