### ISSUE TITLE
Option to force groups to be sorted at the top irregardless of vault group alphabetical ordering.

### ISSUE THREAD

**Issue by mibby** [CodeCrafter47/BungeeTabListPlus#250]
Would it be possible to add a way to force groups to be sorted / displayed first at the top in the tab menu? 

With ``` playerOrder: "vaultprefix,alphabetically"```, it sorts people by their vault group prefix alphabetically. So numbers come first, then letters, i.e. &1, &2, &3, &4, &5, &6, &7, &8, &9, &a, &b, &c, &d, &e, &f. I'd like to force a group to always display first in line so they are always on the tab menu. Specifically in my case, displaying all online staff members with the color &c and &d. With 100+ people online, they get cut off.

**Comment by CodeCrafter47** [comment]
I recommend against using `vaultPrefix`. You should use `vaultGroupInfo` instead. It sorts the players by the weight of their primary group.

**Comment by mibby** [comment]
Weight as in rank order? What about if you had separate permission tiers with separate rank orders so staff ranks aren't part of the main server rank grouping?

**Comment by CodeCrafter47** [comment]
It has nothing to do with group inheritance. Your permission plugin associates a weight with each group. The weight is just a number that can be set using a command. When using `vaultGroupInfo` players whose primary group has a low weight show up at the top of the tab list. PermissionsEx uses the weight property to resolve conflicts in cases where conflicting permission nodes are inherited from multiple groups.

**Comment by mibby** [comment]
I'm assuming you are referring to the weight value as part of the rank ladder.

```
    options:
      rank-ladder: Member
      rank: '4'
```

The problem I have with that is I have multiple different ladders with various rankings. So a staff ranked 1-3 will have the same weight value as the main member tree.

**Comment by CodeCrafter47** [comment]
Do not confuse the `rank` option with the `weight` option. Both can have special meaning to permission plugins, but what they are used for varies from plugin to plugins. E.g. PermissionsEx uses the `rank` option for the promote command and the like.

While BungeeTabListPlus will sort the players by either option if present, I recommend you set the `weight` option as that one will be used in favor of the `rank` option.

**Comment by mibby** [comment]
Hm.. So if I still want the player's primary group prefix and suffix to show up but have staff sorted at the top of tab, I would just need to add a weight value to the staff ranks and everything else will fall in line as it currently behaves? Or set all ranks to the same weight value to use the primary set group's prefix still?

**Comment by CodeCrafter47** [comment]
You can't sort by display name. In your case the easiest solution would be using `vaultGroupInfo,vaultprefix` to sort by `weight` first and players with the same weight by the prefix. A better solution, but possibly involving more work would be not to set all the non-staff ranks to the same weight value, but use different values and only use the same value for those with the same prefix color, to impose an order among them.
