### ISSUE TITLE
Another Spigot server crash

### ISSUE THREAD

**Issue by Lammendam** [CodeCrafter47/BungeeTabListPlus#253]
i've posted an issue before (https://github.com/CodeCrafter47/BungeeTabListPlus/issues/241) and this issue was closed because nothing to seem that something wrong, but when i've completely update my spigot server (git-Spigot-7228328-6659ddf (MC: 1.12)), bungeecord server (build #1250) and bungeetablist plugin with bridge to the latest dev builds, one of spigot server crush again, but crash happens much later (few hours) but with the same error log (maybe not the same, not sure)... (https://pastebin.com/gYuQHv4n).

EDIT: I have removed economy placeholder from tablist for a while to check the situation...
What can i do? Maybe Gringotts has a bug? Maybe i should write to Gringotts author?

**Comment by CodeCrafter47** [comment]
The issue wasn't the same, but still quite similar (though less likely to occur). Should be fixed if you grab the latest dev-build now.
