### ISSUE TITLE
/btlp hide not working with sponge

### ISSUE THREAD

**Issue by Sir-Will** [CodeCrafter47/BungeeTabListPlus#254]
hey,

if I run `/btlp hide` it says you have been hidden but I'm still visible on the tab list. I have the SpongeBridge on the sponge server.

**Comment by CodeCrafter47** [comment]
By default players with the `bungeetablistplus.seevanished` permission can see vanished players. This can be configured, see https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerSets

Also note that the built-in hide command may not hide you entirely, your icon will remain visible on the tab list for all players on the same server unless the size of the tab list is 80 slots. It is therefore recommended to use a server side (i.e. Sponge) vanish plugin instead or in addition to the built-in command.

**Comment by Sir-Will** [comment]
Although I don't have that permission set anywhere, changing `hideenPlayers` to `INVISIBLE` seems to have solved my issue.

**Comment by Sir-Will** [comment]
Hm, still not working correctly. I'm not visible on the tab list but instead it shows someone else twice on it.

Any idea what's causing this?

**Comment by CodeCrafter47** [comment]
Such issues may occur when using a dynamic size tab list. To fix it either
 1. use a fixed size tab list with 80 slots or
 2. use a vanish plugin that supports removing players from the tab list (e.g. SuperVanish) or
 3. configure the tab list to always show hidden players.

**Comment by CodeCrafter47** [comment]
I think when using Sponge, any vanish plugin will do fine, because Sponge takes care of removing the tab list entry of vanished players (it won't remove your own though).

**Comment by Sir-Will** [comment]
It doesn't for this plugin. I'm using Nucleus for the vanish and it does remove me from the normal list but not if I'm using this plugin.

**Comment by CodeCrafter47** [comment]
That's right. But if you use `/btlp hide` while vanished using the Sponge plugin it'll remove you from the tab list correctly.

**Comment by Sir-Will** [comment]
Yes but I would like to hide from the tab list when using the vanish plugin like in bukkit and not use two commands every time.
