### ISSUE TITLE
Spectators are rendered as invisible players

### ISSUE THREAD

**Issue by MClausz** [CodeCrafter47/BungeeTabListPlus#259]
Why are spectator rendered as invisible players? This causes flying armor glitch like this:
http://i.imgur.com/DzpVDx0.png
When I disable bungeetablistplus on a certain server, this issue won't happen in that server.

**Comment by CodeCrafter47** [comment]
You can fix this by setting the size of the tab list to 80.

**Comment by MClausz** [comment]
I can't do that.
I'll cancel equipment packet.

**Comment by MClausz** [comment]
I fixed this by setting the tablist size to 80 3 years ago, but this doesn't work anymore on version 3.0.6
