### ISSUE TITLE
Support for Craftconomy3

### ISSUE THREAD

**Issue by danbovey** [CodeCrafter47/BungeeTabListPlus#26]
Awesome plugin! Only one issue: I've got Vault and Craftconomy3 installed on both of my Bungeecord Spigot servers but the tablist shows that the Balance is `-` even though /money is showing a real number.

![2015-04-28_16-45-37](https://cloud.githubusercontent.com/assets/1503076/7373719/05620684-edc6-11e4-890b-058b61dce2e9.jpg)

**Comment by CodeCrafter47** [comment]
You are required to put BungeeTabListPlus_BukkitBridge-7.jar on your spigot servers for this to work.

**Comment by danbovey** [comment]
Ah thanks :/
