### ISSUE TITLE
[1.12] Unexpected exception

### ISSUE THREAD

**Issue by FiveEYZ** [CodeCrafter47/BungeeTabListPlus#260]
Updated sponge to latest and started getting some weird spam in console, so I updated everything related to the spam: LuckPerms, GriefPrevention and BungeeTabListPlus_SpongeBridge (was already on 2.8.1)

So now im left with this error:
- https://gist.github.com/FiveEYZ/d0a8755ce395fd490aad080e7b442906
i get this error once every second

Running now:
BungeeTabListPlus_SpongeBridge-2.8.1-SNAPSHOT (same build on bungeecord)
LuckPerms-Sponge-3.2.64 (same build on bungeecord)
spongeforge-1.12-2443-7.0.0-BETA-2498

it all started when i updated from spongeforge-1.12-2397-7.0.0-BETA-2486 -> 2498

**Comment by FiveEYZ** [comment]
There have been some permission API changes for SpongeForge API 7.0.0:
https://github.com/SpongePowered/SpongeCommon/commit/8af77618887d0e0e8cce88141652ae0bef062430

**Comment by CodeCrafter47** [comment]
Fixed as of version 2.8.1.
