### ISSUE TITLE
playerOrder: "luckpermsgroupinforeversed" is in wrong order + sync issues

### ISSUE THREAD

**Issue by i9hdkill** [CodeCrafter47/BungeeTabListPlus#262]
Hey, we are using BTLP 2.8.0 on BungeeCord 1.12.1 with Luckperms 2.2.57

Thats our tablist config:
https://pastebin.com/MykCLLNn

In Luckperms, our admin groups have the highest weight as of Luckperms wiki:
https://github.com/lucko/LuckPerms/wiki/Command-Usage#lp-group-group-setweight
Lower groups have lower weights.

We have to use playerOrder: "luckpermsgroupinforeversed" to make the order correct(adminsFirst). But it should be luckpermsgroupinfo.
http://prntscr.com/g6cdsf
Pink(headadmin), red (admin), teal(moderator), orange and yellow(vip ranks), white(normal default user)

As you can see, this isn't just a sorting issue. Sometimes players with vip ranks or ranks at all, show up before admins. In this screenshot: Eisenbeiss +DiesteakPommes. They should have an orange color
If I look them up in LP, they have the vip rank group set. This is often fixed if they reconnect. But also often default users are showing up in front of admins.

**Comment by CodeCrafter47** [comment]
Please use a recent version of LuckPerms. If the issue persists contact its author.

**Comment by i9hdkill** [comment]
These white players are simply players without permission data. (Permission data couldn't be loaded via luckperms). Not BTLP fault.
