### ISSUE TITLE
Maven: Server Error 500

### ISSUE THREAD

**Issue by hibo98** [CodeCrafter47/BungeeTabListPlus#265]
Your maven repository returns HTTP error 500, when access certain subdirectories for example that one:
http://nexus.codecrafter47.dyndns.eu/content/repositories/public/codecrafter47/bungeetablistplus/bungeetablistplus-api-bungee/

Because of the errors I cant get any artifacts from your repository.

**Comment by CodeCrafter47** [comment]
Works fine right now. Though I admit that there are issues with it sometimes, but I'm too lazy to do something about it.
