### ISSUE TITLE
Luckperms placeholders not appearing

### ISSUE THREAD

**Issue by Seeroh** [CodeCrafter47/BungeeTabListPlus#271]
I am trying to display certain usergroups in the tablist, via using meta information.

I am using ${player luckperms_meta_metakey}, but it just doesn't parse while in the tablist.

If I parse it using /papi, it shows the information correctly, as well as this placeholder works fine in other plugins.

**Comment by CodeCrafter47** [comment]
Please use the `/btlp status` command to check whether BungeeTabListPlus was able to connect to the bridge plugin and PlaceholderAPI on the spigot server. Also make sure you're using the correct variant (player vs. viewer) of the placeholder in your tab list configuration file.

**Comment by Seeroh** [comment]
If I used ${viewer luckperms_meta_}, the placeholders would appear. But that would just place in MY meta keys, so every play on the list would show RANK <playername>.

/btlp status returns everything as working properly

**Comment by CodeCrafter47** [comment]
If the `viewer` variant of the placeholder works and the `player` variant doesn't then either
1. you're trying to use the `player` variant at a place where that is not possibly (only possible inside the playerComponent) or
2. all displayed players don't have the specific meta key set.

**Comment by Seeroh** [comment]
Should be possible for the first one, and the meta key is set for a fact, on the second one.

I am thinking that it could be related to the fact I don't have luckperms yet set up on the bungee server, thus it can't access the value? I am not sure if that's the case, but if I get it working via this method, I will give an update.

**Comment by CodeCrafter47** [comment]
When accessing placeholders through PlaceholderAPI you don't need to install LuckPerms on BungeeCord, only need to do that when using the built-in LuckPerms placeholders.
