### ISSUE TITLE
Feature? Sorting the tablist on server! (Non vault for people with custom permissions plugins)

### ISSUE THREAD

**Issue by TheSpeedCoder** [CodeCrafter47/BungeeTabListPlus#272]
Hello I don't use vault, or a BungeeCord based permissions plugin mine uses mysql to hand permissions over the bukkit servers but using plugin messaging channels to sort bungee permissions.
Anyway could you add some kind of api so that we can sort the tablist without vault or a proxy side permissions plugin or just get a integer from placeholder api and sort from higher to lower from that

**Comment by CodeCrafter47** [comment]
It is planned to add support for sorting players by any variable (include custom variables and variables from PlaceholderAPI). There's already an issue (#221). Unfortunately I cannot be specific as to when that will be implemented, don't expect it too soon, I'll be on vacation till October, then I'll probably be quite busy going to university.

**Comment by TheSpeedCoder** [comment]
Thanks I suppose i'll take a look into forking BungeePerms for now
