### ISSUE TITLE
placeholderapi name

### ISSUE THREAD

**Issue by Wqrld** [CodeCrafter47/BungeeTabListPlus#279]
with placeholderapi placeholders:
is it possible to use ${skript_team.%player%} replacing %player% with the player's name

edit: {team.{player}} fails because it parses wrongly

**Comment by CodeCrafter47** [comment]
That's not possible.

**Comment by Wqrld** [comment]
and why if i may asK?

**Comment by CodeCrafter47** [comment]
It is not possible to use a placeholder inside another. There is no technical reason for this, it is just that I feel it would make the configuration files more complicated and there is no real benefit from allowing it, i.e. no one has yet shown me a use case where this is absolutely required.

**Comment by Wqrld** [comment]
Well the use case ive given was per-user skript vars. Plusins like mvdwpapi also suport this.

**Comment by CodeCrafter47** [comment]
Yeah, but the script knows the player, so there is no reason to pass it as part of the placeholder name.

**Comment by Wqrld** [comment]
either you dont understand me or i dont understand you, the script cant know who is viewing the tablist?

**Comment by CodeCrafter47** [comment]
I can see your point there.

**Comment by Wqrld** [comment]
bump, this is already quite far in the future for me ;), any chance of you fixing this soon?

**Comment by CodeCrafter47** [comment]
I don't think this is going to be fixed soon.

**Comment by Wqrld** [comment]
i was able to workaround this by writing a custom papi hook but it would be better performance-wise if you could implement this on a later date

**Comment by CodeCrafter47** [comment]
It is now possible to use placeholders inside other placeholders. It does not yet work for all placeholders. One example of a use case that is supported is the permission placeholder. If you require this feature with any placeholder where it is not available yet, please create a new issue.
