### ISSUE TITLE
no tab anymore..?

### ISSUE THREAD

**Issue by Scorpionvssub** [CodeCrafter47/BungeeTabListPlus#28]
I have this bungeetablistplus 2.0 plugin and stopped working all together but there are no errors as to why its not working, i updated some of the plugins in the hub and other areas to 1.8.3 but then tab stopped working.. and you only provide .zip while it needs .jar o.O

**Comment by CodeCrafter47** [comment]
If you open the zip file you will find the jar file you need inside.
