### ISSUE TITLE
player names shown in dark_blue - can't change it?

### ISSUE THREAD

**Issue by smmmadden** [CodeCrafter47/BungeeTabListPlus#281]
I've looked through the config files and wiki, but I'm not seeing anything that shows what color the players name can be.  I'd like to have all players shown in white as the dark blue/red just can't be seen right.

Can someone tell me what I'm missing?
![image](https://user-images.githubusercontent.com/10309346/31313470-1a9d88b4-abb2-11e7-9f6c-5773aa2a1332.png)

Thanks!

**Comment by CodeCrafter47** [comment]
It has to do with the placeholder you use to display the player's name.

If you're using `${player display_name}`or `${player tab_name}` these might contain additional color codes or prefixes set by other plugins. If you don't want that use `${player name}` which is just the players name without any colors or anything else.

**Comment by smmmadden** [comment]
thank  you very much.  I was using ${player name} (the default) and it was changing the color.  So I just changed it to ${player display_name} and now the players are all white. :-)

Regards,
Steve
