### ISSUE TITLE
BungeeTabListPlus v2.8.2-SNAPSHOT generated an exception while executing task 70

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#286]
Caught this during a server stop:
https://pastebin.com/raw/pdwx3nBz

Using:
2.8.2-Dev-#712

**Comment by andrewkm** [comment]
@CodeCrafter47 any updates on this one?

**Comment by CodeCrafter47** [comment]
It's not harmful.

**Comment by andrewkm** [comment]
@CodeCrafter47 alright. Closed it off.
