### ISSUE TITLE
i need help with my config

### ISSUE THREAD

**Issue by friishon** [CodeCrafter47/BungeeTabListPlus#289]
hi, i'm trying to make the tablist with dynamic size, but i have errors

config 
https://pastebin.com/FwfJfk7M

error 
![bungeetablist](https://user-images.githubusercontent.com/19889173/32676040-60ac1d7c-c659-11e7-9c35-ad6bcc920197.png)

can someone help me?

i'm trying to only see players counter per each server, not global, (currentserver)

**Comment by CodeCrafter47** [comment]
Indentation in lines 81 to 83 is wrong. These are top level configuration options and thus must not be indented.

**Comment by friishon** [comment]
thanks, this fix my problem
