### ISSUE TITLE
World name and prefix does not work

### ISSUE THREAD

**Issue by Pl4ntnet** [CodeCrafter47/BungeeTabListPlus#29]
The variable {name} world does not work with my TabList. In addition, the prefix does not appear from permissionsEx, although I config under permissionSource: bukkit have set. Am I doing something wrong or is this purely a bug?
It would be nice if you would write to me via mail back!
Sincerely PlantNet [plantnet@gmx.de]

default.yml: http://pastebin.com/pPKdftsj
config.yml: http://pastebin.com/CLBX5XMj

**Comment by CodeCrafter47** [comment]
You shouldn't use {world} in groupLines as these are generated once time for every server, as a server may have multiple worlds at that place there is no logical replacement for {world}.

In order for prefixes to work correctly, you need to put BungeeTabListPlus_BukkitBridge.jar on all you bukkit/spigot servers. Vault is needed too.

**Comment by Pl4ntnet** [comment]
#### Thank you very much for your response!
The solution was to install Vault and bukkit_bridge.

But (sorry I'm German) I do not understand what you mean with: _"You shouldn't use {world} in groupLines as these are generated once time for every server, as a server may have multiple worlds at that place there is no logical replacement for {world}."_.

My problem is that  on my server (I have currently only one on my bungeecord), I have linked two several worlds with Multiverse (a lobby and a Farm World) I would like to not be in the TabList show which **server** I am, but on what **world**. Is this possible?

*Sorry for my bad English!*

_[please reply :)]_

**Comment by CodeCrafter47** [comment]
Also, Wenn groupPlayers auf SERVER gesetzt ist dann gruppiert das Plugin die Spieler nach Server (Beispiel: <http://www.spigotmc.org/attachments/2014-05-09_13-29-58-png.3026/>). Der Text in groupLines dient dazu, die Überschrift, also das "> server" zu generieren. Dazu fügt das Plugin den Text in groupLines einmal für jeden server in die TabList ein, {fillplayers} wird dabei durch alle Spieler auf dem jeweiligen Server ersetzt, {server} durch den Namen des Servers. Da auf einem Server oft mehrere Spieler sind und diese sich in mehreren Welten aufhalten können, gibt es aus Sicht des Plugins erstmal nichts womit es {world} ersetzen könnte.

Tatsächlich wird das Plugin {world}, wenn es in groupLines auftritt, durch die Welt, in der der Spieler, der die TabList betrachtet, ist, ersetzen. Damit funktioniert deine Konfigurationsdatei sogar. Allerdings wird, sobald du mehrere Server hast, der Name der Welt, in der der Spieler ist, mehrfach angezeigt werden, was eventuell etwas seltsam aussehen wird. Deshalb empfehle ich groupPlayers auf NONE zu setzen und die Welt in der der Spieler ist z.B. anstelle des Datums einzufügen.
