### ISSUE TITLE
Request custom player order.

### ISSUE THREAD

**Issue by aWitch-Doctor** [CodeCrafter47/BungeeTabListPlus#296]
Is it possible for me to not use one of the player orders listed on https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder and instead create a custom order similar to the custom place holder section using placeholders and assigning weights to them? I have luck perms and the default group is not correct for everyone. If i could make an order going off of ${player permission <permission>} that would solve all my problems.

**Comment by CodeCrafter47** [comment]
That's not possible at the moment. Also this is a duplicate of #221

**Comment by aWitch-Doctor** [comment]
... i searched all the issues, open and closed, for player order and couldn't find anything about this. Sorry for the duplicate.

**Comment by CodeCrafter47** [comment]
It is now possible to sort players by any placeholder. Have a look at <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder>.
