### ISSUE TITLE
Tab Color Issues

### ISSUE THREAD

**Issue by itismejoey** [CodeCrafter47/BungeeTabListPlus#30]
Hi!

For some reason, only my hub server names have the color of their names. All the other servers have white names. Why would this happen? I am using the exact code that came from the Config-example page.

Thanks in advance for any assistance.
![2015-05-30_22 59 45](https://cloud.githubusercontent.com/assets/7752812/7900358/b2eed8f0-071f-11e5-81d5-e86626d72058.png)

**Comment by CodeCrafter47** [comment]
The plugin looks up the name color/ permission group on the server the player is connected to. On your hub server your setup is probably different from your other servers which causes the difference.

**Comment by itismejoey** [comment]
Shouldn't it at least change when someone has a nickname? All the settings are the same for both servers.

**Comment by CodeCrafter47** [comment]
If the settings and installed plugins were same on both servers then the colors would also work on both servers.
Maybe this helps you: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/coloredplayernames
