### ISSUE TITLE
No heads

### ISSUE THREAD

**Issue by justinbea** [CodeCrafter47/BungeeTabListPlus#303]
I am trying to make an tablist, we only wants some server information and the online player counter per server, i have tried this in my config.

https://pastebin.com/H44fn12X

and got this: https://gyazo.com/f67babc7d11ae765b71f535297719670
you see on the right bottom the heads of online players, i want to disable that. the tab is not done just in progress

**Comment by CodeCrafter47** [comment]
The heads of all players on the same server as the player looking at the tab list need to appear on the tab list, to avoid gameplay issues. If your config doesn't make sure of that then, as you can see, the plugin adds them at the bottom right. Only exception is if the tab list is configured to use all 80 slots. In that case no player heads are required to be displayed.

**Comment by justinbea** [comment]
thread closed
