### ISSUE TITLE
Vault and Permissions EX Prefix not work

### ISSUE THREAD

**Issue by joeymaeuslp** [CodeCrafter47/BungeeTabListPlus#305]
the vault prefix from permissions ex dount work please fix it

**Comment by CodeCrafter47** [comment]
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PermissionsEx

**Comment by joeymaeuslp** [comment]
Exactly that I followed it But not the prefix is ​​not displayed Vault is on it pex is on it everything is there but it does not work

**Comment by CodeCrafter47** [comment]
Please connect to the server and run the `/btlp status` command. You must run that command ingame.

The command will tell you whether you have BungeeTabListPlus_BukkitBridge installed on your Spigot servers. If not please install it. The wiki page I linked told you to do so.

**Comment by joeymaeuslp** [comment]
i have the bridge installed

**Comment by joeymaeuslp** [comment]
it is a bug you plugin dont work

**Comment by CodeCrafter47** [comment]
There's no bug in the plugin. You're just using it the wrong way. But unless you tell me what you are doing, I can't tell you what you're doing wrong.

**Comment by joeymaeuslp** [comment]
Here is my Config


showTo: "all"
priority: 0

playerSets:
  lobby:
    filter: ${player server} == "CityBuild01"
# A simple header and footer
showHeaderFooter: true
header:
- '&2Proxy&7Socke&a.net &7Netzwerk'
headerAnimationUpdateInterval: 1.0
footer:
- '&6Aktueller Server: &7${viewer server}'
footerAnimationUpdateInterval: 1.0

# We want a dynamic size tab list
type: DYNAMIC_SIZE

# Below are the options specific to the dynamic size tab list

# Here you can configure which players to display by specifying a player set.
# For this example we are using the `all_players` player set created above.
playerSet: lobby

# Here the order of the players can be configured.
playerOrder: "alphabetically"

# This option controls the format of the players names.
playerComponent: '${viewer vault_prefix} ${player vault_balance}'

**Comment by joeymaeuslp** [comment]
`showTo: "all"
priority: 0

playerSets:
  lobby:
    filter: ${player server} == "CityBuild01"

showHeaderFooter: true
header:
- '&2Proxy&7Socke&a.net &7Netzwerk'
headerAnimationUpdateInterval: 1.0
footer:
- '&6Aktueller Server: &7${viewer server}'
footerAnimationUpdateInterval: 1.0


type: DYNAMIC_SIZE


playerSet: lobby


playerOrder: "alphabetically"


playerComponent: '${viewer vault_prefix} ${player vault_balance}'`

**Comment by CodeCrafter47** [comment]
You have
```
playerComponent: '${viewer vault_prefix} ${player vault_balance}'`
```
Using `${viewer vault_prefix}` there is obviously wrong. You should be using `${player vault_prefix}`. Also putting `${player name}` there too might not be such a bad idea.

**Comment by joeymaeuslp** [comment]
${player vault_prefix} is not working i have the bridge installed and valut and pex your plugin dont work 
on the server of my buddy it is not synonymous so s.Plugin have a look please check your source code if Vault hooks properly

**Comment by CodeCrafter47** [comment]
There is no such issue in the source code. I can recommend you again to
 * use the `/btlp status` command to check whether the bridge plugin is installed and detected by the proxy plugin.
 * check the log files of BungeeCord and Spigot for any error messages.

**Comment by joeymaeuslp** [comment]
The plugin in itself Works the only thing that does not work are the vault groups variable vault money works so just permissionsex variable does not want to show

**Comment by CodeCrafter47** [comment]
Please perform the steps I told you to do in my previous comment. The plugin might actually be telling you what you're doing wrong.

**Comment by joeymaeuslp** [comment]
should I send you my complete server then you can see that I have done everything right
hier ist der link um den server zu downloaden du wirst sehen ich hab alles richtig eingestellt bitte lad ihn dir mal runter und sieh es dir bitte an

http://www.mediafire.com/file/4jy65zcm8i71jv3/Network.rar

**Comment by CodeCrafter47** [comment]
Works perfectly fine. Though I noticed your PEX configuration does not contain any groups or permissions, and no prefixes either. I suggest you check out the PEX wiki on how to use the plugin.

**Comment by joeymaeuslp** [comment]
if I use pex with mysql the plugin will not work please visit my server proxysocke.net

**Comment by CodeCrafter47** [comment]
How  you configure your permission plugin is your problem.

**Comment by joeymaeuslp** [comment]
groups:
  Owner:
    prefix: '&4&lOwner'
    options:
      default: false
    permissions:
     - -nte.admin
     - -nte.mod
     - -nte-srmod
     - -nte.teamladder
     - -nte.supp
     - -nte.builder
     - -nte.premium
     - -nte.alphaboss
     - -nte.spieler
     - nte.owner
     - '*'
  Admin:
    prefix: '&4Admin'
    options:
      default: false
    permissions:
     - -nte.owner
     - -nte.mod
     - -nte-srmod
     - -nte.teamladder
     - -nte.supp
     - -nte.builder
     - -nte.premium
     - -nte.alphaboss
     - -nte.spieler
     - nte.admin
     - '*'
  Teamleader:
    prefix: '&cTeamleader'
    options:
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.tp
     - essentials.tp.others
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.invsee
     - essentials.fly
     - essentials.socialspy
     - essentials.vanish
     - essentials.vanish.interact
     - essentials.vanish.see
     - essentials.sethome.multiple.moderator
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.weather
     - essentials.time
     - essentials.time.set
     - essentials.balance
     - essentials.pay
     - ab.kick.use
     - ab.kick.notify
     - ab.tempban.dur.1
     - ab.ban.notify
     - ab.ban.undo
     - ab.ipban.notify
     - ab.mute.perma
     - ab.mute.temp
     - ab.mute.notify
     - ab.mute.undo
     - ab.warn.perma
     - ab.warn.temp
     - ab.warn.notify
     - ab.warn.undo
     - ab.all.undo
     - ab.warns.own
     - ab.warns.other
     - ab.check
     - ab.check.ip
     - ab.changeReason
     - ab.banlist
     - ab.history
     - ab.tempban.notify
     - nte.teamladder
     - crash.alert
     - permissions.manage.membership.SrModerator
     - permissions.manage.membership.Moderator
     - permissions.manage.membership.Supporter
     - permissions.manage.membership.Builder
     - permissions.manage.membership.Spieler
     - hideandcustomplugins.bypass
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  SrModerator:
    prefix: '&cSr.Mod'
    options:
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.tp
     - essentials.tp.others
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.invsee
     - essentials.fly
     - essentials.socialspy
     - essentials.vanish
     - essentials.vanish.interact
     - essentials.vanish.see
     - essentials.sethome.multiple.moderator
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.weather
     - essentials.time
     - essentials.time.set
     - essentials.balance
     - essentials.pay
     - ab.kick.use
     - ab.kick.notify
     - ab.tempban.dur.1
     - ab.ban.notify
     - ab.ban.undo
     - ab.ipban.notify
     - ab.mute.perma
     - ab.mute.temp
     - ab.mute.notify
     - ab.mute.undo
     - ab.warn.perma
     - ab.warn.temp
     - ab.warn.notify
     - ab.warn.undo
     - ab.all.undo
     - ab.warns.own
     - ab.warns.other
     - ab.check
     - ab.check.ip
     - ab.changeReason
     - ab.banlist
     - ab.history
     - ab.tempban.notify
     - nte.srmod
     - crash.alert
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  Moderator:
    prefix: '&cMod'
    options:
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.tp
     - essentials.tp.others
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.invsee
     - essentials.fly
     - essentials.socialspy
     - essentials.vanish
     - essentials.vanish.interact
     - essentials.vanish.see
     - essentials.sethome.multiple.moderator
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.weather
     - essentials.time
     - essentials.time.set
     - essentials.balance
     - essentials.pay
     - ab.kick.use
     - ab.kick.notify
     - ab.tempban.dur.1
     - ab.ban.notify
     - ab.ban.undo
     - ab.ipban.notify
     - ab.mute.perma
     - ab.mute.temp
     - ab.mute.notify
     - ab.mute.undo
     - ab.warn.perma
     - ab.warn.temp
     - ab.warn.notify
     - ab.warn.undo
     - ab.all.undo
     - ab.warns.own
     - ab.warns.other
     - ab.check
     - ab.check.ip
     - ab.changeReason
     - ab.banlist
     - ab.history
     - ab.tempban.notify
     - nte.mod
     - crash.alert
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  Supporter:
    prefix: '&9Supp'
    options:
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.invsee
     - essentials.fly
     - essentials.vanish
     - essentials.vanish.interact
     - essentials.sethome.multiple.supporter
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.socialspy
     - essentials.tp
     - essentials.tp.others
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.balance
     - essentials.pay
     - ab.kick.use
     - ab.mute.temp
     - ab.mute.undo
     - ab.warn.temp
     - ab.warn.notify
     - ab.warns.own
     - ab.warns.other
     - ab.check
     - ab.check.ip
     - ab.banlist
     - ab.history
     - nte.supp
     - crash.alert
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  Builder:
    options:
      prefix: '&bBuilder'
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - plots.worldedit.bypass
     - essentials.tpa
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.gamemode.creative
     - essentials.gamemode.survival
     - essentials.gamemode.spectator
     - essentials.gamemode
     - essentials.invsee
     - essentials.invsee.modify
     - essentials.heal
     - essentials.heal.cooldown.bypass
     - essentials.heal.others
     - essentials.fly
     - essentials.vanish
     - essentials.vanish.interact
     - essentials.sethome.multiple.builder
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.tp
     - essentials.tp.others
     - essentials.socialspy
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.weather
     - essentials.time
     - essentials.time.set
     - essentials.balance
     - essentials.pay
     - nte.builder
     - worldedit.*
     - crash.bypass
     - crash.alert
     - hideandcustomplugins.bypass
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  AlphaBoss:
    prefix: '&5AlphaBoss'
    options:
      default: false
    permissions:
     - plots.plot.10
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.sethome.multiple.alphaboss
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.chat.color
     - essentials.chat.format
     - essentials.balance
     - essentials.pay
     - essentials.enderchest
     - essentials.recipe
     - essentials.workbench
     - essentials.nick
     - nte.alphaboss
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.type.villager
     - echopet.pet.type.creeper
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  Premium:
    prefix: '&6Premium'
    options:
      default: false
    permissions:
     - plots.plot.6
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.sethome.multiple.premium
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.chat.color
     - essentials.balance
     - essentials.pay
     - essentials.recipe
     - essentials.nick
     - nte.premium
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.type.cow
     - echopet.pet.type.pig
     - echopet.pet.type.wolf
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
  Spieler:
    prefix: '&7Spieler'
    options:
      default: true
    permissions:
     - plots.plot.4
     - plots.use
     - plots.info
     - plots.claim
     - plots.auto
     - plots.home
     - plots.clear
     - plots.delete
     - plots.set.flag
     - plots.permpack.basicflags
     - plots.flag.add
     - plots.flag.remove
     - plots.flag.list
     - plots.flag
     - plots.chat
     - plots.toggle.chat
     - plots.denied
     - plots.add
     - plots.trust
     - plots.deny
     - plots.remove
     - plots.untrust
     - plots.undeny
     - plots.kick
     - plots.visit
     - plots.visit.owned
     - plots.visit.shared
     - plots.visit.other
     - essentials.tpa
     - essentials.worlds.*
     - essentials.tpaccept
     - essentials.msg
     - essentials.signs.use.buy
     - essentials.signs.use.sell
     - essentials.signs.use.warp
     - essentials.warp
     - essentials.warp.list
     - essentials.warps.*
     - essentials.sethome.multiple.spieler
     - essentials.sethome
     - essentials.delhome
     - essentials.home
     - essentials.msg
     - essentials.balance
     - essentials.pay
     - nte.spieler
     - banknotes.withdraw
     - BossShop.open
     - vc.vote
     - echopet.pet.select
     - echopet.pet.ride.*
     - echopet.pet.hat.*
     - echopet.pet.type.chicken
     - echopet.pet.remove
     - echopet.pet.hide
     - echopet.pet.call
     - echopet.pet.name
schema-version: 1
users:

**Comment by joeymaeuslp** [comment]
where is the problem with this Pex Configuration all plugins work with it
the problem is that your plugin does not support pex mysql lso it is useless for bungeecord server

**Comment by CodeCrafter47** [comment]
BungeeTabListPlus works fine with PEX+MySQL.

You might be able to find general help setting up your server on the spigot forums.

**Comment by joeymaeuslp** [comment]
No it does not work with Pex mysql when I activate mysql the plugin is not at all anymore I just tested it you have a bug while programming your plugin is extremely good but please fix this bug please it is the plugin

**Comment by CodeCrafter47** [comment]
https://github.com/CodeCrafter47/BungeeTabListPlus/issues/306#issuecomment-358253438
