### ISSUE TITLE
BungeetablistPlus and Pex mysql answer

### ISSUE THREAD

**Issue by joeymaeuslp** [CodeCrafter47/BungeeTabListPlus#307]
yes I understand that but synonymous but test your plugin yourself please times with mysql pex and you will see that it does not work then please write in the description of your plugin purely the btlp not working with pex mysql

**Comment by CodeCrafter47** [comment]
I just tested it with MySQL and - no surprise - it worked as expected.

**Comment by joeymaeuslp** [comment]
please send me your version of valut that you use

**Comment by CodeCrafter47** [comment]
I used the version of the plugins you send me in the .rar file. I only changed PEX config to use mysql.
