### ISSUE TITLE
Steve/Alexa heads

### ISSUE THREAD

**Issue by NoHoPeLess** [CodeCrafter47/BungeeTabListPlus#31]
Hello i have some trouble with my tablist, as you can see there are steve/alexa skins:

![bkrvmgwk](https://cloud.githubusercontent.com/assets/6246520/7928516/bc33f930-08f1-11e5-99d9-45c179793a89.png)

We use Bungee Build 1068

When i start the Bungee all its fine, when i join result in this "error"? and it makes the tablist show steve/alexa heads...

The only thing in the ProxyLog is this:

06:25:48 [INFO] [BC-Info]: [+] NoHoPeLess
06:25:48 [WARNING] [BungeeTabListPlus] Hit mojang rate limits while fetching uuid for foxfire.

And yes i try to turn off Bungee for 5 minutes / 10 minutes / 15 minutes, nothing happend.

Please Help :)

**Comment by NoHoPeLess** [comment]
After 30 Minutes it works... but its sometimes this issue.... any fix for that?

**Comment by NoHoPeLess** [comment]
Have some ideas i think this is because an rate limit from mojand ddos protection, maybe? so it allowed only 600 skins per hour per ip, i think. Can u make a user cache? Or is there another fix?

**Comment by NoHoPeLess** [comment]
So im again, i think this is why this pl works async he can handle the names...

I fix it for me i use the UUID in the defaultSkin.

So i hope he fix that or make some Informations about that.

PS. sry for my bad english :D

**Comment by CodeCrafter47** [comment]
The plugin caches skins/ uuids, but if a skin is not used for 5 minutes it is withdrawn. Probably changing that delay will fix the issue.
