### ISSUE TITLE
Please Help me again

### ISSUE THREAD

**Issue by joeymaeuslp** [CodeCrafter47/BungeeTabListPlus#310]
Ask for new help the plugin goes to the test server with mysql but not on my judges server everything is now set correctly from he the prefix is ​​not displayed again I'm despairing

there are any plugins that have a konfilct with btlp

**Comment by CodeCrafter47** [comment]
This is not the correct place to seek configuration help. Please use the forum instead.

You may use the `/pex user <user> prefix` command to check whether you configured the prefix in pex.

**Comment by joeymaeuslp** [comment]
iam use a other plugin thank you :(
