### ISSUE TITLE
All the heads Img didnt show

### ISSUE THREAD

**Issue by WahyuAgung27** [CodeCrafter47/BungeeTabListPlus#321]
Hi, I'd like to report some bugs of your plugin..
First, all the img heads didnt show in my tablist
Please help me. I will give you the screenshoot.
![image](https://user-images.githubusercontent.com/36497093/36242146-e7e4414a-124c-11e8-89f0-3c1300324a90.png)

**Comment by CodeCrafter47** [comment]
Heads don't appear on offline mode (cracked) servers.
