### ISSUE TITLE
[suggestion] Citizens and BTLP

### ISSUE THREAD

**Issue by airoons** [CodeCrafter47/BungeeTabListPlus#323]
Hello,

I'll leave a quick suggestion - could you hook into the Citizens and hide their NPC's as Essentials Vanish hook can fully hide vanished players? I have tried many Citizens and BTLP version combinations, all of them had one issue - NPC blinks in the tab every so often, but it is noticeable.

**Comment by CodeCrafter47** [comment]
That's not possible. The NPC's need to appear on the tab list for a short time, otherwise the player wouldn't be able to see them. You can also observe this behavior without BTLP.

**Comment by TheIronMinerLv** [comment]
Sorry for the long response, so there wouldn't be any way to hide them? How do a larger servers fight with such problem?

**Comment by CodeCrafter47** [comment]
There is one way to hide them: Configure BungeeTabListPlus to display a fixed size tab list using the maximum of 80 slots.
