### ISSUE TITLE
custom heads for rank, balance and etc

### ISSUE THREAD

**Issue by ConflictKingdoms** [CodeCrafter47/BungeeTabListPlus#328]
so i got my friend to edit some png for rank,ping and  server

ive got ping to work only and i get this

09.03 23:49:40 [Server] WARNING [BungeeTabListPlus] An server side error occurred while preparing head rank.png
09.03 23:49:40 [Server] WARNING [BungeeTabListPlus] An server side error occurred while preparing head server.png
09.03 23:49:40 [Server] WARNING [BungeeTabListPlus] An server side error occurred while preparing head rank.png
09.03 23:49:40 [Server] WARNING [BungeeTabListPlus] An server side error occurred while preparing head server.png

ive never touched the heads before like this edit them etc.

if u can give me tips on how i actually my own heads that be great

Thanks
- TimRambo

**Comment by CodeCrafter47** [comment]
That error is not your fault. Just try it again at another time. Seems to be working just fine right now,

**Comment by ConflictKingdoms** [comment]
yea i figured it out just tried after few mins etc :D thanks CodeCrafter47
