### ISSUE TITLE
some of png heads not shown

### ISSUE THREAD

**Issue by pixelcrafter001** [CodeCrafter47/BungeeTabListPlus#335]
First sorry when my english no correkt i'm from Germany and i'm not the best in english ...

I had some 8x8 png's made and they are normaly shown but all without one will be not shown (they are purple black) one is shown and its shown my editet the rest will not show...

here is the failure from the console

PS: normal skins from player will be show normaly

> 09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head water1.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head water1.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head water1.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
09:57:21 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png

**Comment by CodeCrafter47** [comment]
Not your fault. Restart the server or reload the plugin and it should work.

**Comment by pixelcrafter001** [comment]
I have all restartet one Head has been loaded the rest not

> 13:53:10 [INFORMATION] BungeeCord has been reloaded. This is NOT advisable and you will not be supported with any issues that arise! Please restart BungeeCord ASAP.
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
13:53:10 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
13:53:11 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
>btlp reload
13:53:19 [INFORMATION] [BungeeTabListPlus] Loading default.yml
13:53:19 [INFORMATION] Successfully reloaded BungeeTabListPlus.
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head rank.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head players.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head clock.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head server.png
13:53:19 [WARNUNG] [BungeeTabListPlus] An server side error occurred while preparing head ping.png

I have restartet the bungee server and the mc server... 
is on the mc server a file where I also put the heads or is all on bungee?

**Comment by CodeCrafter47** [comment]
The heads only go on bungee, as I said you're not doing anything wrong.

The feature uses an external web service which fails sometimes. I'm working on fixing it.

**Comment by pixelcrafter001** [comment]
I'm using bungee ... the warnings from the console are from the bungee console...

**Comment by CodeCrafter47** [comment]
The plugin uploads the custom icons to a webservice at <http://skinservice.codecrafter47.de> which uploads it to mojang servers.

**Comment by CodeCrafter47** [comment]
I've (hopefully) fixed the webservice, so if you restart Bungee or use the `/btlp reload` command now, it should load all your icons (though it takes ~1 minute per icon).

**Comment by pixelcrafter001** [comment]
I will not want to annoy now but the links to the submission are down

Or what i do false ... can you show me how I can use it or make a video for sending heads... I must go off (work) I hope you can help ...
but thanks for your Help

**Comment by CodeCrafter47** [comment]
You don't need to use the link above by yourself. I just put it there for informative purposes.

What you need to do is to restart your server again, and then it'll work.

**Comment by pixelcrafter001** [comment]
Thanks after 5 or so restarts all pngs load and will be work finde :D 
thanks for your help
