### ISSUE TITLE
Players can see names on the tablist for a few seconds for players entering a server as vanished.

### ISSUE THREAD

**Issue by MithrandirCraft** [CodeCrafter47/BungeeTabListPlus#344]
Players can see names on the tablist for a few seconds for players entering a server as vanished with PremiumVanish.
I'll offer more details if necessary. Reported this issue to both PV and BungeeTablListPlus.
BTLP v. 2.8.2
PremiumVanish v. 2.0.5

**Comment by CodeCrafter47** [comment]
I know about this. You already reported this issue last year. See #283. I don't see this being fixed anytime soon.

**Comment by MithrandirCraft** [comment]
Dudes, talk to each other, please. This is a classic case of "not my problem" on something you could probably easily solve.
![image](https://user-images.githubusercontent.com/6623704/50047803-5f590800-00bd-11e9-847c-138dd4524e7e.png)

**Comment by MithrandirCraft** [comment]
Dudes, talk to each other, please. This is a classic case of "not my problem" on something you could probably easily solve together.
![image](https://user-images.githubusercontent.com/6623704/50047803-5f590800-00bd-11e9-847c-138dd4524e7e.png)

**Comment by CodeCrafter47** [comment]
I'm not saying there's nothing I can do about it. It's just that this issue doesn't affect me personally, on top of that is doesn't affect a lot of people (only those using a vanish plugin) and even if you're using a vanish plugin I don't think being visible on the tab list for a few seconds is a big deal. Players don't look at it that often.

I don't know how hard it is to fix this issue, but I think it should be possible for BungeeTabListPlus to communicate with the PremiumVanish BungeeCord plugin to figure out whether a player is vanished without a delay.

I don't see myself working on that in the near future, however BungeeTabListPlus is on GitHub, so other people can work on it too.

**Comment by CodeCrafter47** [comment]
This issue has been fixed with the latest update.
