### ISSUE TITLE
Incorrect config setup crashes player / requires killing bungee.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#345]
https://pastebin.com/raw/ViA3P1ij

Incorrect tab list setup crashes the player that runs /btlp reload
Further more, fixing your mistakes and trying to /btlp reload wether in game or in console is of no use.

You MUST end up closing the bungee instance and restarting it to fix the problem. :( 

V 2.8.4 Build 726

**Comment by CodeCrafter47** [comment]
Now it shouldn't crash anymore.
