### ISSUE TITLE
BungeeTabListPlus potentially causing rare full server crash.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#349]
We recently experienced server crashing.
https://hub.spigotmc.org/jira/browse/SPIGOT-3932

Console log at time of crash:
https://gist.githubusercontent.com/andrewkm/96b19c6863d79528798ef9159de763bc/raw/9d2605a25e427e0bd9d2ce58f4b209c52526e17c/gistfile1.txt

Full crash report:
https://gist.githubusercontent.com/andrewkm/98448b80466084770392917c6bb62727/raw/16b91e5ce98dbdf285f596049d0ea298ee2a9284/gistfile1.txt

Going off the recent tasks section we see BTLP doing quite a lot there.
https://i.imgur.com/rLAPQjL.png

We have examined every plugin listed here, and the only culprit that makes sense to us after speaking to the developers of the other plugins is BungeeTabListPlus.

Can you potentially look into the crash reports in the Spigot ticket above?

I'm am using the following BTLP version:
2.8.4-Dev-#728

Soemthing to note:
This ALL started happening since I added the locations of players to tab:
```
    - {text: "&cLocation:", icon: "default/server.png", ping: 0}
    - {text: "&cX: &6${viewer location_x 1.0}", icon: "default/server.png", ping: 0}
    - {text: "&cY: &6${viewer location_y 1.0}", icon: "default/server.png", ping: 0}
    - {text: "&cZ: &6${viewer location_z 1.0}", icon: "default/server.png", ping: 0}
```

Here is my entire tablist configuration:
https://pastebin.com/raw/PNN45Uwn

**Comment by CodeCrafter47** [comment]
I don't think this issue is related to BungeeTabListPlus. I've looked at the Spigot ticket and I think the issue happens because the world is being modified by a plugin in an async task. BTLP doesn't modify the world.

**Comment by andrewkm** [comment]
Thank you for your reply :)
