### ISSUE TITLE
Tryed to Schem save with Worldedit (and AsyncWorldEdit)

### ISSUE THREAD

**Issue by M9GLiquid** [CodeCrafter47/BungeeTabListPlus#35]
02.07 22:15:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:35 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:35 [Server] INFO java.lang.NullPointerException
02.07 22:15:35 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:35 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:35 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:35 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:35 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:35 [Server] INFO java.lang.NullPointerException
02.07 22:15:35 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO java.lang.NullPointerException
02.07 22:15:34 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO java.lang.NullPointerException
02.07 22:15:34 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO java.lang.NullPointerException
02.07 22:15:34 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:34 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:34 [Server] INFO java.lang.NullPointerException
02.07 22:15:34 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO java.lang.NullPointerException
02.07 22:15:33 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO java.lang.NullPointerException
02.07 22:15:33 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO java.lang.NullPointerException
02.07 22:15:33 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem
02.07 22:15:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot38.jar:git-Spigot-3ccbe77-a6a57a9]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.run(PlayerInformationUpdateTask.java:61) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.PlayerInformationUpdateTask.update(PlayerInformationUpdateTask.java:95) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.informationhooks.VaultHook.getInformation(VaultHook.java:110) [BungeeTabListPlus_BukkitBridge-7.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:120) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.getBalance(Economy_Craftconomy3.java:278) ~[Vault.jar:?]
02.07 22:15:33 [Server] INFO java.lang.NullPointerException
02.07 22:15:33 [Server] WARN §cAn internal error occured! Please send the following stacktrace to the developer in order to help resolving the problem

**Comment by M9GLiquid** [comment]
Inchat error:
http://prntscr.com/7o6y7g

**Comment by CodeCrafter47** [comment]
I don't think this has anything to do with WorldEdit. It looks like your Economy plugin isn't setup correctly.

However using the latest dev-build of this plugin may help you as it only queries economy data if you use the corresponding variable in the tablist.
