### ISSUE TITLE
Create multiple TabLists

### ISSUE THREAD

**Issue by meandpiggy** [CodeCrafter47/BungeeTabListPlus#353]
Okay, I read up on the wiki about a tablist for each server, and I already created the different tablists for each server... But, I was wondering if I need to change anything in the config.yml? Thanks

**Comment by CodeCrafter47** [comment]
You don't need to make changes to config.yml.

**Comment by meandpiggy** [comment]
Also... It said the priority needed to be higher than the default... What about the priority of all 4? Like this:
Default: priority = 0
Default2: priority = 5
Default3: priority = 5
Default4: priority = 5

Is that right? Thanks
