### ISSUE TITLE
${playerset:all_players size} error

### ISSUE THREAD

**Issue by B4TT3RY** [CodeCrafter47/BungeeTabListPlus#356]
playerSets:
  all_players:
    filter: all

type footer "${playerset:all_players size}"

print 8, but all online players size is 7
i cant understand this problem helpme

sorry for my bad english

**Comment by CodeCrafter47** [comment]
You can configure the plugin to display all players, then you can see who those 8 players are.

Alternatively I can also recommend comparing it with the numbers displayed by `/glist`, especially the total player count.

**Comment by B4TT3RY** [comment]
I will test it in a few hours! thx
and /glist is display 7 players

**Comment by CodeCrafter47** [comment]
Did you find out anything?

**Comment by B4TT3RY** [comment]
Oh I'm sorry. I did not check it because I did not have time.

**Comment by B4TT3RY** [comment]
@CodeCrafter47 
![Image](https://i.imgur.com/7p4Rfho.png)

How to solve this?

**Comment by B4TT3RY** [comment]
solved it the other way.
playerSets:
  all_players:
    filter: ${player server} == "server1" || ${player server} == "server2"

now it works! XD
