### ISSUE TITLE
Strange tab messup

### ISSUE THREAD

**Issue by ProMiner909** [CodeCrafter47/BungeeTabListPlus#36]
For the last few days this has been happening to the wantedcraft network @ wantedcraft.net
http://imgur.com/BM4v2zI

Everything moves about its confusing layers if we cant gget a fix soon am gonna have to find another plugin till there is a fix for this issue

**Comment by CodeCrafter47** [comment]
Use the latest dev-build. It will fix the error.

**Comment by ProMiner909** [comment]
Ok ill try it thanks

**Comment by ProMiner909** [comment]
Still happening http://imgur.com/ycJ8vqh

**Comment by CodeCrafter47** [comment]
I've been on your network for a while. It seems that whenever some leaves the server you're player on your tablist "looses" one slot, thus it gets smaller and smaller which makes it look weird. The strange this is, that this bug only occurs on your survival server, but not on your hub server.

**Comment by CodeCrafter47** [comment]
That bug is really strange. I cannot reproduce it. Maybe it's a conflict with another plugin, but I can't imagine how something like that could happen.

**Comment by CodeCrafter47** [comment]
BTW: You could set tab_size to 80. You would need to adjust your layout a bit as you have 4 columns then, but setting tab_size to 80 fixes most issues that happen on 1.8 clients.

**Comment by ProMiner909** [comment]
Ill try it tomorrow morning as most of our players come on at this time

**Comment by ProMiner909** [comment]
Seems to have fixed with tab size:80
