### ISSUE TITLE
Permission check spam.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#362]
Is there any reason why this plugin is constantly checking this permission, basically almost every second for every player?

[18:32:09] [luckperms-3/INFO]: [LP] VB > username - bungeetablistplus.seevanished - undefined

Been doing some debugging with luckperms, and noticed this being the only plugin that continuously spams this permission check, constantly.

Is this really needed?

**Comment by CodeCrafter47** [comment]
There's already an issue on the topic: #293

**Comment by andrewkm** [comment]
I'll take the discussion there then :) Thank you.
