### ISSUE TITLE
Help with prefixes

### ISSUE THREAD

**Issue by Games4k** [CodeCrafter47/BungeeTabListPlus#365]
Hello. I read Wiki, but I think I still didn't find what I want.
Can anyone help me about adding custom prefixes to the tablist. For example, prefix for owner is OWNER, but I want to display only [O] in my tablist. Is it possible to do it?

Thank you very much!

**Comment by CodeCrafter47** [comment]
That's actually on of the features that could be documented better. 

The following post on Spigot forums explains it quite well: https://www.spigotmc.org/threads/bungeetablistplus.10325/page-130#post-2318937.

**Comment by Games4k** [comment]
Thank you very much :D
