### ISSUE TITLE
Need help with Custom placeholder with PlaceholderAPI - Solved

### ISSUE THREAD

**Issue by weronicamc** [CodeCrafter47/BungeeTabListPlus#366]
Hello, I need help with it. It s not working http://prntscr.com/k0cdfw.

customPlaceholders:
  player_nickname:
    !conditional
    condition: ${player %nicky_nickname%} != ""
    true: ${player %nicky_nickname%}
    false: ${player name}

  playerComponent: {text: "${player_nickname}", icon: "${player skin}", ping: "${player ping}"}

**Comment by CodeCrafter47** [comment]
The correct way to use it is `${player nicky_nickname}`. Without the `%` sign.

**Comment by weronicamc** [comment]
@CodeCrafter47 Thank you for answer, but still it doesnt work

customPlaceholders:
  player_nickname:
    !conditional
    condition: ${player nicky_nickname} != ""
    true: ${player nicky_nickname}
    false: ${player display_name}
  viewer_colored_ping0:
    !conditional
    condition: "${viewer ping} < 50"
    true: "&a${viewer ping}"
    false: "&e${viewer ping}"
  viewer_colored_ping:
    !conditional
    condition: "${viewer ping} < 150"
    true: ${viewer_colored_ping0}
    false: "&d${viewer ping}"

defaultIcon: colors/dark_gray.png
defaultPing: 1000
size: 80
playerSets:
  global:
    filter: "true"
components:
- {text: "&dServer: &6${viewer server}", icon: "default/server.png", ping: 0}
- {text: "&dRank: &6${viewer vault_primary_group}", icon: "default/rank.png", ping: 0}
# Show ping in different colors depending on how good/ bad it is
- {text: "&dPing: ${viewer_colored_ping}ms", icon: "default/ping.png", ping: 0}
- {text: "&cMC-Version: &6${viewer client_version}", icon: "colors/gold.png", ping: 0}
- !players_by_server
  playerSet: global
  serverHeader:
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "", icon: "colors/dark_gray.png", ping: 1000}
  - {text: "&e&n${server}&f&o (${server_player_count}):", icon: "colors/yellow.png", ping: 0}
  showServers: NON_EMPTY
  playerComponent: {text: "${player player_nickname}", icon: "${player skin}", ping: "${player ping}"}
  morePlayersComponent: {text: "&7... and &e${other_count} &7others", icon: "colors/gray.png", ping: 0}

**Comment by CodeCrafter47** [comment]
To use the custom placeholder you created use `${player_nickname}` not `${player player_nickname}`.

**Comment by weronicamc** [comment]
@CodeCrafter47 It s finally working :) Thank you very much for your help.
