### ISSUE TITLE
No empty slots and per server tablist

### ISSUE THREAD

**Issue by brainscript** [CodeCrafter47/BungeeTabListPlus#37]
@CodeCrafter47 I just use your plugin to display **the header**, **the footer** and to show the **BungeePerms prefixes**. But I don't want to display information in the slots and I don't want to have a global tablist.

*1. So, how can I can I __only__ list the players on the __current server__?*
*2. Could you please add a config to __disable the empty slots__?*

**Comment by CodeCrafter47** [comment]
1. 
```
groupPlayers: NONE
tabList:
- '{fillplayers:currentserver}'
```
2. The plugin cannot do that. It is not designed to do that. And what you want is not as easy as adding a config option.


You may find that there are other plugins, which can already accomplish what you want to do.

**Comment by brainscript** [comment]
I know but you could add it as a feature.

**Comment by brainscript** [comment]
I'll maybe find another plugin, but then it isn't be compatible with **BungeePerms** and I need to install it on every Bukkit server and configure it there.

**Comment by CodeCrafter47** [comment]
I could, but the difficult thing is, that it will only work well as long as the tablist only contains players. As soon as someone would tell the plugin to remove empty slots but adds some custom content to the tablist or even removes players that would cause a lot of issues.

Worst case would be someone removing the players from the tablist and instead showing a few lines of custom text. That would screw up the tablist as soon as more players are online than there are slots in the tablist (even thought no players a shown).

Assuming the above miss-configuration generates a lot of warnings in the console so that the admin may correct the config, there would only be some minor issues left like how the plugin handles [ALIGN=LEFT] in a tablist that changes its size or how 1.7 clients are handled.

Probably I can add a disableEmptySlots or enableAutoResize option later today to the dev-build so we can test whether it works ok or creates too many issues.

**Comment by brainscript** [comment]
Please do that! :+1:  You can add a comment above like `Only use this without info slots! No warranty!`, because when I only have ...

`groupPlayers: NONE`
`tabList:`
`- '{fillplayers:currentserver}'`

... it should work, I think.

**Comment by brainscript** [comment]
@CodeCrafter47 Is it already in the newest DevBuild 1.2?

**Comment by CodeCrafter47** [comment]
dev-builds are generated automatically whenever I push a change to github. So yes it's in the latest dev-build (build 46 on jenkins).

**Comment by brainscript** [comment]
Jaayyy! :smile_cat: It works! When bugs appear, I'll report them to you, but currently **it works** fine! *Thanks!* :cake:

**Comment by brainscript** [comment]
@CodeCrafter47 There is a strange player called `__?tab` (_=Space) in the tablist. He is strange ... on every server. Strange ....

**Comment by CodeCrafter47** [comment]
the ?tab players are fakeplayers created by the plugin to add slots for custom content.  If you see the ?tab then the plugin somehow forgot to update the name of the fakeplayer. Not sure why this happens. I'll investigate tomorrow.

**Comment by CodeCrafter47** [comment]
Somehow I haven't been successful in recreating the error today.

**Comment by brainscript** [comment]
It only happens sometimes, i'll send you a screenshot and the console log when it happens again.

**Comment by brainscript** [comment]
Error message:
`14:47:14 [WARNING] [BungeeTabListPlus] Could not update tablist for brainscript.`
 `Please increase tab_size`

**Comment by CodeCrafter47** [comment]
You need to increase the value of tab_size. Even if autoShrinkTabList is on that still represents the upper limit for the tablist size. And if it happens that there are more players on the backing server than the tablist can hold the plugin just doesn't update the tablist anymore.
Setting tab_size to 80 will prevent that error.

**Comment by brainscript** [comment]
Currently are only **TWO** players online ....

**Comment by CodeCrafter47** [comment]
Interesting.

Figured out that if autoShrinkTabList is enabled this can also happen under other conditions like
 * You use citizens or a similar plugin
 * There are players on the backing spigot server which are NOT connected through bungeecord
 * A player is hidden

**Comment by brainscript** [comment]
1. I'm not using Citizens.
2. No, I'm using OnlyProxyJoin.
3. No.

*This happens when `__?tab` is "online".*

**Comment by CodeCrafter47** [comment]
Well that issue should be fixed now. At times where you previously saw the ?tab player you will now see an empty slot in the tablist. Its skin shows you which player caused the issue.

**Comment by brainscript** [comment]
It looks amazing ...
![2015-07-29_13 19 31](https://cloud.githubusercontent.com/assets/8706734/8956309/c7652812-35f4-11e5-9eee-564073e7649b.png)

**Comment by CodeCrafter47** [comment]
config?
does this happen always or under only sometimes?

**Comment by brainscript** [comment]
Always. It's no longer auto shrinking the tablist.

**Comment by CodeCrafter47** [comment]
config?

**Comment by brainscript** [comment]
`tablistUpdateIntervall: 1.0`
`updateOnPlayerJoinLeave: true`
`updateOnServerChange: true`
`useScoreboardToBypass16CharLimit: true`
`charLimit: -1`
`permissionSource: BUNGEEPERMS`
`sendPing: true`
`showPlayersInGamemode3: true`
`checkForUpdates: true`
`notifyAdminsIfUpdateAvailable: true`
`serverAlias:`
`  server3: PvP`
`  server2: Creative`
`  server1: Spawn`
`worldAlias:`
`  server3:world: PvP`
`  server1:world1: Spawn`
`  server2:world: Creative`
`serverPrefixes:`
`  SkyBlock: '&8(&dS&8) '`
`  Minigames: '&8(&bM&8)'`
`prefixes:`
`  Player: '&eSpieler &8| &e'`
`  Owner: '&aOwner &8| &a'`
`pingDelay: -1`
`online:`
`  text: '&2 ON'`
`offline:`
`  text: '&c OFF'`
`fakePlayers: []`
`excludeServers:`
`- server2`
`- server7`
`autoExcludeServers: false`
`autoShrinkTabList: true`

**Comment by brainscript** [comment]
@CodeCrafter47 ?

**Comment by CodeCrafter47** [comment]
I'll look at it.

**Comment by brainscript** [comment]
When I'm alone on the server, there are no empty slots. But when a players joins, the empty slots appear. :tophat:

**Comment by CodeCrafter47** [comment]
can you review whether the latest dev-build (74 or later) changed that behaviour.

**Comment by brainscript** [comment]
I would like to, but I'm currently on vacation away from home. :smile_cat: I'll be back next Tuesday. :hourglass: Then I'm going to test it out. :smile:

**Comment by brainscript** [comment]
@CodeCrafter47 I tested it but first I forgot to answer. Yes, it works but sometimes this happens:
![2015-09-05_20 38 30](https://cloud.githubusercontent.com/assets/8706734/9715849/b20c8282-5564-11e5-971e-1ec400b602a2.png)
**zombienudel** is Builder! Not Owner!
```
playerLines:
- '{prefix} &8| {prefixColor}{rawname}'
```

**Comment by CodeCrafter47** [comment]
I don't know why that happens. Shouldn't happen at all.

**Comment by brainscript** [comment]
@CodeCrafter47
![2015-09-15_18 20 52](https://cloud.githubusercontent.com/assets/8706734/9883650/9c8e18f8-5bdb-11e5-81a6-08593522426e.png)
That happens too, maybe it's also related to BungeePerms.

**Comment by brainscript** [comment]
@CodeCrafter47 With the [newest release update](https://www.spigotmc.org/resources/bungeetablistplus.313/update?update=45296) from SpigotMC the `autoShrinkTabList` value doesn't work.
![2015-09-16_17 59 02](https://cloud.githubusercontent.com/assets/8706734/9910303/c489f7a2-5c9c-11e5-9bec-ac005942097d.png)

**Comment by CodeCrafter47** [comment]
It is still working, just the autoShrinkTabList configuration option has been moved from config.yml to the tablist configuration file. That way it is selectable separately per tab list.

**Comment by brainscript** [comment]
@CodeCrafter47 I didn't see that. :smile:
