### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by madtomic** [CodeCrafter47/BungeeTabListPlus#377]
https://www.spigotmc.org/resources/placeholderapi.6245/

Can you please add support for this?

**Comment by madtomic** [comment]
I am interested in this {luckperms_group_expiry_time_*}

**Comment by CodeCrafter47** [comment]
<https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlaceholderAPI>.
