### ISSUE TITLE
NPC's are displayed in the TabList

### ISSUE THREAD

**Issue by mickdom** [CodeCrafter47/BungeeTabListPlus#381]
NPC's created with Citizens appear in the tablist!

Plugin: Citizens
Command: /npc create [Playername]

Can I prevent the NPC's from being displayed?

Thanks for your help!

**Comment by CodeCrafter47** [comment]
Citizens has a config option for it.

They will still appear for a fraction of a second when walking near then, but they shouldn't stay on the tab list for a longer period of time.

**Comment by mickdom** [comment]
Hi CodeCrafter47,

Ok! Thank you for your answer!
