### ISSUE TITLE
custom placeholders

### ISSUE THREAD

**Issue by animekkk** [CodeCrafter47/BungeeTabListPlus#383]
hello, I've a problem with custom placeholder.
This is my code:
Main: https://pastebin.com/piqd6h9m
Test: https://pastebin.com/gUvnqQ9p
In a deafult.yml i have this: - {text: "&cTEST: &7${player test_var}", icon: "colors/dark_gray.png", ping: 0},
but it looks like this: https://imgur.com/a/7PKyHIR
anyone help?

**Comment by CodeCrafter47** [comment]
Try using `${viewer test_var}` instead.

**Comment by animekkk** [comment]
thanks, it works. to close
