### ISSUE TITLE
Get playerhead icon with skinrestorer (offline server)

### ISSUE THREAD

**Issue by phuchptty** [CodeCrafter47/BungeeTabListPlus#386]
I have an idea that connect bungee tablist to skinrestorer. Skinrestorer will save data in json format that have base64 encode. In json text will have a link to skin Mojang's skin server.
So we can use that for offline server. Will it be possible ?

Base64: eyJ0aW1lc3RhbXAiOjE1MzM2MjE3NjcwNzEsInByb2ZpbGVJZCI6ImE5MGI4MmIwNzE4NTQ0ZjU5YmE1MTZkMGY2Nzk2NDkwIiwicHJvZmlsZU5hbWUiOiJJbUZhdFRCSCIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzI2YmU2YmI2OGNkMDNlMTYxNjY2MDdiYzRjNmMxNjM1ZmExYjQxNzE0MzgyNzVkOWQ4N2YwNDVlNThkZmNmNiJ9fX0=

Decode: {\"timestamp\":1533621767071,\"profileId\":\"a90b82b0718544f59ba516d0f6796490\",\"profileName\":\"ImFatTBH\",\"signatureRequired\":true,\"textures\":{\"SKIN\":{\"url\":\"http://textures.minecraft.net/texture/326be6bb68cd03e16166607bc4c6c1635fa1b4171438275d9d87f045e58dfcf6\"}}}

thanks in advance and sorry for bad english !

**Comment by CodeCrafter47** [comment]
It won't work. The client will not display the icon if it is connected to a offline mode server, i.e. not using an encrypted connection.
