### ISSUE TITLE
Essentials AFK (Issue)

### ISSUE THREAD

**Issue by MiraculousLadyBug** [CodeCrafter47/BungeeTabListPlus#387]
![image](https://user-images.githubusercontent.com/40721933/44759347-4709b100-aaff-11e8-8edd-6b203f99e4dc.png)

Whenever I go AFK for my essentials, it appears as this.
![image](https://user-images.githubusercontent.com/40721933/44759378-69033380-aaff-11e8-967d-12355c6a550d.png)
![image](https://user-images.githubusercontent.com/40721933/44759392-77514f80-aaff-11e8-93bd-48a7581db6a9.png)

**Comment by MiraculousLadyBug** [comment]
It's just broken it appears as my {name}and then {true or false}

**Comment by CodeCrafter47** [comment]
In `playerComponent` you need to use `${afk_tag}` instead of `${player essentials_afk}`.

**Comment by Thomas-Lecuppre** [comment]
Hi, this problem steel here in 2021.
I do /essentials:afk but I don't appears in AFK list.
![image](https://user-images.githubusercontent.com/71729025/113922170-407b6400-97e7-11eb-8a36-028003f19d96.png)

My default.yml : 

`playerSets:
  lobby: ${player server} == "lobby"
  survival: ${player server} == "survie"
  afk: ${player essentials_afk} = true

type: FIXED_SIZE
size: 80

defaultIcon: "colors/dark_gray.png"
defaultPing: 1000

components:
- !table
  columns:
    0:
    - {text: "&6Lobby", icon: "colors/gold.png", ping: 0}
    - !players
      playerSet: lobby
      playerComponent: "${player luckpermsbungee_prefix}${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    1-2:
    - {text: "&2Survie", icon: "colors/dark_green.png", ping: 0}
    - {text: "", icon: "colors/dark_green.png", ping: 1000}
    - !players
      playerSet: survival
      playerComponent: "${player luckpermsbungee_prefix}${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}
    3:
    - {text: "&7AFK", icon: "colors/dark_gray.png", ping: 0}
    - !players
      playerSet: afk
      playerComponent: "${player luckpermsbungee_prefix}${player name}"
      morePlayersComponent: {text: "... and ${other_count} others", icon: "default/players.png", ping: 0}`

**Comment by CodeCrafter47** [comment]
You need to install `BungeeTabListPlus_BukkitBridge` on your Bukkit/ Spigot server.

**Comment by Thomas-Lecuppre** [comment]
My bad.

You do a very nice plugin !

Just a little think :)
![image](https://user-images.githubusercontent.com/71729025/113923757-33f80b00-97e9-11eb-95d8-8a91a9b883da.png)
I think it's ${player essentials_afk} on right at https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders

**Comment by CodeCrafter47** [comment]
Thanks for pointing that out.
