### ISSUE TITLE
Cannot use placeholders form Sponge Papi that without ‘_’

### ISSUE THREAD

**Issue by ginyai** [CodeCrafter47/BungeeTabListPlus#389]
For example 
`{viewer player_name}`  works well, but  `{viewer player}` does not work.

Probably due to the code [here](https://github.com/CodeCrafter47/BungeeTabListPlus/blob/c6bb7ea2fb7ddb2794a36a1a68e58b7ee4388c1e/bungee/src/main/java/codecrafter47/bungeetablistplus/bridge/PlaceholderAPIHook.java#L66) 
does not remove the suffix '%'.

**Comment by CodeCrafter47** [comment]
You can use the latest dev-build to get the fix immediately: <https://ci.codecrafter47.de/job/BungeeTabListPlus/>.
