### ISSUE TITLE
CPU usage maxes out, and proxy log gets spammed with config error.

### ISSUE THREAD

**Issue by SullyTheUnusual** [CodeCrafter47/BungeeTabListPlus#39]
The following error spams my proxy log when applying the most recent update (7/29/15).  I tried commenting out server aliases in the config (because I don't use them) to no avail.

04:19:08 [WARNING] [BungeeTabListPlus] Configuration Error: Server "server2" used in the alias map does not exist.
04:19:08 [WARNING] [BungeeTabListPlus] Configuration Error: Server "server1" used in the alias map does not exist.
04:19:08 [WARNING] [BungeeTabListPlus] Configuration Error: Server "server3" used in the alias map does not exist.

**Comment by CodeCrafter47** [comment]
You can use `serverAlias: {}` to create an empty alias map.

**Comment by SullyTheUnusual** [comment]
Good to know, I'll try that.

**Comment by CodeCrafter47** [comment]
Fixed with 677798f47164f88fc0ba969b638ee55162fb5a5b
