### ISSUE TITLE
BungeePerms + PEX error

### ISSUE THREAD

**Issue by hockeymikey** [CodeCrafter47/BungeeTabListPlus#4]
So I'm testing on a test server using BungeePerms for some Bungee only permissions and still using PEX for everything else on Spigot.  BungeePerms doesn't have the bukkit bridge, only they proxy plugin.  Whenever a player joins this is spammed every second:
http://pastebin.com/vdN3957n

I've tried setting the permissions source to BUKKIT with no luck.

**Comment by hockeymikey** [comment]
Yep you're right issue was fixed after I added myself to a group.  Will there be a fix so I don't have to add every user to a group?

**Comment by CodeCrafter47** [comment]
I fixed it with 56e0edcf5f32b0e3f107242619733b66836c4ba6

a dev-build is available at <http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/>
