### ISSUE TITLE
Issue with EXP display in tab.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#401]
It looks like there are certain scenarios when the exp displayed via tab using this plugins exp placeholder shows an incorrect value.

Discussion and bug report here:
https://ecocitycraft.com/forum/threads/tab-exp-and-xp-showing-different-numbers.180214/

Using 2.8.10 build 796
Running on 1.13.2

**Comment by CodeCrafter47** [comment]
I just did some research and my conclusion is that the `${viewer total_xp}` placeholder displays the total experience collected by the player. This value is displayed when a player dies.

There is no placeholder in BungeeTabListPlus that displays the value you're looking for. However PlaceholderAPI comes with four experience related placeholders, one of them might suit your needs.

**Comment by andrewkm** [comment]
@CodeCrafter47 this is what I use:
https://pastebin.com/raw/bywDbBGF

`- {text: "&cEXP: &6${viewer total_xp}", icon: "default/balance.png", ping: 0}`

It is working fine most of the time, but sometimes displays an incorrect amount.

**Comment by CodeCrafter47** [comment]
It should always match the number that would be displayed on the players death screen should he die in that moment. It's not supposed to be equal to the number you'd obtain by summing up the players levels.

**Comment by CodeCrafter47** [comment]
The `${viewer total_xp}` placeholder displays the number returned by the [`Player.getTotalExperience`](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/Player.html#getTotalExperience--) API call. If you search for it you can find some old discussion on the Bukkit forums saying that it sometimes returns an incorrect value. The gist of it is that this always matches the number displayed on the players death screen and there are no guarantees that this number relates to anything else.

The Essentails `/exp` command [calculates the number it displays using the player's level](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/craftbukkit/SetExpFix.java#L67). However I don't feel like copying their code or recreating the same calculations in BungeeTabListPlus.

I also checked the `%total_exp%` placeholder from PlaceholderAPI and it works the same way as BungeeTabListPlus's own placeholder.

**Comment by andrewkm** [comment]
@CodeCrafter47 

Our users have now found more exact reproduction steps for you:
https://ecocitycraft.com/forum/threads/tab-exp-and-xp-showing-different-numbers.180214/

> Okay so heres what I did step by step:
> 1. Lowered my level down as far as possible from 14 levels to 0 levels (3 points). (/xp experience shown http://prntscr.com/m8duo0) (Tab experience shown http://prntscr.com/m8dv7e)
> 2. Used 64 exp bottles to raise my level to 18 (/xp experience shown http://prntscr.com/m8dvmz) (Tab experience shown http://prntscr.com/m8dw3r)
> 3. Combined 2 pickaxes (diamond, one with Eff 2 Fort 1 Unbreaking 2) which cost me 10 levels and brought my exp from 18 to 8 levels http://prntscr.com/m8dwuk. (/xp experience shown http://prntscr.com/m8dx6v) (Tab experience shown http://prntscr.com/m8dxji)
> 4. Checked tab to see if the exp count matched with /xp (It didn't. Tab showed 636 points greater in difference to /xp.)
> 
> This was recreated on Minecraft Version: 1.13.2-Optifine_HD_U_E4 - Optifine
> 
> I believe that the tab is miscalculating or not calculating any exp taken when enchanting/combining tools as my tab exp always seems to show more than my /xp which means it is not removing any exp when performing enchants etc.
> 
> @andrewkm If you need anything else shown / added, I will be happy to do so :)
> 
> UPDATE: I have found whilst I have been gaining exp since today via killing mobs etc, the difference has been staying at 636 points. Not sure if this is helpful but may come in handy.
