### ISSUE TITLE
Spammed bungee console on BTLP 2.1.0

### ISSUE THREAD

**Issue by ziutekkk** [CodeCrafter47/BungeeTabListPlus#41]
My bungee console is spammed by this error. Please fix that, it makes log file oversized

"[WARNING] [BungeeTabListPlus] Server cr uses Scoreboard teams. This feature is not compatible with BungeeTabListPlus."

**Comment by ziutekkk** [comment]
I didnt set any teams, so I have no idea why it appears.

**Comment by CodeCrafter47** [comment]
Some plugins may use teams without you knowing it. Scoreboard plugins like FeatherBoard do, the AnimatedNames plugin (and similar plugins that change the name above the players head) also uses scoreboard teams.

**Comment by CodeCrafter47** [comment]
The plugin is now compatible with most Scoreboard plugins. This kind of error message will now only occur if you have a scoreboard team with players assigned to it which is not compatible with BungeeTabListPlus unless you set tab_size to 80. So I'm closing this now.
