### ISSUE TITLE
Question: Scroll through players?

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#412]
Instead of using the morePlayersComponent to just show how many more the tab list is missing, is it possible to actually have the tab column scroll through all players?

If so please direct me to a guide or link where I can read up on how to achieve this :)

**Comment by CodeCrafter47** [comment]
This is not possible.

**Comment by Devillion** [comment]
what is the morePlayersComponent? how do I get it

**Comment by CodeCrafter47** [comment]
The `morePlayersComponent` is some text that is displayed when there are more players on your server than fit the tab list.[ This wiki page ](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-7---Fixed-Size-Tablist---Adding-Players)has an image where it is used.
