### ISSUE TITLE
Remove permission checks on hiddenPlayers: INVISIBLE

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#416]
Remove permission checks on hiddenPlayers: INVISIBLE
It's impossible to debug permissions issues due to this plugin spamming:
https://i.imgur.com/0GBHrm2.png

Even when hiddenPlayers: INVISIBLE.

**Comment by CodeCrafter47** [comment]
There's an issue for this: #293. If it's just about debugging, you can remove BungeeTabListPlus while you debug permission issues in other plugins.

**Comment by andrewkm** [comment]
We can’t “just remove” a plugin when live debugging is needed in production.

**Comment by CodeCrafter47** [comment]
I see this is potentially different from the problem described in #293. If I understand this correctly, your debugging the permissions on the Bukkit/ Spigot server. BungeeTabListPlus does perform the query every one or two seconds for each player. Your picture shows it also queries the `prefix` and `primarygroup` attributes at the same rate. So I suppose you would need to get rid of those queries too?

**Comment by CodeCrafter47** [comment]
Would a command to temporarily disable the permission queries fix your problem?

**Comment by andrewkm** [comment]
It would be best if the checks didn’t go through at all if hiddenplayers is VISIBLE.

**Comment by CodeCrafter47** [comment]
As you can see from my answers on #293 this will eventually happen, but don't expect the unnecessary permission checks to be removed tomorrow or in the near future.

**Comment by andrewkm** [comment]
It’s been a year dude, why not just say you’re not gonna fix it.

**Comment by andrewkm** [comment]
@CodeCrafter47 ?

**Comment by CodeCrafter47** [comment]
The status of this issue remains unchanged.
