### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Raphy123** [CodeCrafter47/BungeeTabListPlus#42]
Hello,

Every 3-4 days, I have Memory leak with this plugin

**Comment by CodeCrafter47** [comment]
I don't think the plugin has memory leaks. But it uses a lot of memory. How much memory does your server have? How many players do you have?

**Comment by Raphy123** [comment]
Bungee was launch with 512M. I have up on 1G for the Bungee's memory. since that, I have not crashed but.. so that is normal ? I have 40 players connected.

**Comment by Xayanix** [comment]
I suggest you use 2GB RAM for bungee.

**Comment by CodeCrafter47** [comment]
I've fixed all the memory leaks I found in the plugin.
