### ISSUE TITLE
Feature Addition: Mcmmo Placeholders.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#423]
Feature Addition: mcMMO Placeholders.

https://www.spigotmc.org/resources/official-mcmmo-classic.2445/
https://www.spigotmc.org/resources/official-mcmmo-original-author-returns.64348/

Would be nice to display some mcMMO information with BTLP in the tab lists.
The current plugin scoreboards have quite a bit of information that could be used in BTLP:
https://i.imgur.com/Gnrl3HP.png

Perhaps @nossr50 can provide some info on what could be added.

**Comment by CodeCrafter47** [comment]
You can use the placeholders from PlaceholderAPI:
 * <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlaceholderAPI>
 * <https://www.spigotmc.org/wiki/placeholderapi-plugin-placeholders-page-1/#mcmmo>

**Comment by andrewkm** [comment]
Oh cool! Thanks :)
