### ISSUE TITLE
Players' heads switching randomly

### ISSUE THREAD

**Issue by Kikisito** [CodeCrafter47/BungeeTabListPlus#424]
Hello. I've been using BungeeTabListPlus for some days, and I saw a little bug. When somebody joins the server, the head of each player switches randomly its place in the tab. Here you can see it.

![Right one](https://i.imgur.com/qVjpdOW.png)
This is the tablist with the heads correctly placed.

![Wrong one](https://i.imgur.com/iyIx1R7.png)
This is the tablist when somebody joins or leaves the server, and the heads are placed incorrectly.

What's causing this?

**Comment by CodeCrafter47** [comment]
It's a bug in the plugin. It rarely happens. It can sometimes be triggered by the use of Citizens or vanish plugins.

**Comment by Kikisito** [comment]
I don't use any of these plugins.

**Comment by CodeCrafter47** [comment]
It can also happen without these plugins. I was just saying it might happen more frequently if you use those.

**Comment by Kikisito** [comment]
There isn't any fix for this? It happens always.

**Comment by CodeCrafter47** [comment]
I'll fix this eventually, but it won't be soon.

**Comment by CodeCrafter47** [comment]
This bug has been fixed. It should no longer occur using version 3.x.x of the plugin.
