### ISSUE TITLE
canSeeFriendlyInvisibiles bugging

### ISSUE THREAD

**Issue by iFlyinqMC** [CodeCrafter47/BungeeTabListPlus#428]
When a player is in your team and the option canSeeFriendlyInvisibles is on true you have to set the tab mode to FIXED_SIZE to make this work, when you put it to Dynamic its not working and than you dan't see the 'ghost', i hope you can fix this asap.

**Comment by CodeCrafter47** [comment]
For the plugin to work it needs to put each player into a separate team. This is what breaks the `canSeeFriendlyInvisibles` option. The only exception to this rule is when the tab list uses all 80 slots. This can't be fixed.
