### ISSUE TITLE
Hidden Servers

### ISSUE THREAD

**Issue by Cobi** [CodeCrafter47/BungeeTabListPlus#43]
It would be nice to have a list of servers which should not be displayed on the tab list.  So if someone is on a test server (or private for whatever other reason), the server will not appear in the tab list.  Preferably this could be done on a per tablist setting, but globally would be OK too.

**Comment by DreamPhreak** [comment]
That already exists, in config.yml:

    excludeServers:
    - private

**Comment by CodeCrafter47** [comment]
That is for preventing the tablist to be shown to players on that server not to prevent a server from appearing on the tablist.
