### ISSUE TITLE
Scoreboard/objective as option for 'playerOrder'

### ISSUE THREAD

**Issue by EvModder** [CodeCrafter47/BungeeTabListPlus#438]
To create an objective "levels" and display it in TAB:
/scoreboard objectives add levels level "Levels"
/scoreboard objectives setdisplay list level

It would be awesome if BungeeTabListPlus could have an option to sort players (playerOrder setting from config) based on a scoreboard value.
My current workaround is to create fake teams named to whatever the player's level is and then setting playerOrder=teams, but it's definitely too hacky.

perhaps named something like "playerOrder=objective"

**Comment by CodeCrafter47** [comment]
I plan on extending the available options for `playerOrder` in the future. The plan is to allow any placeholder to be used to order players.

**Comment by EvModder** [comment]
Sweet.
I was going to send a pull request, but got a bit intimidated by the codebase :)

**Comment by CodeCrafter47** [comment]
You can still do a pull request if you like. The changes I plan on making might take some time.

**Comment by CodeCrafter47** [comment]
It is now possible to use any placeholder you like for sorting players: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder>.
