### ISSUE TITLE
Skins in tab are acting weird

### ISSUE THREAD

**Issue by Sikatsu** [CodeCrafter47/BungeeTabListPlus#445]
Sometimes the skins in tab are switched with another player.

I don't know why, but my skin shows as a black block and Bluroisa shows my skin.

http://prntscr.com/or78eq

This happens with other players too. Anything I or you can do?

**Comment by CodeCrafter47** [comment]
Sorry for the late response. This is a bug. It happens mostly when using the `DYNAMIC_SIZE` mode.

**Comment by Sikatsu** [comment]
I assume the bug will be fixed? :P

**Comment by CodeCrafter47** [comment]
Yes, it will be fixed, but do not expect a fix in the near future.

**Comment by Deuphic** [comment]
I'm having the same issue. Also using `DYNAMIC_SIZE`. Would be nice with a fix in the not-far-future.

Thanks.

**Comment by CodeCrafter47** [comment]
I put this issue on the Far Future milestone. I cannot say when that will be, but definitely before the issues on the Very Far Future milestone are fixed.

**Comment by Sikatsu** [comment]
Is it still far future, months later? :/

**Comment by CodeCrafter47** [comment]
Yes, that is why it is called far future.

**Comment by CodeCrafter47** [comment]
Can you check if the [latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/) fixes the issue?

**Comment by CodeCrafter47** [comment]
This issue should be fixed with the latest update.
