### ISSUE TITLE
Show different tabs to different groups?

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#447]
I'd like to show certain tabs to certain users.
For example:
showTo: '${viewer server} == "lobby"'
Here I would like to add another variable so its lobby AND a luckperms group.

1. I'm not sure how to do this, is it possible to use more than one variable in the showTo field such as "${viewer luckperms_primary_group}"?

2. I'm looking to use a luckperms group that is NOT primary. Simply a group that user is part of. Is this in any way possible? ${viewer luckperms_group} for example, would that be a thing?

**Comment by CodeCrafter47** [comment]
> I'm not sure how to do this, is it possible to use more than one variable in the showTo field such as "${viewer luckperms_primary_group}"?

Yes that is possible: 
```yaml
showTo: ${viewer server} == "lobby" and ${viewer luckperms_primary_group} == "admin"
```

> I'm looking to use a luckperms group that is NOT primary. Simply a group that user is part of. Is this in any way possible? ${viewer luckperms_group} for example, would that be a thing?

This is not possible.

**Comment by andrewkm** [comment]
Thanks!
