### ISSUE TITLE
Missing placeholders ${player|viewer skin} in wiki

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/BungeeTabListPlus#454]
The Placeholder page of the wiki is lacking the `${player skin}` and `${viewer skin}` respectively.
Those should be added to the page.

**Comment by CodeCrafter47** [comment]
I have added some info about the `${viewer skin}` placeholder at the bottom of the page. I think it is not necessary to mention the `${player skin}` placeholder as there is no need to ever use it.

**Comment by Andre601** [comment]
okay. Didn't see it there because I thought it would be in the default viewer/player placeholder list.
