### ISSUE TITLE
This may be an issue or it may be me doing something wrong

### ISSUE THREAD

**Issue by stw222** [CodeCrafter47/BungeeTabListPlus#455]
For some reason, people keep being placed in our tablist in the wrong spots. like when im on the pixelmon server it may place me in the bottom right or top left corner, no-where near where the pixelmon server players should be listed. This happens on all of the servers except sometimes doesnt happen on our Hub server
server list: Waterfall, Survival, Hub, Creative, Pixelmon, All the Mods 3, Stoneblock 2.

this started happening after we added AtM3 and SB 2

images:
[https://i.imgur.com/mmbg4BR.png?1](https://i.imgur.com/mmbg4BR.png?1)

configs:
[default.yml](https://pastebin.com/q9Twa7ve)
[spigot servers.yml](https://pastebin.com/KZ68p9d1)
[sponge servers.yml](https://pastebin.com/VPJgJVeS)
[config.yml](https://pastebin.com/v6NUv10R)

**Comment by CodeCrafter47** [comment]
This looks like a bug in the plugin. Considering it involves Waterfall, I will not investigate it.

**Comment by stw222** [comment]
would you take a look at it if i had the same bug using only bungee?

**Comment by stw222** [comment]
it seems that it is probably waterfall that is causing the problem. kinda sucks that i cant go back to bungeecord since we needed waterfall for our modded servers

**Comment by stw222** [comment]
the thing is, it works fine on our hub server but people are misplaced on survival and creative, all of which are paper servers but people are also misplaced on our sponge servers

**Comment by gp-Airee** [comment]
Bungee is unusable in performance compared to Waterfall. Don't be obtuse!

**Comment by gp-Airee** [comment]
It took a while but I see this as a win
