### ISSUE TITLE
hello i need help

### ISSUE THREAD

**Issue by guardark** [CodeCrafter47/BungeeTabListPlus#464]
hello I have installed bungeetablistplus as indicated in the description, but is it normal that it displays the heads of players in the list?
![2019-11-21_10 34 10](https://user-images.githubusercontent.com/52101698/69325487-85324980-0c4a-11ea-90e8-fa7ccaec946a.png)

**Comment by CodeCrafter47** [comment]
Icons don't appear on offline mode servers.

**Comment by guardark** [comment]
the server is online :/

**Comment by CodeCrafter47** [comment]
The heads only appear under the following two conditions: First you need Minecraft 1.8 or newer and second you need to set `online_mode: true` in BungeeCord's config.yml. Since you appear to be using a recent version of Minecraft, not the second condition is where your problem lies.
