### ISSUE TITLE
Add support for custom variables

### ISSUE THREAD

**Issue by danbovey** [CodeCrafter47/BungeeTabListPlus#47]
The amount of variables you have [here](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/variables) is impressive, but it would be even more amazing if you supported variables that could be injected by another plugin directly, instead of having to add support for every and all plugins (It makes sense to have Factions, Clan, PlayerPoints etc. in core plugin, but as a developer & server owner I'd love to be able to add my own server's points plugin into my tablist).

Steps a developer should take to register a variable

1. Write a class that implements a new `Variable` class on the Bukkit bridge side (as there isn't any Variable functionality on Bukkit) allowing the plugin to pass through it's variable string.
2. Register the Variable with the Bukkit bridge (no idea how this would work).
3. Use `{customVariable}` in the tabLists config

**Comment by CodeCrafter47** [comment]
Has been added.
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Developers
