### ISSUE TITLE
Update LuckPerms dependency

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/BungeeTabListPlus#470]
The API of LuckPerms has been updated to v5 which brought major breaking changes.
For once was the path changed from `me.lucko.luckperms` to `net.luckperms.api`.
Next change was `LuckPermsApi` to just `LuckPerms`

I don't know if there would be a proper solution to keeping support for the v4 API of LP, but I just wanted to inform you about the changes.

**Comment by CodeCrafter47** [comment]
Hi,

Thanks for letting me know about this.

The latest dev-build of BungeeTabListPlus now supports v5 of the LuckPerms API as well as v4.
