### ISSUE TITLE
Tab list moves down 1 line

### ISSUE THREAD

**Issue by HHServers** [CodeCrafter47/BungeeTabListPlus#478]
Tab list appears normal when connecting directly to server normal way (enter IP in direct connect/save server) but when connecting from the hub using /server servername the tab list appears incorrectly with current server and players bunched up at top left as seen [HERE](https://i.hhservers.co.uk/uploads/5dfb1c40d108c0.41724771.png)

When it should look as seen [HERE](https://i.hhservers.co.uk/uploads/5dfb1c87a65405.42072751.png)

any help would be appreciated, i'm pretty much using the default config aside from a few colour changes

**Comment by HHServers** [comment]
I believe the issue is "disable_entity_metadata_rewrite" being set to true in waterfall.yml - I did this to use a protocol support plugin for newer/older versions of MC to be able to connect. For anyone running in to same issue

**Comment by CodeCrafter47** [comment]
I recommend against using Waterfall. If you want to support different Minecraft versions, one possible option that does not interfere with this plugin is to use ViaVersion, install it on all your Spigot servers but not on BungeeCord.

**Comment by huangsijun17** [comment]
> I recommend against using Waterfall. If you want to support different Minecraft versions, one possible option that does not interfere with this plugin is to use ViaVersion, install it on all your Spigot servers but not on BungeeCord.

No Waterfall useing or set "disable_entity_metadata_rewrite" to false, Some of my servers will be unconnected from time to time.

[https://github.com/PaperMC/Waterfall/issues/428](https://github.com/PaperMC/Waterfall/issues/428)

**Comment by electronicboy** [comment]
Having health issues, so not really been able to look into this, that option was used to hack a early protocol release together where that option was needed to get around some metadata changes and avoid having to deal with them, but the option is primarily used for dealing with mod incompatibilities; if you have any insight into what is going on here vs "waterfall bad", that would help with tryna solve this issue on our end with such setups

**Comment by CodeCrafter47** [comment]
BungeeTabListPlus modifies the `PlayerListItem` and `Team` packets. From the images it looks like something is wrong with the `Team` packets.

**Comment by SerendipityMC** [comment]
@electronicboy, @CodeCrafter47: If it helps, I can confirm. When [this line](https://github.com/SpigotMC/BungeeCord/blob/c2cc33c6d74ceddaf55cb8960ac305920cc41e90/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L242) isn't run (ie: disable_entity_metadata_rewrite) this issue occurs. Though I'm unsure why this specifically results in the tab list order being broken.

**Comment by CodeCrafter47** [comment]
That's weird. When using BungeeTabListPlus the copy of the scoreboard maintained by BungeeCord should not contain any teams. Thus that line wouldn't be executed anyway.

**Comment by SerendipityMC** [comment]
Just tested with [this line](https://github.com/SpigotMC/BungeeCord/blob/c2cc33c6d74ceddaf55cb8960ac305920cc41e90/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L240) specifically, with the following results when using a barebones setup with "disable_entity_metadata_rewrite" set to true:

[Before](https://i.imgur.com/hILbjyF.mp4) --> [Changes](https://i.imgur.com/ILDLIYd.mp4) --> [After](https://i.imgur.com/6u52KKe.mp4)

**Comment by xANoyU** [comment]
> 刚刚专门[对此行](https://github.com/SpigotMC/BungeeCord/blob/c2cc33c6d74ceddaf55cb8960ac305920cc41e90/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L240)进行了测试，使用“ disable_entity_metadata_rewrite”设置为true的准系统设置时具有以下结果：
> 
> [之前](https://i.imgur.com/hILbjyF.mp4) -> [更改](https://i.imgur.com/ILDLIYd.mp4) -> [之后](https://i.imgur.com/6u52KKe.mp4)
> 
> 由于我不熟悉Bungee的代码，因此不太确定该怎么做，但希望这会有所帮助。

Can you upload your Waterfall to me? I really need it!

**Comment by SerendipityMC** [comment]
@xANoyU: This is just attempting to narrow down the cause of the issue, and is not a fix yet.

**Comment by xANoyU** [comment]
> @xANoyU: This is just attempting to narrow down the cause of the issue, and is not a fix yet.

This appeared not to work,the tablist still messed up
