### ISSUE TITLE
Unable to use a tab_size greater than 80

### ISSUE THREAD

**Issue by aetaric** [CodeCrafter47/BungeeTabListPlus#48]
I currently have the tab_size set to 160 and it looks like your code is basically forcing the tab_size back down to 80 if the setting is set to a higher number. Is it possible for you to allow users of this plugin to set a number higher than 80?

**Comment by CodeCrafter47** [comment]
The minecraft client (1.8+) will not show more than 80 slots in the tablist. There is nothing a plugin can do to change that.
If you connect with an older minecraft client (1.7.10) then the plugin will accept a higher tab_size.
