### ISSUE TITLE
vault_primary_group_weight decs broken.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#486]
Previous layout: https://pastebin.com/aqSmjs5P
New layout: https://pastebin.com/nhTzCUzg
Still getting errors: https://pastebin.com/wHCKj1uc

TL;DR previously:
`      playerOrder: "vaultGroupInfoReversed"`
Currently migrated as per errors:
`      playerOrder: "vault_primary_group_weight decs"`
Broken.

**Comment by andrewkm** [comment]
Derp, ignore the error, clearly I have to rewrite my configs.
Anyways, I don't see that new visible_to_admins option anywhere that you mentioned in another ticket.

**Comment by andrewkm** [comment]
Nope still not working.
Example new config: https://pastebin.com/nhTzCUzg
Error: https://pastebin.com/wHCKj1uc

**Comment by CodeCrafter47** [comment]
There is a typo in the error message. It must be `desc` not `decs`. It is short for _descending_. Apologies for that.
