### ISSUE TITLE
VISIBLE_TO_ADMINS new option not showing?

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#487]
Tried generating a fresh config.
I do not see the new VISIBLE_TO_ADMINS option anywhere?

**Comment by CodeCrafter47** [comment]
You can just add the following line to the config:
```yaml
hiddenPlayers: VISIBLE_TO_ADMINS
```
I should probably add it to the default config, so it is easier to find. Information on how it works is available on the following wiki page: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Hidden-Players>. You can still configure the visibility of hidden players per player set the way it used to be done before the update.
