### ISSUE TITLE
Wiki: Smaller typos

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/BungeeTabListPlus#488]
On the [PlayerOrder](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/PlayerOrder) wiki page did I found some minor typos and some text that might be changed.

First of all does it in the table say the following about `vault_prefix`
> Sorts players by their prefix, alphabetically. You can use this is setting up weights is too complicated for you.

I think the first "is" should actually be an if?
In addition would I think that it was a good idea to also mention that this option requires you to have the Bridge plugin on the spigot-servers to retrieve the information of Vault in the first place.

The last option `server viewer-first` says the following:
> players which are in the same world as the player who sees the tablist appear at the top

World or server? I think you meant server, right?

**Comment by CodeCrafter47** [comment]
Thanks for noticing. I have fixed these.
