### ISSUE TITLE
Not sure if it's a bug Help

### ISSUE THREAD

**Issue by Neverlookbackgrg** [CodeCrafter47/BungeeTabListPlus#49]
So i am using your awesome plugin for my server.And i am trying to take the prefix from my groupmanager i tried everything that has to do with perms and player line and i am using all the files from the bungeetablistplus is it possible to give some info or help on the config how to set it up so i will be able to use prefix from group manager?Thank you.

**Comment by CodeCrafter47** [comment]
You need to install BungeeTabListPlus_BukkitBridge.jar and Vault on all your bukkit spigot servers. Then apply the {prefix} variable somewhere in the config. Also have a look at https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/coloredplayernames.

**Comment by Neverlookbackgrg** [comment]
Thank you so much for your support i already have all of them install i will check it right now.

**Comment by Neverlookbackgrg** [comment]
Well i got the bukkitbridge installed in all of my server and this is my tablist yml.
# 
# This the default TabList
# It is shown to all users which haven't got another TabList
# 
# Create a copy of this File, name it like you wish
# and change the showTo and some other options
# to create another TabList only shown to some users.
# By doing this you can for example create
# a special TabList for VIPs / Admins or
# create a tabList only shown o one server
# You can find more information on the wiki https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
# 

# Defines to which players this tabList applies
# No effect in the default tabList
# possible values:
# 'Player:<Name>' for specific Player
# 'Players:<player1>,<player2>' for multiple Players
# 'Server:<Server>' for all Players on that Server
# 'Servers:<server1>,<server2>' for all Players which are on These Servers
# 'group:<group>' for all players within that permission group
# 'groups:<group1>,<group2>' same with multiple groups
# '1.7' for all players with client version 1.7 or below
# '1.8' for all players with client version 1.8 or above
# 'all' for all players
showTo: all
# This text will be shown above the tablist
header: '&cWelcome &6{player} &cto &4Never&6Craft'
# This text will be shown below the tablist
footer: '&cplay.&4Never&6Craft.&ceu'
# whether to shown header/footer or not. You should set this to false if you wan to use a bukkit/spigot side plugin for that.
shownFooterHeader: true
# The skin shown for non-players
# leave empty for default skins
defaultSkin: MHF_Question
# ping value tu use for non-player slots, 
# used if no other value is specified using [PING=?]
defaultPing: 0
# if true player skin is shown beneath name, otherwise default skin
showCorrectPlayerSkins: true
# how Players should be grouped
# You can use 'SERVER' or 'NONE'
groupPlayers: SERVER
# Whether to Show Groups with no Players
# not effective if groupPlayers=NONE
showEmptyGroups: false
# If enabled slots are filled top-to-bottom instead of left-to-right
verticalMode: false
# This is how a group looks in the tabList
# Use {fillplayers} at the point where you
# wish the players to be listet
# not effective if groupPlayers=NONE
# You can also use {fillplayers:<group>}
groupLines:
- '[ALIGN LEFT][SKIN=MHF_ArrowRight]&9&l>&9 {server}({server_player_count}):'
- '{fillplayers}'
# This allows you to change the way players are listet
# You can also use multiple slots to displaye additional information
playerLines:
- '{prefix}{player}'
# These lines are shown if there's not enough space
# for all players upon the tabList
morePlayersLines:
- '... and {other_count} others'
# And here finally is the tabList
# Use {fillplayers} at the point where
# you want the players to be shown.
# You can also use {fillplayers:<group>} or {fillplayers:<server>}
# Use [ALIGN BOTTOM] to state that the folowing
# lines should be shown at the bottom of the tabList
# You can also use [ALIGN LEFT]
# You can use Variables to display dynamic content
# more information at https://github.com/CodeCrafter47/BungeeTabListPlus/wiki
tabList:
- '&4>>>>>>>>>>>>'
- '&cWelcome'
- '&cTo NeverCraft'
- '&4<<<<<<<<<<<<'
- '&4>>>>>>>>>>>>'
- '&c{player}'
- '&cHave Fun!'
- '&4<<<<<<<<<<<<'
- '[ALIGN TOP]&4============'
- '&4============'
- '&4============'
- '&4============'
- '&cHub'
- '&cCreative'
- '&cPrison'
- '&cFactions'
- '[ALIGN LEFT][COLUMN=0]{fillplayers:hub}'
- '[COLUMN=1]{fillplayers:creative}'
- '[COLUMN=2]{fillplayers:prison}'
- '[COLUMN=3]{fillplayers:factions}'
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- ' '
- '[ALIGN BOTTOM]&4============'
- '&4============'
- '&4============'
- '&4============'
- '[ALIGN BOTTOM]&6&lTotal:&c&l{gcount}&6&l/&c&l100'
- '&4&lWelcome to'
- '&4&lNever&c&lCraft'
- '&6&lHub:&c&l {players:hub}&6&l/&c&l100'


and this is my config.

# This is the Config File of BungeeTabListPlus
# You can find more detailed information on the wiki: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki

# time in seconds after which the tabList will be resend to all players
# set this to -1 to disable scheduled update of the tabList
tablistUpdateIntervall: 1.0
# whether tabList should be resend if a player joins or leaves the server
updateOnPlayerJoinLeave: true
# whether tablist should be resend if a player switches the server
updateOnServerChange: true
# whether to use scoreboard functions to bypass the 16 character limit
# does NOT conflict if other scoreboard plugins
useScoreboardToBypass16CharLimit: true
# You can limit the number of characters per slot here
# Color codes do not count as a character; -1 means unlimited
charLimit: -1
# Decide from where BungeeTabListPlus takes informations like permissions,
# prefix, suffix and group.
# Possible values:
# AUTO        - take best source
# BUKKIT      - take informations from bukkit/vault
# BUNGEEPERMS - take informations from bungeeperms
# BUNGEE      - take group from bungee, prefix from config.yml, permissions from bungee
permissionSource: AUTO
# whether ping is sent to clients
# setting this to false can help you reducing network traffic
sendPing: true
# whether to show players in suspector mode
showPlayersInGamemode3: true
# if enabled the plugin checks for new versions automatically.
# Use /BTLP to see whether a new version is available
# this does NOT automatically install an update
checkForUpdates: true
# this notifies admins (everyone with the permission `bungeetablistplus.admin`) if an update is available
notifyAdminsIfUpdateAvailable: true
# server Alias fo the {server} Variable
serverAlias:
  server3: PvP
  server2: Creative
  server1: Spawn
# Alias fo the {world} Variable. Match 'server:world' to an alias
worldAlias:
  server3:world: PvP
  server1:world1: Spawn
  server2:world: Creative
# list servers you wish to create custom prefixes for.
# to use the custom prefixes use the new {serverPrefix} variable
serverPrefixes:
  SkyBlock: '&8(&dS&8) '
  Minigames: '&8(&bM&8)'
# the prefixes used for the {prefix} variable, based upon permission groups
# IMPORTANT: these prefixes won't be used by default. see the wiki for details
prefixes:
  default: ''
  admin: '&c[A] '
# Interval (in seconds) at which all servers of your network get pinged to check whether they are online
# If you intend to use the {onlineState:SERVER} variable set this to 2 or any value you like
# setting this to -1 disables this feature
pingDelay: -1
online:
  # replacement for the {onlineState} variable if the server is online
  text: '&2 ON'
offline:
  # replacement for the {onlineState} variable if the server is offline
  text: '&c OFF'
# those fakeplayers will randomly appear on the tablist. If you don't put any names there then no fakeplayers will appear
fakePlayers: []
# servers which you wish to show their own tabList (The one provided by bukkit)
excludeServers:
- server2
- server7
# 1.8 ONLY
# When enabled the tablist will adjust it's size to the number of players online/ slots used, instead of using
# the static tab_size set in bungee's config.yml.
# WARNING: This is an experimental feature an will most likely cause bugs
# WARNING: [ALIGN=LEFT] and other formatting tags will not operate correctly
# WARNING: If this is enabled it is STRONGLY recommended to also enable verticalMode
autoShrinkTabList: false
# Detects which servers are using a bukkit-side tabList-plugin
# and lets them show it / doesn't show the tablist provided by this plugin on these servers
# This is disabled by default because it could be accidentially triggered by other plugins (Essentials nicknames etc.)
# Warning: This is an experimental feature, it may cause unintended behaviour
autoExcludeServers: false

**Comment by Neverlookbackgrg** [comment]
please assist thank you for your time

**Comment by Neverlookbackgrg** [comment]
after some diging i found out that error
[Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-880a532 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[13:59:17] [Server thread/ERROR]: Could not load 'plugins\BungeeTabListPlus_BukkitBridge-2.1.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Bukkit-880a532]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Bukkit-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [spigot.jar:git-Bukkit-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [spigot.jar:git-Bukkit-880a532]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_45]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Bukkit-880a532]
	... 8 more

**Comment by CodeCrafter47** [comment]
Looks like the file is broken. Just download it again.

**Comment by Neverlookbackgrg** [comment]
[15:27:38] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-880a532 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[15:27:38] [Server thread/ERROR]: Could not load 'plugins\BungeeTabListPlus_BukkitBridge-2.1.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot.jar:git-Bukkit-880a532]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Bukkit-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [spigot.jar:git-Bukkit-880a532]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [spigot.jar:git-Bukkit-880a532]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [spigot.jar:git-Bukkit-880a532]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_45]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_45]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot.jar:git-Bukkit-880a532]
	... 8 more

i think is the same error i use 2.1.5

**Comment by Neverlookbackgrg** [comment]
i redownloaded it

**Comment by CodeCrafter47** [comment]
Did it help? You should make sure the file size is bigger than 0 (should be ~120kb for bukkit bridge).

**Comment by Neverlookbackgrg** [comment]
yes i am unziping it using the correct files the bungee file work but the bukkit one dosen't i put it inside the faction server

**Comment by CodeCrafter47** [comment]
You could also try downloading the bukkit file from the ci server: http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/

**Comment by Neverlookbackgrg** [comment]
i check it out ASAP

**Comment by Neverlookbackgrg** [comment]
Well downloading the newest version and the bukkit bridge seems to work for now...Extra problem i will let you know.And a little help why don't you put spigot bridge and bukkit bridge inside the same folder so everybody is happy? Thank you though you are awesome bro..

**Comment by Neverlookbackgrg** [comment]
I have a question why is that happening? http://prntscr.com/8nn6kf

**Comment by CodeCrafter47** [comment]
What is wrong with the tab list?

**Comment by Neverlookbackgrg** [comment]
The one name is taking a second slot i just want it to be on one box not 2

**Comment by CodeCrafter47** [comment]
Your player names with prefixes are a bit long, so they glitch into the next slot a bit. If you don't like that you can make your prefixes shorter, so the names will fit into a single slot.

**Comment by Neverlookbackgrg** [comment]
any way to make them small i do not care if all the name is available

**Comment by CodeCrafter47** [comment]
You can set charLimit in config.yml to set the maximum length of text in a slot. If the text isl onger the plugin will cut the rest of.

**Comment by Neverlookbackgrg** [comment]
ok is it possible to show date?

**Comment by CodeCrafter47** [comment]
{date}

**Comment by Neverlookbackgrg** [comment]
I have a problem..Server 1 shows prefix ok server 2 dosen't show the prefix server1 works perfect server 2 dosen't show the prefix.. White name any ideas server 1 has 1 world server 2 has 2 worlds but same prefixes please give info thanks

**Comment by CodeCrafter47** [comment]
You need to install BungeeTabListPlus_BukkitBridge.jar on both servers. You need the same version as you install on bungee. You need to install Vault on both servers. The configuration of your permission plugin (regarding groups and prefixes) must be identical on both servers.

**Comment by Neverlookbackgrg** [comment]
yes but i can have diferent groups and diferent prefixes on the servers right?

**Comment by CodeCrafter47** [comment]
Yes you can. The plugin will always take the prefix for a player from the server that player is playing on.

**Comment by Neverlookbackgrg** [comment]
well i have a prefix in the server at chat on server 1 works fine on server 2 the prefix on chat is okay but on tab is not okay

**Comment by CodeCrafter47** [comment]
I think it's an issue with your setup. Why don't you take a look at the log files of your servers. I'm sure you will find some errors or warnings or some other hints that tell you what's wrong.
