### ISSUE TITLE
BungeeTabList Config Error

### ISSUE THREAD

**Issue by Predzzy** [CodeCrafter47/BungeeTabListPlus#492]
Literally using the default configuration and when i do /btlp reload i get this error in console.

21.01 11:37:18 [Server] INFO btlp reload
21.01 11:37:18 [Server] INFO [BungeeTabListPlus] Loading default.yml
21.01 11:37:18 [Server] WARNING [BungeeTabListPlus] Failed to load default.yml
21.01 11:37:18 [Server] INFO Failed to validate config
21.01 11:37:18 [Server] INFO in 'reader', line 13, column 1:
21.01 11:37:18 [Server] INFO showTo: 'all'
21.01 11:37:18 [Server] INFO ^
21.01 11:37:18 [Server] INFO com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:250)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.libs.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.libs.snakeyaml.Yaml.loadAs(Yaml.java:410)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:102)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig.read(YamlConfig.java:98)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.managers.TabListManager.loadTabLists(TabListManager.java:67)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.BungeeTabListPlus.reloadTablists(BungeeTabListPlus.java:426)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.BungeeTabListPlus.reload(BungeeTabListPlus.java:411)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.BungeeTabListPlus.lambda$reload$1(BungeeTabListPlus.java:376)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:98)
21.01 11:37:18 [Server] INFO at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
21.01 11:37:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21.01 11:37:18 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21.01 11:37:18 [Server] INFO at java.lang.Thread.run(Thread.java:748)
21.01 11:37:18 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;I)V
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.config.FixedSizeConfig.validate(FixedSizeConfig.java:48)
21.01 11:37:18 [Server] INFO at codecrafter47.bungeetablistplus.yamlconfig.YamlConfig$MyConstructor.constructObject(YamlConfig.java:248)

**Comment by CodeCrafter47** [comment]
You are not using the latest version of BungeeTabListPlus. In addition you appear to be using an old version of BungeeCord. Please update your software.

**Comment by Predzzy** [comment]
Im using version 2.8.12 of BungeeTabListPlus since the newer versions don't work for me

And yeah im using a 1.7 - 1.8 Bungee as my server is only 1.7 - 1.8

Is there any fix at all for this? i know im using old versions and probably wont't get support for them
