### ISSUE TITLE
having a player nickname issue with bungeetablistplus

### ISSUE THREAD

**Issue by Cayde-x** [CodeCrafter47/BungeeTabListPlus#494]
when i added i got a weird text behind my player name and i tried hours to fix the problem but nothing seems to work i hope you could help me.
![playerproblem](https://user-images.githubusercontent.com/60242451/73030911-f8b72980-3e3a-11ea-8772-bcb530fcba62.png)

**Comment by CodeCrafter47** [comment]
To me this looks like the plugin fails to correctly detect your minecraft version. Are you running some fork instead of the official BungeeCord? Are you using ViaVersion or ProtocolSupport?

**Comment by Cayde-x** [comment]
Im using the latest viaversion

**Comment by CodeCrafter47** [comment]
Is ViaVersion installed on BungeeCord or spigot. If it is BungeeCord I recommend you install it on Spigot instead. That way it can not interfere with BungeeTabListPlus. That is also the way ViaVersion developers recommend it to be used.

**Comment by Cayde-x** [comment]
Yeah you're right it fixed the problem thank you
