### ISSUE TITLE
java.lang.IllegalArgumentException: firstIndex < this.size

### ISSUE THREAD

**Issue by freak-dk** [CodeCrafter47/BungeeTabListPlus#496]
Getting the following error on 3.0.6 
https://pastebin.com/Jk1iK8Jn
Tablist https://pastebin.com/GicPRLRb

I am using a fork of Bungeecord (FlameCord, which is basically Waterfall) and saw hints that the plugin might just not run on a fork?

Any info much appreciated

**Comment by CodeCrafter47** [comment]
Please double check whether you are really using version 3.0.6 of BungeeTabListPlus.

**Comment by freak-dk** [comment]
Pfff my mystake, appears I was running  3.0.5.
Don't really get how though, got an email about the update and went ahead and downloaded it. 
Anyways will try using the newest version and report back, my bad.
