### ISSUE TITLE
Issues on player join

### ISSUE THREAD

**Issue by sannielollie** [CodeCrafter47/BungeeTabListPlus#498]
Hi, since the last few updates (running 3.0.7 now) my TABlist just goes drunk when a player joins. If i reload the plugin using btlp reload (from my bungeecord console) the TAB shows up normally, untill a player joins. Then i just get this error in my console: https://pastebin.com/3dYnBJfA

When i reload the plugin i get no error at all. Also on server start it looks clean:
22:23:34 [INFO] [BungeeTabListPlus] Starting UpdateChecker Task
22:23:34 [INFO] Enabled plugin BungeeTabListPlus version 3.0.7-SNAPSHOT by CodeCrafter47
22:23:35 [INFO] Listening on /0.0.0.0:25565

It does this to my tablist:
https://i.imgur.com/zrXD2Ra.png before playerjoin
https://i.imgur.com/JToy2Qa.png after rejoin, without reloading the plugin

Before, when i used version 2.8.11 i had no issues at all regarding this. As a temp workaround i am using a automated command, running every 30 seconds in Bungeecord doing "/btlp reload"

**Comment by CodeCrafter47** [comment]
Please double check whether you are really running version 3.0.7 of the plugin (from spigot, not the dev-build). I believe this issue has been fixed there.
