### ISSUE TITLE
TabList is Global?

### ISSUE THREAD

**Issue by Predzzy** [CodeCrafter47/BungeeTabListPlus#500]
Sorry for sounding like a noob i read the wiki on how to do this but i don't get it.

How do i make the tablist only show players that are on the server they're on? not global

My config file:

**Comment by CodeCrafter47** [comment]
I do not think that config file is related to this plugin. There is an example on the wiki for what you want to do: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples#only-display-players-on-the-same-server>.
