### ISSUE TITLE
Dynamic Type

### ISSUE THREAD

**Issue by zManuu** [CodeCrafter47/BungeeTabListPlus#502]
Hey!
I want to setup a Tablist for my Bungeecord-Server. No Server, placeholders, just a normal tablist. The code out of the example isnt working: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Configuration-Basics-Part-5---Dynamic-Size-Tablist 
![image](https://user-images.githubusercontent.com/60520810/73564052-17cb4200-445f-11ea-8562-bc3fcce5924b.png) 

Can someone help me?

**Comment by CodeCrafter47** [comment]
You are using an old version of the plugin. Update to the latest version to fix the issue.
