### ISSUE TITLE
Some Player Head Icons do not fit the player name

### ISSUE THREAD

**Issue by bloggy** [CodeCrafter47/BungeeTabListPlus#503]
I just noticed that some player heads are not fitting to the right player, they are displayed next to a random player. Using latest version of your plugin and paper spigot.

**Comment by CodeCrafter47** [comment]
Do you have a way of reproducing this bug, or does it just occur randomly?

**Comment by bloggy** [comment]
I can not reproduce it. It's just random. Also I noticed that the color of the player display name's are changing randomly on the same server where the mentioned issue occurs.

**Comment by CodeCrafter47** [comment]
Can you check if the new version 3.0.9 fixes the issue?

**Comment by bloggy** [comment]
It seems to fix it.
But have another bug. The player head icon in the tablist is displaying another random player's head IF the player is in vanish mode (using vanish plugin: https://dev.bukkit.org/projects/vanish ).

**Comment by CodeCrafter47** [comment]
All players (more precisely their icons) on the server (spigot) need to be on the tab list. Completely removing a player from the tab list if vanished is only possible when using a vanish plugin that supports this (e.g. SuperVanish). When using a dynamic size tab list the recommendation is to use 
```yaml
hiddenPlayers: VISIBLE
```
to avoid issues.

**Comment by CodeCrafter47** [comment]
Have you been able to fix the issue?
