### ISSUE TITLE
Why is ~BTLP Slot 0   BTLPfcfeffbf 00 now?

### ISSUE THREAD

**Issue by rasputinea** [CodeCrafter47/BungeeTabListPlus#505]
https://imgur.com/a/2WNRs1d sorry if this issue has been reported already, i would assume it has but i cannot find it

**Comment by CodeCrafter47** [comment]
This change is intentional. I added some random characters so nothing breaks if someone is stupid enough to put two BungeeCord instances behind each other and install the plugin on both.

**Comment by clrxbl** [comment]
Would it be possible to hide these?

**Comment by CodeCrafter47** [comment]
If the size of the tab list is 80 slots then these can be hidden. This is planned for version 3.1.0 of the plugin. If the size of the tab list is smaller, then nothing can be done.

**Comment by CodeCrafter47** [comment]
See #384 for updates on this.
