### ISSUE TITLE
can't join my server 

### ISSUE THREAD

**Issue by Zipp3y** [CodeCrafter47/BungeeTabListPlus#509]
I can't join my server in 1.12.2
Console says:

06.02 12:21:31 [Server] SEVERE [Zipp3y] -> UpstreamBridge - encountered exception

06.02 12:21:31 [Server] INFO io.netty.handler.codec.EncoderException: java.lang.NullPointerException
06.02 12:21:31 [Server] INFO at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
06.02 12:21:31 [Server] INFO at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:762)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:788)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:756)
06.02 12:21:31 [Server] INFO at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
06.02 12:21:31 [Server] INFO at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
06.02 12:21:31 [Server] INFO at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
06.02 12:21:31 [Server] INFO at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:145)
06.02 12:21:31 [Server] INFO at codecrafter47.bungeetablistplus.handler.TabOverlayHandlerImpl.sendPacket(TabOverlayHandlerImpl.java:40)
06.02 12:21:31 [Server] INFO at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler$CustomContentTabOverlayHandler.onActivated(AbstractTabOverlayHandler.java:1253)
06.02 12:21:31 [Server] INFO at codecrafter47.bungeetablistplus.handler.AbstractTabOverlayHandler.update(AbstractTabOverlayHandler.java:473)
06.02 12:21:31 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
06.02 12:21:31 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
06.02 12:21:31 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
06.02 12:21:31 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
06.02 12:21:31 [Server] INFO at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
06.02 12:21:31 [Server] INFO at java.lang.Thread.run(Thread.java:748)
06.02 12:21:31 [Server] INFO Caused by: java.lang.NullPointerException
06.02 12:21:31 [Server] INFO at us.myles.viaversion.libs.bungeecordchat.api.chat.BaseComponent.toLegacyText(BaseComponent.java:226)
06.02 12:21:31 [Multicraft] Skipped 15 lines due to rate limit (30/s)

**Comment by CodeCrafter47** [comment]
Please install ViaVersion on your Spigot servers, not on BungeeCord.

**Comment by Zipp3y** [comment]
It is working! ty!
