### ISSUE TITLE
Question about server connect and disconnect

### ISSUE THREAD

**Issue by devocite** [CodeCrafter47/BungeeTabListPlus#51]
Hello, I am working on running down a bug, but I can't quite figure out where it is.
Our server uses Bungee Cord, Log Block, and BungeeTabListPlus, among some others.

Here is what I'm seeing, when moving between servers, the Log Block plugin isn't logging a logout, but getting a login for the server they moved to.
Something is suppressing logout messages to the Log Block plugin.

I see a proper logout on the console.
Just seeing what you think.

**Comment by CodeCrafter47** [comment]
Log Block is a bukkit plugin, this is a bungee plugin. I don't think the issue is related to this plugin.

**Comment by devocite** [comment]
I believe you are right.  It appears to be related to the PlayerQuitEvent not being fired correctly.
Sorry for the bother.
