### ISSUE TITLE
Tab complete in Chat

### ISSUE THREAD

**Issue by Cerexus** [CodeCrafter47/BungeeTabListPlus#514]
Hey, if i press the tabulator button for auto complete it shows me that:

http://prntscr.com/r0qygb

What can i do?

**Comment by CodeCrafter47** [comment]
There is not a lot that can be done about it.

If you use the latest dev-build those entries should appear below the normal user entries. For the next big update (3.1.0) it is planned to remove those entries, but only if the size of the tab list is 80 slots.

**Comment by CodeCrafter47** [comment]
See #384 for updates on this.
