### ISSUE TITLE
Strings are above the ping bar

### ISSUE THREAD

**Issue by MatteCarra** [CodeCrafter47/BungeeTabListPlus#52]
If I shrink minecraft this happens:
![2015-09-19_22 18 34](https://cloud.githubusercontent.com/assets/11074527/9977988/949aaff0-5f1c-11e5-82fc-4fda4ecb3562.png)

**Comment by brainscript** [comment]
@MatteCarra :laughing: That's because of the minimap mod.

**Comment by CodeCrafter47** [comment]
Also happens without this plugin.

**Comment by MatteCarra** [comment]
I confirm @CodeCrafter47 .
![2015-09-21_17 04 00](https://cloud.githubusercontent.com/assets/11074527/9996886/8f69478a-6089-11e5-9030-5664940028eb.png)

**Comment by MatteCarra** [comment]
@CodeCrafter47 
yes, you are right.
I didn't notice it before

**Comment by brainscript** [comment]
@CodeCrafter47 Why bug? You can't fix **a feature** of a mod? I would just close this issue.

**Comment by CodeCrafter47** [comment]
Even without the minimap mod the tab list looks messed up when shrinking the window. I can't fix that either, but that's the reason I didn't close this yet.
