### ISSUE TITLE
Problem with CMI placeholders

### ISSUE THREAD

**Issue by SeruhioX** [CodeCrafter47/BungeeTabListPlus#521]
Today I updated from version 2.8.9 to 3.0.9 and could't use the placeholder that I already used before "cmi_user_afk", this was already working before, I updated to version 3.0.10 #907 but it still fails.

[10:56:23] [main/WARN] [BungeeTabListPlus]: There have been 1 warnings while loading plugins/BungeeTabListPlus/tabLists/default.yml
WARNING: Error in placeholder ${player cmi_user_afk}:
Unknown placeholder
 in 'reader', line 72, column 16:
        condition: ${player cmi_user_afk} == "§aAc
                   ^
 in use of placeholder ${afk_tag1}
 in 'reader', line 55, column 22:
        playerComponent: "${player vault_suf
                         ^

[10:56:23] [main/INFO]: Enabled plugin BungeeTabListPlus version 3.0.10-SNAPSHOT by CodeCrafter47

**Comment by CodeCrafter47** [comment]
That is a placeholder from PlaceholderAPI. It will work, the warning will disappear once BungeeTabListPlus is able to resolve it for the first time, i.e. the first time someone connects to a server with PlaceholderAPI and CMI installed.

**Comment by SeruhioX** [comment]
Thank you!
