### ISSUE TITLE
Latest BTLP screwed up our tab list...

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#522]
Latest dev build:
https://i.imgur.com/n5KavYA.png

tablist:
https://pastebin.com/raw/hxYBck2k (server is 1.15.2)

Not having issue on this server (1.12.2)
https://i.imgur.com/oIc4MK7.png
https://pastebin.com/raw/4PEHfukr

What happened here?
Happened ever since we updated to 3.0.10-Dev-908 on the bungee instance and across all servers.
3.0.10-Dev-900 was absolutely fine with no issues.

**Comment by CodeCrafter47** [comment]
I thinks that is probably a bug introduced by 037daf1. That commit removes the fake players from tab completion.

Are you using ViaVersion or something similar?

**Comment by andrewkm** [comment]
No, we are not using ViaVersion, this is hug exists on 1.15.2 servers on our network.

**Comment by andrewkm** [comment]
I've just tried on default spigot with no plugins, just bungeetablistplus with the above config.
It basically duplicates the players on the tablist I posted above.

https://i.imgur.com/An6e0km.png

Reverting back to 906 has fixed all my issues. 907 is broken.

**Comment by CodeCrafter47** [comment]
Somehow I fail to reproduce this issue in my test setup. Which version of BungeeCord are you using? Does `/btlp reload` help?

**Comment by CodeCrafter47** [comment]
I am still unable to reproduce the issue. However I have added two commits that slightly change/ simplify how the tab list works. It is possible this fixes the issue, but I can not tell. If not we need to come up with some way to reproduce the issue.

**Comment by andrewkm** [comment]
Your latest commits do not fix the issue unfortunately.
A few /btlp reload's fixes it (sometimes 2, sometimes 3, but as soon as users login, it's broken again).
I'm going to stick to 906 for now, as 907 literally destroys all of tab :(
A few others I know have the same issue on 907.

**Comment by mibby** [comment]
So far the issue seems fixed for me with dev 913. I'll let you know if it reoccurs though, just seems fine after initial updating and logging on with users.

**Comment by andrewkm** [comment]
Dev 913 continues to be broken for me:
https://i.imgur.com/2nTBRdJ.png
Dev 906 has no issues and works perfectly fine.

**Comment by CodeCrafter47** [comment]
Can you checkout the latest dev-build? I have taken a slightly different approach towards there.

**Comment by andrewkm** [comment]
Initial testing shows no issues (via test machines).
Will launch in production shortly and report back soon. @CodeCrafter47

**Comment by andrewkm** [comment]
Confirmed fixed on production @CodeCrafter47

**Comment by andrewkm** [comment]
Nevermind, still broken when switching servers.
Ugh, I'm just going to revert to 906 permanently lol.
930 is a wild mess when switching servers.

https://i.imgur.com/zkIsGm4.png

**Comment by mibby** [comment]
@CodeCrafter47 This issue seems to be back for me with dev 927. Not too sure what changed though since you re-implemented the commits that were reverted. :( Maybe the player was in a bugged logging in state, both online and offline (loading/relog)?

![link2](https://i.imgur.com/x3gMprB.png)

How it normally looks.
![link3](https://i.imgur.com/SsEpwJa.png)
I also noticed it flashes for a second or two (where the bottom row appears at the top) when you login / change worlds.

**Comment by CodeCrafter47** [comment]
You say, you are having the issue with build 927. Does that mean it did not occur with 926, or did you just not test that one?

**Comment by mibby** [comment]
I tested 913 when you first made changes to try and fix it. Didn't come across any issues but may have just not noticed? 

Then updated to 927 where you re-implemented the fix after it was reverted (in-between newer dev builds) but am noticing tab break more often. Flickering during world change with the bottom appearing at the top and breaking sometimes on player logins (assuming when they are stuck in loading limbo between connected and disconnected).

Going to revert back to 906 for the time being as well. :(

**Comment by CodeCrafter47** [comment]
So far I have not been able to reproduce this issue at all. So I will probably revert the commit causing it before the next update. The only way I can see to fix the issue and keep the feature causing it would be to come up with a reliable way of reproducing the issue. Or someone who can reproduce it could do the testing for me - but it would probably require a lot of testing to pin down the issue.

**Comment by andrewkm** [comment]
Awesome! Thanks :)
Will allow me to finally update and use that invisibility potion fix you made. :D

**Comment by MWLVegas** [comment]
Amongst those having the same issue ... The server's Tab list displays before any BTLP stuff, and Spacer isn't formatting to the bottom, even using default tabLists. Sometimes it does NOT Show the player names for the people on the same server, sometimes it does - I'm not sure why.

**Comment by CodeCrafter47** [comment]
The commit causing this issue was reverted three days ago, so it should not occur anymore starting from dev-build 937.

**Comment by andrewkm** [comment]
Everything is now working as it should after the revert. Thank you!!!

**Comment by MWLVegas** [comment]
My post was after updating to #937. Currently using #941 and still occurring. 
![2020-03-25 - 06 44 51 ~ Cropped Capture](https://user-images.githubusercontent.com/3679851/77542943-30a31300-6e64-11ea-85f7-08413c6d1135.png)

**Comment by andrewkm** [comment]
@MWLVegas are you sure you updated both bungee and spigot servers?

I am on 938 and every problem has been fixed. Confirmed and running live in production for hours.

**Comment by MWLVegas** [comment]
100% positive.

Bungee:
![2020-03-25 - 06 57 36 ~ Cropped Capture](https://user-images.githubusercontent.com/3679851/77544606-752fae00-6e66-11ea-9985-9fc3260434e5.png)

Spigot:
![2020-03-25 - 07 01 15 ~ Cropped Capture](https://user-images.githubusercontent.com/3679851/77544624-7c56bc00-6e66-11ea-8a88-a27f4d272297.png)

Granted, that doesn't show build number, but I reinstalled both again this morning, just in case.
