### ISSUE TITLE
hiddenServers

### ISSUE THREAD

**Issue by FunnysBanana** [CodeCrafter47/BungeeTabListPlus#525]
Hello <:

I updated to the new version and now i can`t hide any server .-.

[cfg](https://i.imgur.com/oKMoQI7.png)

[tab](https://i.imgur.com/zIdHyXF.png)

**Comment by CodeCrafter47** [comment]
The latest dev-build should fix the issue.

**Comment by FunnysBanana** [comment]
it works!
thx
