### ISSUE TITLE
Player component not working

### ISSUE THREAD

**Issue by mellowism** [CodeCrafter47/BungeeTabListPlus#526]
I can't get playercomponents to work in 3.0.9 the same way as it did in the previous version. 
I am trying to use multiple slots per player:
  playerComponent:
  - {text: "${player name}", icon: "${player skin}", ping: "${player ping}"}
  - {text: "${player server}", icon: "${player skin}", ping: "${player ping}"}
  - {text: "${player vault_player_prefix}", icon: "${player skin}", ping: "${player ping}"}
  - {text: "${player ping}ms", icon: "${player skin}", ping: "${player ping}"}

This used to work but now it doesn't show anything. 
It works If I change to: 
  playerComponent: "${player name}"

My config: https://pastebin.com/0yUXEqzV

Any help is much appreciated.

**Comment by CodeCrafter47** [comment]
Just use `playerComponent: "${player name}"`. The plugin will display the players skin and ping by itself.

**Comment by mellowism** [comment]
I feel I need to clarify. I am using https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Examples#using-multiple-slots-per-player

But as soon as I enter more than one line after each other like so: 
- ${player name}
- ${player server}

The players disappear?

I want to be able to use this layout, it worked fine in 3.0.8.

**Comment by CodeCrafter47** [comment]
I had another look at it. Seems there is a bug in the plugin. Checkout the latest dev-build, that should fix it.

Also there is an issue in your config:
```yaml
  all_players: all
    filter: all
    hiddenPlayers: VISIBLE
```
should be 
```yaml
  all_players:
    filter: all
    hiddenPlayers: VISIBLE
```

**Comment by mellowism** [comment]
Perhaps a bit of noob here but I can only find the source code. Do I need to build it myself? Could you link it? :)

**Comment by mellowism** [comment]
Btw, it spams me in-game that there's a new version of BungeeTabListPlus but it's not updated in Spigot yet.

**Comment by CodeCrafter47** [comment]
The dev-build can be found at <https://ci.codecrafter47.de/job/BungeeTabListPlus/>.

Also it is possible to download version 3.0.10 from spigot (it will not fix your issue, though), so the update the plugins tells you about does exist.

**Comment by mellowism** [comment]
That worked yes. Thanks!
