### ISSUE TITLE
no PAPI into Tabs after major update

### ISSUE THREAD

**Issue by jewome62** [CodeCrafter47/BungeeTabListPlus#529]
Hello,
I have update BTLP yesterdat from 2.X to 3.0.10
on paper 1.13.2/bungeecord 1.15 and bridge is well updated

![image](https://user-images.githubusercontent.com/472429/76618687-776e4000-6529-11ea-83d7-cc2b64ad9867.png)

papi is well installed, and last version
in the screen, i have try a placeholder (into command line) and the result on the screen is 12

![image](https://user-images.githubusercontent.com/472429/76618837-d3d15f80-6529-11ea-811f-813293c484ed.png)

But into BTLP (last line) the placeholder don"t work anymore after BTLP update

![image](https://user-images.githubusercontent.com/472429/76618897-fbc0c300-6529-11ea-8402-90d29546e950.png)
The lien into config (this is the lastest lines)
```yaml
- {text: "&cRD Serveur: &6${viewer VDIST_PLAYER_SUPPORTED_VIEW}", icon: "default/server.png", ping: 0}
- {text: "&cRD Client: &6${viewer VDIST_PLAYER_SETTINGS_VIEW}", icon: "default/rank.png", ping: 0}
- {text: "&cRD Current: &6${viewer VDIST_PLAYER_CURRENT_VIEW}", icon: "default/players.png", ping: 0}
```

So i would know if something change into syntax, because i did not find changelog to update this major release ?

Thanks

**Comment by CodeCrafter47** [comment]
Do other PAPI placeholders work? I.e. placeholders provided by a different plugin/ extension. I have a feeling that the placeholder being uppercase might be causing the issue.

**Comment by jewome62** [comment]
Hello @CodeCrafter47
I have change nothing on configuration, or with papi, just update BungeeTabListPlus
if i try /papi parse with key on lowercase, that's not working.

**Comment by jewome62** [comment]
this is the unique placeholder importer by PAPI, the other is already integrated into config (luckperms, ping, etc)

**Comment by jewome62** [comment]
Maybe the lowercast here ? https://github.com/CodeCrafter47/BungeeTabListPlus/blob/95cb52b6ca8661b37b7b3c545f16ca09fe7a94a6/bungee/src/main/java/codecrafter47/bungeetablistplus/placeholder/PlayerPlaceholderResolver.java#L235

**Comment by CodeCrafter47** [comment]
I removed that cast to tlowercase. Can you check if the latest dev-build fixes the issue?

**Comment by jewome62** [comment]
i will try this tomorrow. Thanks

**Comment by jewome62** [comment]
@CodeCrafter47 That's work well with dev build, Thx
