### ISSUE TITLE
No compatible with 1.6.4 BungeeCord

### ISSUE THREAD

**Issue by CodeCrafter47** [CodeCrafter47/BungeeTabListPlus#53]
The plugin doesn't run on 1.6.4 BungeeCord. I identified the following problems:
- [ ] it is not possible to start 1.6.4 BungeeCord with Java 8 but the plugin requires Java 8
- [ ] the plugin calls ProxiedPlayer#getUniqueId which is not available on 1.6.4

**Comment by DistortedDorian** [comment]
I believe the oldest supported version is 1.7.x, I feel like you are missing out on a lot by running on 1.6.4, perhaps considern updating?

**Comment by CodeCrafter47** [comment]
I'm not running 1.6.4 anymore. But the plugins has been compatible with 1.6.4 some time ago and there is still some code for 1.6.4 support in it (https://github.com/CodeCrafter47/BungeeTabListPlus/tree/master/network/1.6.4). 
I don't know whether anyone is still running the plugin on 1.6.4 or whether support for that is still required. This issue is just to remind me to either make the plugin compatible with 1.6.4 again or to delete the 1.6.4 support code completely.

**Comment by brainscript** [comment]
@CodeCrafter47 I don't think there is a reason to use older BC versions. I would remove the 1.6.4 support.
