### ISSUE TITLE
BungeeTabListPlus breaks invisibility potions.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#530]
When using your standard Minecraft Invisibility potions, BTLP makes the user transparent.
However, when removing BTLP the user is properly vanished.

This has been quite a long standing issue and we just got to the bottom of it being purely BTLP's fault.
Even running on no plugins, and only using BTLP on the bungee instance, the issue is reproduced. However, when removing BTLP, all is fine again.

Tested on both BTLP 906(currently using in production) and BTLP 930(latest)

Transparent users look as such:
https://i.imgur.com/qDnFVio.png

I believe something to do with:
`if (this.canSeeFriendlyInvisibles()) {
            i |= 2;
        }`

**Comment by electronicboy** [comment]
the friendly fire byte controls if an entity is "visible" or not when in the same team, it looks like BTLP is using "3" across the board (or in a fair number of places when I find usages), which sets friendly fire and the option to see entities which are invis

**Comment by andrewkm** [comment]
This issue has been confirmed fixed.
