### ISSUE TITLE
Hidden Servers not working.

### ISSUE THREAD

**Issue by Onfimarist** [CodeCrafter47/BungeeTabListPlus#533]
Hello there! I don't know why this is happening but the hidden servers stuff isn't working. My config is like this:

```yaml
hiddenServers:
  - lobby1
  - lobby2
  - lobby3
```

After this, I did a /bungeetablistplus reload but it didn't remove the players in those servers from the TAB list. Don't know what might be happening. Those servers have the BungeeTabListPlusBridge plugin.

Version: 1.13.2
TAB: 3.0.10
Bridge: 3.0.10

In advanced, thanks for helping out!

**Comment by CodeCrafter47** [comment]
The `hiddenServers` option in `config.yml` hides players on these servers, but not the servers themselves. It is also affected by other options related to hidden players, see <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Hidden-Players>. By default players with the `bungeetablistplus.seevanished` will be able to see hidden players.

**Comment by lokka30** [comment]
if you use players by server. you can specify `hiddenServers: [server1, server2, etc]`.
