### ISSUE TITLE
Fix 1.12.2 and lower with ViaVersion Bungee please

### ISSUE THREAD

**Issue by Justsnoopy30** [CodeCrafter47/BungeeTabListPlus#534]
https://pastebin.com/QVKQ2PFb

**Comment by Justsnoopy30** [comment]
ViaVersion said it's an issue with the plugin.

**Comment by Justsnoopy30** [comment]
I am unable to use it on the backend servers.

**Comment by CodeCrafter47** [comment]
If you tell me how I'll fix it. It crashes when BTLP tries to send a team packet. Without ViaVersion that needs to look differently depending on the version of the client (which BTLP does correctly). With ViaVersion I have no idea how it needs to look. But I think ViaVersion tries to rewrite a packet that is already correct for the client version.

**Comment by Justsnoopy30** [comment]
Electroniccat (mod on viaversion discord) said:

> https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/BaseComponent.java#L226
> looks like something is sending a null chat component
> Ah, the plugin ain't setting a display name.

**Comment by CodeCrafter47** [comment]
It's not null, I set it to an empty string which would be correct for 1.12.2 clients.

**Comment by Justsnoopy30** [comment]
Maybe you should hook into viaversion?

**Comment by CodeCrafter47** [comment]
I think that might be a way to solve the issue.

For 1.12 clients the display name is just a string, for 1.13+ clients it is a text component. BungeeTabListPlus decides which one is correct depending on the client version. With ViaVersion transforming the packets before they are sent to the client that is not good enough. I think it may depend on the server version or something like that.

I do not know what would be the correct way for the plugin to decide what to do with ViaVersion in mind. I am not willing to spend many hours figuring out how ViaVersion works. So if people who care about this issue or people familiar with ViaVersion come up with some suggestions I am happy to try those, but I will not put a lot of research effort into this myself.

**Comment by CodeCrafter47** [comment]
Can you check if the latest dev-build fixes the issue?

**Comment by Justsnoopy30** [comment]
Okay.
Will check.

**Comment by Justsnoopy30** [comment]
Issue fixed! 😄
