### ISSUE TITLE
Player inherits from multiple groups - broken TAB priority

### ISSUE THREAD

**Issue by astetyn** [CodeCrafter47/BungeeTabListPlus#535]
I am using LuckPerms and all players are in default group (highest weight) and when somebody buys VIP, luckperms gives player group.vip with expiry with lower priority. Order in TAB is then completely broken. This issue is only when player inherits from multiple groups, in this example vip and default.

**Comment by CodeCrafter47** [comment]
I think the VIP group is supposed to have the higher priority.

**Comment by astetyn** [comment]
Maybe I have opposite order in config beacuse when players don't have two groups (where one of them has expiry) it is working well and players are ordered correctly.

**Comment by astetyn** [comment]
This is in BTLP config: `playerOrder: "luckpermsbungee_primary_group_weight asc"`
and this is in the luckperms config: `primary-group-calculation: parents-by-weight`

but still, players who have expiry-group are sorted randomly.

**Comment by astetyn** [comment]
Solved. Problem was on LuckPerms side. Primary group was not setup corretly.
