### ISSUE TITLE
Can't use "HiddenServers" to hide servers from tablist.

### ISSUE THREAD

**Issue by jadsspt** [CodeCrafter47/BungeeTabListPlus#537]
Using "hiddenServers" simply doesnt work, see the screenshots ahead:

Config:
![1](https://user-images.githubusercontent.com/47069768/76926222-bf97b480-68d3-11ea-913d-8901dc1b629d.png)

Tablist:
![2](https://user-images.githubusercontent.com/47069768/76926224-c0c8e180-68d3-11ea-8f71-18311046a27f.png)

**Comment by mxs42** [comment]
Fixed in latest dev versions https://github.com/CodeCrafter47/BungeeTabListPlus/commit/c14176a01404188474014e2bacf2eb3fe19f6448

**Comment by jadsspt** [comment]
Ok thanks 👍

**Comment by CodeCrafter47** [comment]
There is actually an update on spigotmc, so if you download the latest version from there you won't have any issues.
