### ISSUE TITLE
Is it possible to have different name colors depending on their group?

### ISSUE THREAD

**Issue by JasonHorkles** [CodeCrafter47/BungeeTabListPlus#541]
I'm trying to make it so different groups will change the color of the person's player name but I can't figure out how. The person doesn't want to show prefixes in tab and only the name with the corresponding color. Is this even possible with a dynamic tab list?

**Comment by CodeCrafter47** [comment]
You can modify how players appear on the tab list by changing the `playerComponent` option.

If you do not want to use the prefixes provided by your permission plugin you can create custom ones - just for the tab list - if you like only containing color codes. Have a look at <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/CustomPlaceholders#creating-custom-prefixes>.

**Comment by JasonHorkles** [comment]
Awesome that worked! Thank you!
