### ISSUE TITLE
Player heads not shown

### ISSUE THREAD

**Issue by psrcek** [CodeCrafter47/BungeeTabListPlus#544]
Player heads are not being shown. I'm using the [default config](https://pastebin.com/s4e6Cs1E).

![image](https://user-images.githubusercontent.com/13370323/77239380-69c85280-6bda-11ea-9e51-5263d2543858.png)

![image](https://user-images.githubusercontent.com/13370323/77239442-1276b200-6bdb-11ea-82de-357f24776fe0.png)

**Comment by CodeCrafter47** [comment]
Icons are not available in offline mode.

**Comment by psrcek** [comment]
Is that you doing that on purpose or is it because of a protocol limitation?

**Comment by CodeCrafter47** [comment]
It happens on the client, so there is nothing I can do about it. I think the idea is that when you are offline it cannot download the skins.

**Comment by psrcek** [comment]
IDK, but maybe some of this code would be of help: https://github.com/SkinsRestorer/SkinsRestorerX
Its definitely possible to change the physical skin, IDK about tab, the APIs should be similar, right?

**Comment by CodeCrafter47** [comment]
It happens client side. It cannot be fixed by a server plugin. See #269 for more information and possible work-arounds/ fixes.
