### ISSUE TITLE
Bungeetablist on main servers stopped working randomly

### ISSUE THREAD

**Issue by SilentRoses** [CodeCrafter47/BungeeTabListPlus#548]
No changes have been made to my tablist for the past month. However out of no where the tablists ceased to work. Server versions range from 1.8 all the way to 1.15.2 The hub has a seperate tab and works fine. Issue is only on other servers. A config can privately be shared if you'd like to contact me via discord: Rosie#9628 Plugin version is latest release. 3.0.10

**Comment by CodeCrafter47** [comment]
I think we've fixed this.
