### ISSUE TITLE
Memory leak in DataManager$LocalDataCache

### ISSUE THREAD

**Issue by sandtechnology** [CodeCrafter47/BungeeTabListPlus#549]
Recently my BC server having memory issue when running server for a long time, and I found this:
![TIM截图20200327210259](https://user-images.githubusercontent.com/20417547/77758888-bc888b00-706e-11ea-900c-4f7779506329.jpg)
![TIM截图20200327210230](https://user-images.githubusercontent.com/20417547/77758894-beeae500-706e-11ea-8cf5-c3f6ffbe6f1b.jpg)
![TIM截图20200327212136](https://user-images.githubusercontent.com/20417547/77760248-fa86ae80-7070-11ea-9ddb-4c807e50a184.jpg)

Could you fix this serious issue? I'm using BungeeTabListPlus 3.0.10

**Comment by CodeCrafter47** [comment]
This appears to fix the issue for me. Let me know if it works for you.

**Comment by sandtechnology** [comment]
> 
> 
> This appears to fix the issue for me. Let me know if it works for you.

Thanks, I will test for a few days to see if it fixed

**Comment by DanielAlves123** [comment]
@sandtechnology how do you check dumps?

**Comment by sandtechnology** [comment]
Looks like it fixed, thanks!

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology how do you check and generate dumps?

Use JDK command to dump to file, and open it by Visualvm: https://visualvm.github.io/
(You can also dump it directly by Visualvm, I dump it by JDK just because freuently Full GC overload my CPU so I can't start Visualvm)

**Comment by DanielAlves123** [comment]
@sandtechnology can you give me contact to you? I have 1 question
