### ISSUE TITLE
ClosedChannelException warning spammed in console

### ISSUE THREAD

**Issue by JasonHorkles** [CodeCrafter47/BungeeTabListPlus#551]
Sometimes either randomly or when a player leaves or times out console will be spammed with the warning below. Is there some sort of incompatibility with Java 11 and/or Tuinity?
```
>.... [17:56:07 WARN]: java.nio.channels.ClosedChannelException
>.... [17:56:07 WARN]: at io.netty.channel.AbstractChannel$AbstractUnsafe.close(...)(Unknown Source)
```

**Comment by CodeCrafter47** [comment]
How is your issue related to my plugin?

**Comment by JasonHorkles** [comment]
Error goes away when I remove the bridge

**Comment by CodeCrafter47** [comment]
Are you getting those errors on BungeeCord or on Bukkit?

**Comment by JasonHorkles** [comment]
Bukkit (but I'm using Java 11 and Tuinity - a fork of paper)

**Comment by CodeCrafter47** [comment]
I'm not sure I can do anything about this. I don't think it's harmful.

**Comment by JasonHorkles** [comment]
I mean if my host sees that it gets spammed too much it stops the server but it's fine now that I went back to Java 8 and paper instead

**Comment by JasonHorkles** [comment]
When I say it spams I mean it like really spams lol
Here's a pic zoomed in
![image](https://user-images.githubusercontent.com/51760372/78052690-b29bac00-733c-11ea-9ebb-5836cdee52d0.png)
And zoomed out as far as my text editor will go
![image](https://user-images.githubusercontent.com/51760372/78052724-bd564100-733c-11ea-8b1b-24305ac811d2.png)

**Comment by JasonHorkles** [comment]
Well now for some reason the warning happens without any plugins, so I'll go ahead and close this for now
Sorry for any trouble
