### ISSUE TITLE
btlp messes with vanilla scoreboard team prefixes

### ISSUE THREAD

**Issue by rasputinea** [CodeCrafter47/BungeeTabListPlus#554]
I have 1 scoreboard team that displays a golden crown before a player's name, but other players who aren't even in the team get this prefix, this only happens when btlp is enabled as when I switch to spectator mode (which disables it) the prefixes go back to normal. (https://youtu.be/UnFDjDP1tkg)

**Comment by CodeCrafter47** [comment]
I've looked at the code and identified and fixed two issues with scoreboard teams. Those would only affect players not in any team, but given your problem description that seems to be the case here. Have a look at the [latest dev-build](https://ci.codecrafter47.de/job/BungeeTabListPlus/) and see if it fixes your issue.

**Comment by rasputinea** [comment]
@CodeCrafter47 thank you! this worked perfectly.
