### ISSUE TITLE
Sort By Grouping

### ISSUE THREAD

**Issue by nathanfusselman** [CodeCrafter47/BungeeTabListPlus#555]
If possible I would like to add the option to add to the sorting by allowing for grouping. I know this sounds weird but I want to allow for this to be a thing.

```
playerSets:
  all_players: all
  staff: |
      ${player vault_primary_group} == "Helper"
      and ${player vault_primary_group} == "Mod"
      and ${player vault_primary_group} == "Senior-Mod"
      and ${player vault_primary_group} == "Admin"
      and ${player vault_primary_group} == "Senior-Admin"
      and ${player vault_primary_group} == "Owner"

playerSet: all_players
playerOrder: "staff,server viewer-first,vault_prefix,name asc"
playerComponent: "${other_server_prefix}${vanish_suffix} * ${player networkmanager_tag}${player networkmanager_prefix}&7${player networkmanager_nickname}  "
```

I know this looks silly because I could make a special column but that would take up a lot of slots and there for I want staff to show up at the top regardless of the server they are on but want the subgroups still sorted in the same way.

(If this is possible already I would love a config for it)

**Comment by CodeCrafter47** [comment]
What I'd do is to give every staff player a specific permission. Let's say that permission is `tablist.staff`. Then I'd take advantage of PlaceholderAPI's `player_has_permission_<permission>` placeholder. (Unfortunately the built-in permission placeholder of BTLP cannot be used for sorting players yet).

```yaml
playerOrder: "player_has_permission_tablist.staff desc,server viewer-first,vault_prefix,name asc"
```

You might have to exchange `desc` for `asc` if staff appears at the bottom instead of the top.

**Comment by FusselFace** [comment]
Ok this works a little, may I ask if it is possible to sort by a custom placeholder?

**Comment by CodeCrafter47** [comment]
It's not. You can sort by most of the built-in placeholders, any placeholders from PlaceholderAPI and also by placeholders registered by third party plugins using BungeeTabListPlus's API.

If you try to sort players by a placeholder that cannot be used for sorting the plugin will tell you that the placeholder is unsuitable.
