### ISSUE TITLE
When using luck perms my Sr.Mod is below my helper

### ISSUE THREAD

**Issue by Flii** [CodeCrafter47/BungeeTabListPlus#561]
When using luck perms my Sr.Mod is below my helper even when my meta weight for Sr.Mod is higher

**Comment by CodeCrafter47** [comment]
Here are some tips for troubleshooting:
* Verify that the group weights are set correctly and each player is assigned the correct primary group using the commands provided by your permission plugin.
* Make sure you have installed Vault.
* Make sure you installed BungeeTabListPlus_BukkitBridge. Use `/btlp status` to verify.
* Display the primary group and the weight in the tab list, e.g. using 
    ```yaml
    playerComponent: "${player name} ${player vault_primary_group}/${player vault_primary_group_weight}"
    ```
    If the placeholder you used in `playerOrder` is not `vault_primary_group_weight` display the one you used there in the tab list.

**Comment by Flii** [comment]
THANKS
