### ISSUE TITLE
[Sponge] Console is spamming too much logs related to Luckperm (but says from BungeeTabListPlus)

### ISSUE THREAD

**Issue by farizluqman** [CodeCrafter47/BungeeTabListPlus#564]
Hi, I keep on getting this in my console and it is flooding my console every second

> 16.04 19:25:27 [Server] pool-3-thread-34/ERROR [bungeetablistplus]: Unexpected exception
> 16.04 19:25:27 [Server] INFO java.lang.ClassCastException: me.lucko.luckperms.sponge.service.reference.CachedSubjectReference cannot be cast to org.spongepowered.api.service.permission.Subject
> 16.04 19:25:27 [Server] INFO at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.Collections$2.tryAdvance(Collections.java:4719) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.data.sponge.sponge5.Sponge5.getPrimaryGroup(Sponge5.java:26) ~[Sponge5.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[AbstractDataAccess.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[AbstractDataAccess.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.data.sponge.AbstractSpongeDataAccess.get(AbstractSpongeDataAccess.java:35) ~[AbstractSpongeDataAccess.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[JoinedDataAccess.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updatePlayerData(AbstractBridge.java:369) ~[AbstractBridge.class:?]
> 16.04 19:25:27 [Server] INFO at de.codecrafter47.bungeetablistplus.bridge.AbstractBridge.updateData(AbstractBridge.java:304) ~[AbstractBridge.class:?]
> 16.04 19:25:27 [Server] INFO at codecrafter47.bungeetablistplus.spongebridge.SpongePlugin.lambda$onServerStart$3(SpongePlugin.java:146) ~[SpongePlugin.class:?]
> 16.04 19:25:27 [Server] INFO at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2838-7.2.0]
> 16.04 19:25:27 [Server] INFO at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:197) ~[SchedulerBase.class:1.12.2-2838-7.2.0]
> 16.04 19:25:27 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
> 16.04 19:25:27 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Running LuckPerms v5.0.134
and BungeeTabListPlus_SpongeBridge-3.2.0

Help is really needed.

Thank you

**Comment by CodeCrafter47** [comment]
Which version of Sponge are you running?

**Comment by farizluqman** [comment]
Hi, I'm running Sponge version 1.12.2-2838-7.2.0.

**Comment by Mirko1682** [comment]
Oh, i don't run any sponge version. I don't know what sponge is.
I'm new on github and i beginn to learn. Possibly i pushed any button?! 😬


Hope you can solve your problem. Maybe i can help you in, eeehm, 8 to 10
years?! 😅

Mirko

FarEast <notifications@github.com> schrieb am Fr., 17. Apr. 2020, 09:56:

**Comment by CodeCrafter47** [comment]
I think I have fixed the issue. Please have a look at the latest dev=build (of the SpongeBridge) and check if that solves the problem for you.

**Comment by farizluqman** [comment]
The problem is now fixed and I no longer see all the messages. 
I'd like to thank you @CodeCrafter47 for your prompt response and speed 🥇
