### ISSUE TITLE
Player heads are shown without the helm

### ISSUE THREAD

**Issue by CruxCraft** [CodeCrafter47/BungeeTabListPlus#568]
The player heads in the tablist are shown without the helm, which isn't the method of showing them on the vanilla tablist. The vanilla tablist shows it based on what each player has set in their client (by default with helm). Considering this might not be possible for this plugin, could you at least make an option to either show helms or no helm on the player heads? A lot of our player heads look a bit weird without them.

Thanks for considering this

**Comment by CodeCrafter47** [comment]
Actually what BungeeTabListPlus does is pretty close to vanilla behavior in most cases. The hat layer is only shown when you are in the same dimension and physically near each other (i.e. you can see the other player ingame). The exception to this is when the tab list is configured to use 80 slots. In that case the hat layer is never shown.

Also there already is an issue for this: #50. Unfortunately it is not to be fixed soon.
