### ISSUE TITLE
Sponge LuckPerms Weight

### ISSUE THREAD

**Issue by SeruhioX** [CodeCrafter47/BungeeTabListPlus#576]
Hello, I recently put a sponge server on my network, but I would like to request new functionality.

Currently there is this placeholder for bukkit "vault_primary_group_weight", but I can't find anything similar for sponge, on this server I am using LuckPerms just like on bukkit server.

The suggestion is to allow players to be sorted by the weight of the primary group of luckperms (not bungeecord, if not the specific server as with vault).

Cheers

**Comment by CodeCrafter47** [comment]
`vault_primary_group_weight` should work with Sponge.
