### ISSUE TITLE
BTLP formatting text issue

### ISSUE THREAD

**Issue by PlopHat** [CodeCrafter47/BungeeTabListPlus#578]
don't know if it is a bug or not, but btlp get only the last character of hex for ${player display_name}. i tried /papi parse me %player_displayname% an it returns the correct color.

Here's a post of imgur with images explaining.
https://imgur.com/a/opljkEX

**Comment by PlopHat** [comment]
it is not a problem with BTLP, it's not possible right now, nickname in tab don't get translated correctly as part of minecraft i think (tested with other tab plugins and essentials nick)

**Comment by CodeCrafter47** [comment]
Actually I think a1c163bd should have fixed this. Didn't text this myself, but if you update to the latest dev-build of BTLP it'll probably work.

**Comment by PlopHat** [comment]
Yes... and no, special formatting codes breaks tab (&n;&o;&k;&l), i'll re-open this issue if anyone has the same error.

[https://i.imgur.com/GrRT2tV.png](url)

**Comment by CodeCrafter47** [comment]
What did you put in the config to make that happen?

**Comment by PlopHat** [comment]
${player vault_prefix}${player player_displayname}
thats in tabconfig player component

**Comment by CodeCrafter47** [comment]
What are a prefix and displayname to make the issue happen?

**Comment by PlopHat** [comment]
prefix was &lDev
nick was &o&lasd
the guy with the colored word paisen only has the "4" with bold and the name got that whole thing

**Comment by CodeCrafter47** [comment]
Can you check if the latest dev-build fixes the issue?

**Comment by PlopHat** [comment]
Sadly nope, formatting text still breaks tab names
i changed the placeholder for playercomponent to "${player display_name}" but still no luck.
input:
![image](https://user-images.githubusercontent.com/41564958/86190002-281c4180-bb11-11ea-8aa6-e66b6f51e423.png)
What i see:
![image](https://user-images.githubusercontent.com/41564958/86189968-10dd5400-bb11-11ea-9850-06deaaa8a111.png)
it gets broken with text formatting (bold, italic, obfuscated, underlined, strikethrough).

Hex and color codes work fine, only text formatting gets weird
Input:
![image](https://user-images.githubusercontent.com/41564958/86190477-7251f280-bb12-11ea-9780-59329bd34b44.png)

Output:
![image](https://user-images.githubusercontent.com/41564958/86190497-7da51e00-bb12-11ea-9701-235e5357fc5b.png)

**Comment by CodeCrafter47** [comment]
I've just tested this myself and did not experience this issue. I'm fairly certain that BungeeTabListPlus does not create the broken json. Probably it's already in the display name. You could use `/papi parse %player_displayname%` to check. Also make sure CMI and Spigot are up to date. Same goes for your other plugins - but they may not be that related to this issue.

**Comment by PlopHat** [comment]
Got fixed! TSM (forgot to disable another tab plugin, sorry about that 😭)
