### ISSUE TITLE
Hello problem

### ISSUE THREAD

**Issue by Neverlookbackgrg** [CodeCrafter47/BungeeTabListPlus#58]
My tablist was running smooth for 6-10 hours and suddenly that happens
http://prntscr.com/8wcarl

**Comment by CodeCrafter47** [comment]
That basically says you need to assign more memory to BungeeCord.

**Comment by Neverlookbackgrg** [comment]
what you recommend for 40-50 players?

**Comment by CodeCrafter47** [comment]
I suggest 2G. You should also update BungeeTabListPlus to version 2.2.7. It fixes some issues in previous versions that resulted in high memory usage.

**Comment by Neverlookbackgrg** [comment]
will it change my configs etc?Create new problems?

**Comment by CodeCrafter47** [comment]
I don't think so. It fixes a bug that prevented variables in the tab list header or footer from being updated in some cases and it offers better performance. That's all that changed.
