### ISSUE TITLE
Colon after some usernames

### ISSUE THREAD

**Issue by Sylensky** [CodeCrafter47/BungeeTabListPlus#582]
Hi iam not reporting a issue i just wanted to know why and how this occurs like in the picture below.
![image](https://user-images.githubusercontent.com/57076968/87369216-43129b00-c580-11ea-830b-5fe42a15a83d.png)
I noticed that after some players a colon is displayed in the tablist and i can't find out why it do be like that.
Any explainations?
Just for references i use the latest version 3.3.0 on the bungee and the bridges on the spigot servers running 1.15.2.

**Comment by CodeCrafter47** [comment]
I think the colon appearing in this case is a bug. The plugin can sometimes add the colon if there is text with `right` alignment to create pixel precise spacing. However in this case there is not text with `right` alignment (only `center` alignment I think), so that should not happen.

**Comment by CodeCrafter47** [comment]
b4d54457413dd6862921cc2c4ed0c551e1e621f7 / 3.3.3 should fix this.
