### ISSUE TITLE
Please add hex color support to prefix displayname

### ISSUE THREAD

**Issue by wangyz1999** [CodeCrafter47/BungeeTabListPlus#583]
If the displayed name contains hex color code such as &#FF0000, the raw code will be displayed on the tablist

The proper function would be:

`net.md_5.bungee.api.ChatColor.of(colorCode)`

**Comment by CodeCrafter47** [comment]
Support for hex color codes using the `&#rrggbb` format has already been added to the latest dev-build and will be available with the next release. Using the current version you can use the `[color=#RRGGBB]` format. For prefixes shared with other plugins you can use the `&x&r&r&g&g&b&b` format.
