### ISSUE TITLE
${player ping}

### ISSUE THREAD

**Issue by wallxq** [CodeCrafter47/BungeeTabListPlus#585]
Why does ${player ping} give me a different result compared to spigot plugins or skript. Like TAB plugin or placeholders in skript.
Its problem with my connection between bungee and spigots or issue with bungeetablistplus?

**Comment by CodeCrafter47** [comment]
The ping displayed by BungeeTabListPlus is the time it takes a packet to travel from BungeeCord to the Client and back. So the time it takes the packet to travel between BungeeCord and the spigot server is not considered. Thus the ping is slightly lower.
