### ISSUE TITLE
Suggestion: Add an option without any modification to the Options of the Dynamic Size Tab List

### ISSUE THREAD

**Issue by BingYanchi** [CodeCrafter47/BungeeTabListPlus#586]
Considering some situations, it may be necessary to keep the original state, not even using ${player name}.

For example: BedwarsRel will modify the player's color and prefix in the tab, but this will conflict with BungeeTabListPlus.

The implementation is very simple. Add a type option and cancel all operations on the players in the tab.

**Comment by CodeCrafter47** [comment]
Are you looking for an option where BungeeTabListPlus only changes the header and footer, or not even that?

**Comment by BingYanchi** [comment]
> header and footer

Yes, I want to be able to use only header and footer
