### ISSUE TITLE
Outdated PlaceholderAPI wiki page

### ISSUE THREAD

**Issue by Andre601** [CodeCrafter47/BungeeTabListPlus#589]
The [PlaceholderAPI wiki page]() is a bit outdated (mainly in terms of links)

1. Point 1 links to a no longer supported wiki page. The updated and maintained one is https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
2. The parse command requires a target to test on. You can just change the example to `/papi parse me %statistic_kill_enity_CREEPER%`

**Comment by CodeCrafter47** [comment]
Thank you! Fixed this one.
