### ISSUE TITLE
Option to disable showing player head icons to prevent abuse.

### ISSUE THREAD

**Issue by MCRob2** [CodeCrafter47/BungeeTabListPlus#591]
On our survival server, someone figured out that the head icon infront of the player on the tablist will show their "hat" only when you get within player tracking range, thus making this a very effective tracking tool. 

Basically the "attacker" keep checking the tablist until the head icon of its "victim" changes as soon he gets close enough to his victim. Here you can see the two versions (2nd player on the list). This affects only players that have an additional head skin or hat.

![far](https://user-images.githubusercontent.com/42914932/93421482-c1a5f480-f8b1-11ea-98d1-d6c0141819dc.png)

![near](https://user-images.githubusercontent.com/42914932/93421483-c23e8b00-f8b1-11ea-9d46-9a110978fa2b.png)

Is there an option to either disable loading those "hats" or alternatively to not show the player head icon at all in the tablist?

**Comment by CodeCrafter47** [comment]
It is not possible to disable the head icons. However, it is possible to disable the hat overlay. There's two options
1. Players can disable the hat overlay in the client settings.
2. You can set the size of the tab list to 80 slots. In that case it will never show the hat overlay.
