### ISSUE TITLE
Cannot modify offline player's skin when using BTLP

### ISSUE THREAD

**Issue by djytw** [CodeCrafter47/BungeeTabListPlus#593]
This was originally a bungee issue, PaperMC/Waterfall#548, that bungee will rewrite and remove PlayerProfile of an offline player, even if we set a profile(skin) for the player at bukkit side.

Currently waterfall has a workaround that disables the tablist rewrite PaperMC/Waterfall@fae68b0, and that works well without BTLP(skin can be changed). But it won't work with BTLP installed.

I think (not sure) when BTLP rewrites the tablist, it somehow invokes the bungee rewrite and removes the player skin. Is there anyway to prevent this?

**Comment by CodeCrafter47** [comment]
BTLP has it's own code for handling rewrite as the code in BungeeCord suffers of a race condition. It won't rewrite the uuid of a packet if the player has already left which would lead to players leaving the server not being removed from the tab list. They have implemented a work around so this doesn't happen, but that creates another race condition where if you connect to bungee while already playing on it you will not be present on the tab list afterwards. BTLP's rewrite code is located at <https://github.com/CodeCrafter47/BungeeTabListPlus/blob/master/bungee/src/main/java/codecrafter47/bungeetablistplus/handler/RewriteLogic.java>.

I don't like the solution implemented in waterfall. If used incorrectly a config option to disable tab list rewrite can break the game (i.e. players will appear invisible on the client).

The purpose of tab list rewrite is to ensure nothing breaks if ip-forwarding is disabled. For that reason I think a better option might be to disable tab list rewrite whenever ip-forwarding it enabled. Though when making any changes to tab list rewrite one would need to consider that there might be (BungeeCord) plugins depending on this specific behavior.

**Comment by djytw** [comment]
I agree with you, it's no good to disable tablist rewrite only for the skin issue. Actually, the skin issue can be resolved by removing [this line](https://github.com/SpigotMC/BungeeCord/blob/15b514130eb861cb44ddc787aa152f73e259dbb1/proxy/src/main/java/net/md_5/bungee/tab/TabList.java#L54) (or the [corresponding line in BTLP](https://github.com/CodeCrafter47/BungeeTabListPlus/blob/dad8ac59dfeee96b9837ec64f1b65307cf067b18/bungee/src/main/java/codecrafter47/bungeetablistplus/handler/RewriteLogic.java#L86)), which discards the skin of offline player. Although I do not know the reason of discarding skins nor the risks of modifying this.

**Comment by CodeCrafter47** [comment]
I don't think removing that line will break anything. I think that would be a good way to solve the issue.
