### ISSUE TITLE
Suggestion: increase the server display name variable

### ISSUE THREAD

**Issue by BingYanchi** [CodeCrafter47/BungeeTabListPlus#595]
Currently, the `${viewer server}` variable is provided, but usually, we need a custom name to replace it.
If possible, hope to add configuration options for this variable in the corresponding tablists file.
Maybe it can be displayed as a group:
```
'Bedwars':
  - bw_1
  - bw_2
'Bedwars Lobby':
  - bw_lobby
```
If you are on the `bw_1` server, the variable will be displayed as `Bedwars`.

**Comment by CodeCrafter47** [comment]
Have a look at the following wiki page: <https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Custom-Placeholders#custom-names-for-servers---server_display_name>.
