### ISSUE TITLE
Random Alex/Steve Skins in TAB

### ISSUE THREAD

**Issue by InfinityAspire** [CodeCrafter47/BungeeTabListPlus#6]
After updating to the latest the head icons next to players and empty slots no longer show the skin specified in the config, it shows random Steve and Alex heads.

I see this in my tablist. http://prntscr.com/5u5c1t
Using latest Spigot compiled with BuildTools#24 and latest version of this plugin 2.0#2

**Comment by CodeCrafter47** [comment]
Can you provide your default.yml?

**Comment by InfinityAspire** [comment]
http://pastebin.com/wvvBaysS
My default.yml

**Comment by CodeCrafter47** [comment]
That one works.

**Comment by InfinityAspire** [comment]
Well apparently not for me. There's also someone else having this issue on the Spigot discussion page of this plugin

**Comment by CodeCrafter47** [comment]
Any other files in the tabLists directory?

**Comment by InfinityAspire** [comment]
None at all

**Comment by CodeCrafter47** [comment]
Are there any errors in the log file? Maybe related to #7 ?

**Comment by InfinityAspire** [comment]
No sorry, nothing related to that issue that I can see. Sorry about lateness

**Comment by InfinityAspire** [comment]
The latest version seems to develop this issue. e.g. After a fresh restart it'll function fine but after a while it turns to Alex and Steve skins again

**Comment by CodeCrafter47** [comment]
Made a [new build](http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/lastBuild/) for you. Can you try it?

**Comment by InfinityAspire** [comment]
I'll test it now and get back to you. I also created another issue #10 which may be related but I'm unsure

**Comment by InfinityAspire** [comment]
No success, now it's just Alex and Steve skins directly after restart as well

**Comment by InfinityAspire** [comment]
I restarted once again and the Alex/Steve skin issue is fixed. I'll keep you posted

**Comment by InfinityAspire** [comment]
The issue is back. Alex and Steve skins directly after restart again.

**Comment by CodeCrafter47** [comment]
Is it gone?
