### ISSUE TITLE
Is it possible to make rainbow animation bold? QUESTION

### ISSUE THREAD

**Issue by Invy55** [CodeCrafter47/BungeeTabListPlus#608]
QUESTION
I've this custom placeholder
```
my_rainbow:
    !color_animation
    colors: ["&4", "&c", "&6", "&e", "&2", "&a", "&b", "&3", "&1", "&9", "&d", "&5"]
```
Is there any way to make that text bold too? I tried to put &l after the colors in the colors list but it doesn't work this way.

**Comment by CodeCrafter47** [comment]
It is not possible to make rainbow text bold.

**Comment by Invy55** [comment]
> It is not possible to make rainbow text bold.

Even without some other things it's possible to put the strings of colors (&a,&e...) between each leatter?
