### ISSUE TITLE
something is wrong with gradle not getting the depends 

### ISSUE THREAD

**Issue by ham1255** [CodeCrafter47/BungeeTabListPlus#610]
![image](https://user-images.githubusercontent.com/34905970/102640446-e7be8780-4173-11eb-88fd-afa34c0c65b4.png)

**Comment by CodeCrafter47** [comment]
Make sure you cloned the submodules.Use the commands in the readme to cloned and build the plugin.

**Comment by ham1255** [comment]
i did it seems not working

**Comment by ham1255** [comment]
```
> Configure project :fabric-bridge-1.16.3
Fabric Loom: 0.4.33 Build(jenkins #33)
:setting up loom dependencies
:setting up mappings (yarn 1.16.3+build.11)
Configuring compiler arguments for Java

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':BungeeTabListPlus:shadowJar'.
> Could not resolve all dependencies for configuration ':BungeeTabListPlus:runtimeClasspath'.
   > Could not find de.codecrafter47.taboverlay:taboverlaycommon-config:1.0-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://nexus.codecrafter47.dyndns.eu/content/repositories/public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.codemc.org/repository/maven-public/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.md-5.net/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://repo.spongepowered.org/maven/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/de/codecrafter47/taboverlay/taboverlaycommon-config/1.0-SNAPSHOT/taboverlaycommon-config-1.0-SNAPSHOT.pom
     Required by:
         project :BungeeTabListPlus > project :bungee-plugin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 16s
```

**Comment by CodeCrafter47** [comment]
If you want to build the dev branch make sure to check out the dev branch of the submodules.

**Comment by ham1255** [comment]
followed the readme.md on building the plugin both dev branch or the master branch none of them working

**Comment by CodeCrafter47** [comment]
I just had a closer look at it. If you had the following error, then it is fixed now. Otherwise please post your error.
```
$ ./gradlew shadowJar
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/minecraft/BungeeTabListPlus/build.gradle' line: 76

* What went wrong:
A problem occurred evaluating root project 'BungeeTabListPlus-parent'.
> Could not get unknown property 'mavenUser' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by ham1255** [comment]
hi sorry for late response here is the error that i get when i got the fix
***
$ ./gradlew shadowJar

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':BungeeTabListPlus_SpongeBridge:shadowJar'.
> Could not resolve all dependencies for configuration ':BungeeTabListPlus_SpongeBridge:runtimeClasspath'.
   > Could not resolve project :bungeetablistplus-api-sponge.
     Required by:
         project :BungeeTabListPlus_SpongeBridge
      > Cannot choose between the following variants of project :bungeetablistplus-api-sponge:
          - javadocElements
          - sourcesElements
        All of them match the consumer attributes:
          - Variant 'javadocElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-api-sponge:3.4.3-SNAPSHOT:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'javadoc' but wasn't required.
                  - Required org.gradle.jvm.version '8' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'sourcesElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-api-sponge:3.4.3-SNAPSHOT:
              - Unmatched attributes:
                  - Found org.gradle.category 'documentation' but wasn't required.
                  - Found org.gradle.docstype 'sources' but wasn't required.
                  - Required org.gradle.jvm.version '8' but no value provided.
                  - Required org.gradle.libraryelements 'jar' but no value provided.
              - Compatible attributes:
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
   > Could not resolve project :bungeetablistplus-common.
     Required by:
         project :BungeeTabListPlus_SpongeBridge
      > Unable to find a matching variant of project :bungeetablistplus-common:
          - Variant 'apiElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-common:3.4.3-SNAPSHOT:
              - Incompatible attributes:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
          - Variant 'runtimeElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-common:3.4.3-SNAPSHOT:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
   > Could not resolve project :bungeetablistplus-bridge.
     Required by:
         project :BungeeTabListPlus_SpongeBridge
      > Unable to find a matching variant of project :bungeetablistplus-bridge:
          - Variant 'apiElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-bridge:3.4.3-SNAPSHOT:
              - Incompatible attributes:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
                  - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
          - Variant 'runtimeElements' capability codecrafter47.bungeetablistplus:bungeetablistplus-bridge:3.4.3-SNAPSHOT:
              - Incompatible attribute:
                  - Required org.gradle.jvm.version '8' and found incompatible value '11'.
              - Other attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Required org.gradle.dependency.bundling 'external' and found compatible value 'external'.
                  - Required org.gradle.libraryelements 'jar' and found compatible value 'jar'.
                  - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
***

**Comment by CodeCrafter47** [comment]
I have seen this error message before. It can occur when building a specific module instead of the parent project. Never seen it when building the parent project.
