### ISSUE TITLE
PlaceholderAPI placeholder breaks tablist

### ISSUE THREAD

**Issue by TheRealKraken** [CodeCrafter47/BungeeTabListPlus#616]
I'm trying to use a placeholderAPI placeholder but, whenever I try to, the entire tablist doesn't show, it just goes back to vanilla tablist.

```
footer:
- |-
  &f&lClearLag Timer: ${player clearlagtimer_seconds}
- |-
  &6&lClearLag Timer: ${player clearlagtimer_seconds}
footerAnimationUpdateInterval: 0.5
```

I have made sure it Is a valid placeholder with the papi command using the original placeholder, which is `%clearlagtimer_seconds%`. I'm not sure if I'm doing something wrong or not? It just seems that this placeholder breaks the entire plugin for some reason.

**Comment by Andre601** [comment]
I assume you figured out what the issue was?
