### ISSUE TITLE
AFKLast does not work.

### ISSUE THREAD

**Issue by kotarobo** [CodeCrafter47/BungeeTabListPlus#617]
AFKLast does not work.
I am using CMI &Luckperm.

playerOrder: "AFKLast,vault_primary_group_weight desc,alphabetically"

[https://i.gyazo.com/dc1dab7eab346b9035b168fb7dafd293.png](url)

**Comment by CodeCrafter47** [comment]
AFKLast works with Essentials only.

**Comment by kotarobo** [comment]
ok! thanks.
