### ISSUE TITLE
Wiki fix: under serverSeparator it calls it serverFooter?

### ISSUE THREAD

**Issue by jasikpark** [CodeCrafter47/BungeeTabListPlus#618]
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Components#serverseparator
<img width="906" alt="Screen Shot 2021-02-05 at 5 40 46 PM" src="https://user-images.githubusercontent.com/10626596/107100253-65e4f500-67d9-11eb-8f77-dc61b7322d03.png">

**Comment by Andre601** [comment]
Corrections can be PRed to the [TabOverlayWiki Repository](https://github.com/CodeCrafter47/TabOverlayWiki) as this probably is also the case for the AdvancedTabOverlay wiki.

**Comment by Andre601** [comment]
Actually... Looking at the source is this only visible in the BTLP wiki.
I quickly PRed a fix that only awaits CodeCrafter's merge.
