### ISSUE TITLE
Compatibility with Nucleus 2 AFKService

### ISSUE THREAD

**Issue by Mike5357** [CodeCrafter47/BungeeTabListPlus#623]
Nucleus 2 has changed the AFKService functionality, and as a result any reference to the AFK tag from BTLP causes continuous console spam until removed, reloaded, and all players have disconnected: https://pastebin.com/t3aZ3cgH

Spongeforge 1.12.2-2838-7.3.1
Nucleus 2.3.2
BTLP Sponge Bridge 3.4.3

**Comment by embeddedt** [comment]
Were you able to find a workaround for this issue? I'll probably wind up patching the bridge myself to use the newer Nucleus API; just wanted to check that the work hasn't been done already.

**Comment by CodeCrafter47** [comment]
I haven't yet looked at this. Feel free to go ahead.

**Comment by embeddedt** [comment]
@CodeCrafter47 I've opened https://github.com/CodeCrafter47/minecraft-data-api/pull/4.
