### ISSUE TITLE
Hex Colors show as white on pre-1.16 versions

### ISSUE THREAD

**Issue by Mike5357** [CodeCrafter47/BungeeTabListPlus#624]
When viewing a tab list which uses Hex codes on a pre-1.16 client (using ViaBackwards), the tab list shows up entirely white.

1.12:
![image](https://user-images.githubusercontent.com/12630858/109256290-b68db380-77c3-11eb-9967-c283a70a385d.png)
1.16: 
![image](https://user-images.githubusercontent.com/12630858/109256058-3404f400-77c3-11eb-80d7-d48192583154.png)

I'd like to see functionality added similar to how some other plugins are currently able to translate hex colors to their closest legacy color code:

1.16: 
![image](https://user-images.githubusercontent.com/12630858/109256577-3ddb2700-77c4-11eb-95ac-0c779cc6feaa.png)
1.12: 
![image](https://user-images.githubusercontent.com/12630858/109256500-1c7a3b00-77c4-11eb-991a-a8aa3aaabfe0.png)

**Comment by Andre601** [comment]
I think that is more a ViaBackwards thing

**Comment by Mike5357** [comment]
Got it resolved by switching Via over to bungee instead of just on the server (duh, makes sense.)

Thanks!

**Comment by Andre601** [comment]
Don't forget to close this issue then :)
