### ISSUE TITLE
Placeholder session_duration_minutes formatting

### ISSUE THREAD

**Issue by JeffHD** [CodeCrafter47/BungeeTabListPlus#629]
Hi,

in my config i have : {text: "&7Online-Zeit&r: &6${viewer session_duration_hours}:${viewer session_duration_minutes 2}", ping: 0}
but ingame it displays :   Online-Zeit: 0: 1      until i am 10 minutes ingame : Online-Zeit: 0:10
Now how do i get the placeholder to show as 0:01 and not 0: 1

**Comment by CodeCrafter47** [comment]
Try `${viewer session_duration_minutes 02}`.

**Comment by JeffHD** [comment]
Still shows as 0: 0

**Comment by CodeCrafter47** [comment]
I have investigated the issue and found it to be a bug in the plugin. I fixed the bug (https://github.com/CodeCrafter47/TabOverlayCommon/commit/5f167afcdcc6795f9fae96c087079ff84809827a). The fix is available in the latest dev-build (https://ci.codecrafter47.de/job/BungeeTabListPlus/).
