### ISSUE TITLE
Missing maven artifact

### ISSUE THREAD

**Issue by Kamilkime** [CodeCrafter47/BungeeTabListPlus#633]
The [maven 'tutorial'](https://github.com/CodeCrafter47/BungeeTabListPlus/#maven) in the project readme says to add artifacts of version `3.4.4-SNAPSHOT`, but no such artifacts exist in the maven repo. Readme should be changed to `3.5.0-SNAPSHOT`

**Comment by iFlyinq** [comment]
Request a PR.
