### ISSUE TITLE
BTLP (Bungee) kicks players with error when using latest ViaVersion for 1.17

### ISSUE THREAD

**Issue by JustEli** [CodeCrafter47/BungeeTabListPlus#640]
When a player joins a proxy-server (Waterfall, v431) with BTLP and latest ViaVersion (supporting 1.17), the player gets immediately kicked from the proxy with the following disconnection message:
![image](https://user-images.githubusercontent.com/8517465/121223926-53162600-c888-11eb-9899-20472e2273e2.png)

The authors of ViaVersion say the following:
![image](https://user-images.githubusercontent.com/8517465/121224004-688b5000-c888-11eb-9d64-6791b28e6fb4.png)
![image](https://user-images.githubusercontent.com/8517465/121224498-e94a4c00-c888-11eb-82bf-6c62e8c3ffdd.png)

Many people agree in the ViaVersion Discord server that disabling BTLP fixed the issue.
Edit: there are no errors in console or client output log.

**Comment by Andre601** [comment]
This is to be expected considering BTLP doesn't support 1.17 yet.

We need to wait for BungeeCord and other sources to update first before we can tackle issues regarding the plugin...
Also, using ViaVersion or other plugins which allow never versions on older servers doesn't really give a clear proof that BTLP is at fault here.

Remember that MC 1.17 came out **today** so new updates may take a while.

**Comment by JustEli** [comment]
Ok, I also wanted to append this to it:
![image](https://user-images.githubusercontent.com/8517465/121233979-83af8d00-c893-11eb-8001-ccc3b6028094.png)

**Comment by CodeCrafter47** [comment]
#641
