### ISSUE TITLE
1.17 client support

### ISSUE THREAD

**Issue by KennyTV** [CodeCrafter47/BungeeTabListPlus#641]
(**This includes the actual client error and an assumption of where it originates, so it's not just a "1.17 doesn't work" issue**)
Given this was drowned out in messages pretty much immediately on the Discord, I'm opening a small issue instead.

People running ViaVersion on Bungee/Waterfall to support 1.17 clients encounter a client error, reproducible with the BTLP default config. It's about (empty?) display names in the player info packet, see this Fabric client error https://paste.gg/p/anonymous/99074e9b1f1e4ea8938f33f059cde7c1 (Fabric was used to actually print out the error in packet decoding and for you to have the intermediary names you can throw at the Yarn/Moj mapping bots).

~~This obviously wasn't an issue before, but I *assume* the same will occur on 1.17 backend servers once they are available in the Bungee environment (given Via doesn't actually do any component transformation in 1.16->1.17 or touched the player info at all), so I wanted to give you a small heads-up about it... if not, you can ignore me, but I'm pretty sure it's due to a change in client serialization.~~ 👻

**Comment by Andre601** [comment]
Perhaps this is more about [CodeCrafter47/minecraft-data-api](https://github.com/CodeCrafter47/minecraft-data-api) which is used in BTLP?
Not sure, but would be my guess here, as I doubt anything specific in BTLP causes this.
Another culprit could be [CodeCrafter47/TabOverlayCommon](https://github.com/CodeCrafter47/TabOverlayCommon) which contains the code mostly responsible for the tab list (custom slots?)

**Comment by CodeCrafter47** [comment]
I appreciate the input. I just did some testing with 1.17 myself, but I did not encounter any errors. I used the latest BungeeCord (`git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:633ff1c:1578`) and Spigot 1.16.5. I've tested with ViaVersion on Spigot and I've also tested installing it on the proxy. My guess is that the issue has been fixed somewhere else since you posted it here, though it could also be that there is some difference between your setup and mine.

**Comment by TNTUP** [comment]
Can't reproduce on BungeeCord (I don't use Waterfall) so no issues with 1.17 clients. Gotten no reports since yesterday.

**Comment by Peda1996** [comment]
I can confirm this issue with Waterfall 1.17

**Comment by KennyTV** [comment]
Having tested a few setups, it doesn't occur with Via on the backend or clientside, so it does seem Via Bungee specific (which is even more confusing). I will have to look into it a bit more, sorry for all the fuzz caused at your end

**Comment by KennyTV** [comment]
Yeah, err, the issue is as simple as it is dumb, I'll create a pr for it.
