### ISSUE TITLE
Multi change packet?

### ISSUE THREAD

**Issue by andreasdc** [CodeCrafter47/BungeeTabListPlus#644]
Do you have some kind of multi change packet to change multiple fields in just 1 packet or you update every field with 1 packet? With multiple packet it would be more efficient, but I don't think if that's possible. 🥇

**Comment by CodeCrafter47** [comment]
A single PlayerListInfo packet can change multiple entries. BungeeTabListPlus makes use of this.

**Comment by andreasdc** [comment]
> A single PlayerListInfo packet can change multiple entries. BungeeTabListPlus makes use of this.

Perferct <3 keep up the good work :)
