### ISSUE TITLE
tablist prefixes

### ISSUE THREAD

**Issue by Diixxon** [CodeCrafter47/BungeeTabListPlus#645]
I'm looking for a configuration for what I show in the attached image. Currently I'm using LuckPerms and LuckPermsChat and I need to synchronize everything so that every time I add someone to a group, it's fully configured as shown in the image.

![prefix](https://user-images.githubusercontent.com/78665087/126562453-7ab1fcd8-1fab-4457-973e-a5c8082d175e.png)

Thanks for the help :)

**Comment by Andre601** [comment]
Take a look at this page:
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Placeholders#luckperms

**Comment by Diixxon** [comment]
I have tried all the possible combinations of that page, but none have worked for me. The only thing I have achieved is to put the same prefix of the rank in the chat and in the tablist, but I need that the rank doesn't appear in the tablist, only the color

**Comment by Andre601** [comment]
Create a custom placeholder in this case. The wiki even has an example of "Custom prefixes" which you could adjust to just returning the colour instead:
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Custom-Placeholders#creating-custom-prefixes---custom_prefix

**Comment by Diixxon** [comment]
I attach some images so you can see if I'm doing it well or not...

![prefix](https://user-images.githubusercontent.com/78665087/126568319-32aeb1c4-ffc9-4fd7-81ad-33f9fc2a54cf.png)

![tablist](https://user-images.githubusercontent.com/78665087/126568333-80d16096-ae47-4965-9d98-95fe2b14d316.png)

**Comment by Andre601** [comment]
Make sure you have the Bridge plugin installed on your server to use the `vault_primary_group` placeholder.
If you use LuckPerms on your proxy and have it connected to the same database, consider using `luckpermsbungee_primary_group` instead.

**Comment by Diixxon** [comment]
It happens exactly the same. I have the administrator rank, but nothing is shown in the tablist

![tablist](https://user-images.githubusercontent.com/78665087/126569341-6201d329-d5dc-43e9-9257-857659876a04.png)

**Comment by Andre601** [comment]
Then double check that you use the right naming, including capitalization.

**Comment by Diixxon** [comment]
I have changed the variable as you have told me but nothing still appears. I have the Bridge installed and everything connected by mysql database since I have several servers and I need everything to be synchronized

![prefix](https://user-images.githubusercontent.com/78665087/126569550-7c319377-7342-40f6-8f6c-15c68f229346.png)

**Comment by Andre601** [comment]
You use `${player vault_prefix}` where you want to use `${custom_prefix player}` instead (Line 65)

**Comment by Diixxon** [comment]
Shit man! You are right bro, it was that variable...

**Comment by Diixxon** [comment]
But now I get the color of the default rank, when I have myself as administrator. Do you know why that could be?

**Comment by Diixxon** [comment]
Could it be because I'm using the LuckPermsBungee and the LuckPerms?

**Comment by Andre601** [comment]
I told you before to double-check that the names actually match

**Comment by Diixxon** [comment]
They match correctly, both those of the bunge console (first image) and those of the server console (second photo)

![bungeeconsole](https://user-images.githubusercontent.com/78665087/126570535-20c200ef-828c-4e91-8c69-1bdda3b8d464.png)

![serverconsole](https://user-images.githubusercontent.com/78665087/126570544-a73aefea-323b-4cb1-91fe-2502b6c8d260.png)

**Comment by Andre601** [comment]
Then I'm out of ideas and have to wait for CodeCrafter to help

**Comment by Diixxon** [comment]
ok np dude! Anyway, thank you very much for your help.

**Comment by CodeCrafter47** [comment]
I recommend you display your rank on the tab list, so you can see what the plugin thinks your rank is.

**Comment by Diixxon** [comment]
I have already solved! The thing is, I was using the Waterfall Proxy and it turns out there are some incompatibilities with the LuckPerms and the LuckPermsBungee. So I have replaced it with the BungeeCord and it has already worked perfectly.

**Comment by Andre601** [comment]
That sounds like something you should report to waterfall usually Bungee plugins are 99% compatible with it. So if they (accidentally) break stuff through their modifications should you report this.
