### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by sleepinghaise** [CodeCrafter47/BungeeTabListPlus#646]
Hey! 

I installed BungeeTabListPlus on my Bungeecord Server. Everything is working exept one small thing. On the bottom left is  a clock  for the Time. I found the config and where to change it but it says the wrong time.

I'm from germany and when i put **"time_zone: germany:BERLIN"**. Sadly that time is 2 hours earlier because its not UTC +2. Anyone knows how i can fix that?

Thanks for your time :)!

**Comment by Andre601** [comment]
Your format is wrong. It should be a tz database timezone in the format `continent/city` or a custom ID in the format `GMT<offset>`
So either `Europe/Berlin` or `GMT+1`/`GMT+2`

This is also explained within the wiki, so I don't see where you got this format from.
https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Global-Configuration#time-zone-europeberlin

**Comment by sleepinghaise** [comment]
Thank you very much! It worked. I didnt found the Side on the wiki so i didnt really know what to put there. Next time i'll search a bit better!
