### ISSUE TITLE
Console spam "connecting to Mojang servers" error code 403 and 400

### ISSUE THREAD

**Issue by donvdp** [CodeCrafter47/BungeeTabListPlus#648]
BungeeTabListPlus is causing my console to get spammend like you wont believe.

When bungee starts BungeeTabListPlus reports back with error 403 and error 400. See screenshots below. after a while and sometimes directly from the start of bungee the console starts to get spammend like shown at screenshot below. This causes my bungeecord server to get super sized log file and also causes the memory usage of the server to increase.

Information below on the used waterfall, papermc and BTLP plugin versions.

![image](https://user-images.githubusercontent.com/10013800/127744462-5db6d347-24ff-4eee-8229-16e010a7c118.png)

SPAM ERROR 403 messages
![image](https://user-images.githubusercontent.com/10013800/127744861-e2edceb1-3009-4850-9928-592de2868180.png)

SPAM ERROR 400 messages
![image](https://user-images.githubusercontent.com/10013800/127744954-9eae3f0d-c7fb-4fa2-ba03-0753b9fdddf2.png)

Log files are getting enormous
![image](https://user-images.githubusercontent.com/10013800/127744526-ab3b5dcf-a540-47f3-bb26-5274214b3c48.png)

Currently running
server: Bungeecord: Waterfall 1.16-R0.5
server: PaperMC: 1.16.5 build# 873
Bungee BTLP plugin: 3.5.0 build#1105 (most recent build as of today)
PaperMC BTLP pluigin: bukkit_bridge build#1105 (most recent build as of today)

This behaviour has also been reported since 23-07-2021 on same waterfall/papermc + BTLP version 3.4.4.

**Comment by donvdp** [comment]
anyone ?

**Comment by Andre601** [comment]
403 means "Forbidden" meaning BTLP tries to access an API path it does not have permission for (Maybe requires authorization?)
400 on the other hand means "Bad Request" and could mean that something in BTLP's request is malformed or otherwise wrong/invalid.

Could you share your tab list configuration please? My guess is that you have a typo or similar somewhere which causes BTLP to send wrong/invalid information here.

**Comment by donvdp** [comment]
Config file: https://pastebin.com/jSixnXcx
tablist: https://pastebin.com/5z8p8F1C

**Comment by donvdp** [comment]
i had a fakeplayer with color code in my config. my bad.
