### ISSUE TITLE
Permissions Ranks

### ISSUE THREAD

**Issue by mariolars** [CodeCrafter47/BungeeTabListPlus#65]
Hello, 
the problem is when players join to the same proxy they can see each other prefix but if one of them will join to other bungeecord instance he/she won't see other players ranks.

**Comment by mariolars** [comment]
I forgot to mention that bungee instances are connected with each other with RedisBungee

**Comment by CodeCrafter47** [comment]
fix with 6c56c624dde8376b2ff8cc6a2682d576b4fe8533
