### ISSUE TITLE
Rank/Balance/Prefix Not Show on other Server

### ISSUE THREAD

**Issue by SuryaRajgor** [CodeCrafter47/BungeeTabListPlus#667]
hello I install and set prefix and economy and its work fine on **lobby**  But in other server like survival no info show in tab list

![02tab](https://user-images.githubusercontent.com/9131487/147417196-932e6469-a9aa-420b-bf20-1223f6c3583c.png)
![01tab](https://user-images.githubusercontent.com/9131487/147417199-c13a9f09-c082-446a-9c22-18d1090cacf1.png)
 
![image](https://user-images.githubusercontent.com/9131487/147417227-9349d0b5-7bc7-4bd5-b75d-c08ccec461a7.png)

**Comment by Andre601** [comment]
Please make sure you have the bukkit bridge plugin installed + Vault on the server, so that BTLP can actually get the required info.

Additionally should you always share your tab list file, so that we can see what a possible cause is... Finding that out through screenshots is a bit difficult :/

**Comment by SuryaRajgor** [comment]
Config : https://pastebin.com/WgA55JDP
default.yml : https://pastebin.com/RSnrLjyh
