### ISSUE TITLE
Tablist giving * ERROR *

### ISSUE THREAD

**Issue by Pierates** [CodeCrafter47/BungeeTabListPlus#67]
I've been having errors on my server with bungee, im currently using the test server. On the normal server it works fine (well the older version) but when i try it on my test server I get this:
http://puu.sh/lTSRp.png

**Comment by CodeCrafter47** [comment]
Maximum tab_size for 1.8 is 80.

**Comment by Pierates** [comment]
Dumb question, where do I change that? I Can't find it in my config whatsoever.

**Comment by Pierates** [comment]
Oh haha, nevermind had to go to the bungeecord config.
