### ISSUE TITLE
can't join server

### ISSUE THREAD

**Issue by lostINParadies** [CodeCrafter47/BungeeTabListPlus#672]
Hey I got this error when I try to join my Bungee on 1.18.2 Any solution? https://prnt.sc/UGMZUxGU2J8W

Using the last Dev-Build https://ci.codecrafter47.de/job/BungeeTabListPlus/1110/

I don't get any error messages in the log. Plugin load normaly

**Comment by MackenzieMolloy** [comment]
I get the same issue here, I've tried both the latest SpigotMC release and the snapshot version from April 4th. (#1110?)

Lobby Server Version
`[21:12:37 INFO]: Checking version, please wait...
[21:12:37 INFO]: This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)
You are running the latest version`

Bungeecord (Waterfall) Version
`[21:12:37 INFO]: Checking version, please wait...
[21:12:37 INFO]: This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)
You are running the latest version`

**Comment by MackenzieMolloy** [comment]
Hey @lostINParadies,

Are you running ViaVersion? and If so, what version of ViaVersion are you running? (don't say latest)

**Comment by lostINParadies** [comment]
@MackenzieMolloy 

haha I think so. Not Home Right now

**Comment by MackenzieMolloy** [comment]
Please let me know what version of ViaVersion you are running.

**Comment by lostINParadies** [comment]
ViaVersion 4.1.0 Bungee + Paper

**Comment by lostINParadies** [comment]
@MackenzieMolloy You are right. It seems to be a bug with Viaversion. Without Viaversion it works

**Comment by lostINParadies** [comment]
@MackenzieMolloy Use latest dev-Build from  ViaVersion. it works

**Comment by MackenzieMolloy** [comment]
> @MackenzieMolloy Use latest dev-Build from ViaVersion. it works

Was about to say- that updating to even the latest SpigotMC release fixed the issue for me. I too was running version 4.1.0.
