### ISSUE TITLE
BungeeTabListPlus breaks with the latest waterfall build for 1.19. (#490)

### ISSUE THREAD

**Issue by Erlpil** [CodeCrafter47/BungeeTabListPlus#677]
Hello!

This plugin breaks with the latest Waterfall build for 1.19. (#490, https://api.papermc.io/v2/projects/waterfall/versions/1.19/builds/490/downloads/waterfall-1.19-490.jar)

Stacktraces: https://pastebin.com/raw/KVna28zc

This plugin has worked like a charm over previous upgrades so I guess I was a bit bold when upgrading this time.
A revert back to an older waterfall build solved the issue, but 1.19 clients can not connect on this old build.
Players where not able to connect when BungeeTablistPlus was installed on the latest Waterfall build.

**Comment by eleksploded** [comment]
I have a custom build using my PR [here](https://www.dropbox.com/s/f2vbggdtc7f90dl/BungeeTabListPlus-3.6.0-SNAPSHOT.jar?dl=1) if you'd like. keep In mind custom build and all when asking for support tho

**Comment by Gyztor** [comment]
> I have a custom build using my PR [here](https://www.dropbox.com/s/f2vbggdtc7f90dl/BungeeTabListPlus-3.6.0-SNAPSHOT.jar?dl=1) if you'd like. keep In mind custom build and all when asking for support tho

thank you for making an update as soon as you did! should at least allow my bungee stuff to limp along for now without being obvious to players stuff is borked a little

**Comment by Gyztor** [comment]
Current build by eleksploded as of posting this
Bungee: https://jenkins.havensedgemc.com/job/BungeeTabListPlus/lastSuccessfulBuild/artifact/bootstrap-bungee/build/libs/BungeeTabListPlus-3.6.0-SNAPSHOT.jar
Bukkit Bridge: https://jenkins.havensedgemc.com/job/BungeeTabListPlus/lastSuccessfulBuild/artifact/bootstrap-bukkit/build/libs/BungeeTabListPlus_BukkitBridge-3.6.0-SNAPSHOT.jar
these should work until its offically updated than i will switch it to build the official version for anyone who wants to use my build server for BTLP

**Comment by andrewkm** [comment]
Happening here as well.
