### ISSUE TITLE
Arrows Not Working

### ISSUE THREAD

**Issue by EazyFTW** [CodeCrafter47/BungeeTabListPlus#68]
The head arrows and question marks are not working, but the player heads are

Console Part:
15.12 16:35:12 [Server] WARNING can't fetch skin for 'MHF_Question', is neither a name nor an uuid
15.12 16:35:12 [Server] INFO >
15.12 16:35:12 [Server] WARNING Hit mojang rate limits while fetching uuid for MHF_Question.
15.12 16:35:12 [Server] INFO >
15.12 16:35:12 [Server] WARNING can't fetch skin for 'MHF_ArrowRight', is neither a name nor an uuid
15.12 16:35:12 [Server] INFO >
15.12 16:35:12 [Server] WARNING Hit mojang rate limits while fetching uuid for MHF_ArrowRight.

**Comment by CodeCrafter47** [comment]
That happens if you restart the server too often (multiple times within 2 minutes). The plugin will download the skins again in 5 minutes and the issue will fix itself.

**Comment by EazyFTW** [comment]
It didn`t fix itself
