### ISSUE TITLE
Failed to acquire data DataKey (Detailed report)

### ISSUE THREAD

**Issue by JamesMCL44** [CodeCrafter47/BungeeTabListPlus#681]
BungeeCord version: BungeeCord dev build version 1644
BungeeTabListPlus version: 3.4.2, 3.4.4, 3.5.0
Server Jar version: paper-1.12.2-1618, paper-1.18.1-187, spigot-1.19

Frontend: No tabled content shown, only header and footer, in tablist.
Error stacktrace: [https://pastebin.com/6F0JkTvk](https://pastebin.com/6F0JkTvk)

Further info:
Before updating to latest BungeeCord build version 1644 (supports 1.19), the plugin works no problem (with ver. 3.5.0).
Further tried downgrade to BungeeCord build version 1636, the plugin works no problem but does not support MC1.19.

Related bug report I believe: #679 

If you need further info, please contact me at Discord  JamesMCL44#871

**Comment by Andre601** [comment]
Did you try the latest dev build of BTLP?
It adds 1.19 support.

**Comment by JamesMCL44** [comment]
@Andre601 Many thanks for your suggestion. I have replaced with dev build and works fine now.

This is therefore considered resolved.
