### ISSUE TITLE
3.5.1 java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by broken1arrow** [CodeCrafter47/BungeeTabListPlus#683]
I get this error on latest. Don´t know if you drop compatibility with older mine craft versions.

https://pastebin.com/C3Bgzedr

**Comment by Andre601** [comment]
Please read the Spigot page and/or README.md next time:

> BungeeTabListPlus is a tab list plugin for **BungeeCord**

This plugin is not meant to be used on a single Spigot Server. For that purpose should you use [AdvancedTabOverlay](https://www.spigotmc.org/resources/advancedtaboverlay.78905/) instead.

**Comment by broken1arrow** [comment]
> > Please read the Spigot page and/or README.md next time:
> > > BungeeTabListPlus is a tab list plugin for **BungeeCord**
> > 
> > 
> > This plugin is not meant to be used on a single Spigot Server. For that purpose should you use [AdvancedTabOverlay](https://www.spigotmc.org/resources/advancedtaboverlay.78905/) instead.
> 
> I know what it is, but he have change the usage then in later versions. I mean before you needed 1 plugin on bungee and 1 plugin on the server.

only of this plugin is named so you add it on bungee and other on server.

**Comment by Andre601** [comment]
You probably talk about the [Bukkit Bridge](https://ci.codecrafter47.de/job/BungeeTabListPlus/) which is by default named `BungeeTabListPlus_BukkitBridge_<version>.jar`

Your error mentions `BungeeTabListPlus.jar` on a Spigot server, so you most likely just installed the wrong plugin there.
This is not a BTLP issue for sure.

**Comment by broken1arrow** [comment]
I can also have mixed this two plugins when install it and pick wrong one on the server (was not yesterday I update this plugin).

**Comment by broken1arrow** [comment]
> You probably talk about the [Bukkit Bridge](https://ci.codecrafter47.de/job/BungeeTabListPlus/) which is by default named `BungeeTabListPlus_BukkitBridge_<version>.jar`
> 
> Your error mentions `BungeeTabListPlus.jar` on a Spigot server, so you most likely just installed the wrong plugin there. This is not a BTLP issue for sure.

yeah I think I made that error.

**Comment by broken1arrow** [comment]
> You probably talk about the [Bukkit Bridge](https://ci.codecrafter47.de/job/BungeeTabListPlus/) which is by default named `BungeeTabListPlus_BukkitBridge_<version>.jar`
> 
> Your error mentions `BungeeTabListPlus.jar` on a Spigot server, so you most likely just installed the wrong plugin there. This is not a BTLP issue for sure.

You can close this issue. I mix up the jars and put wrong one on the server.

**Comment by Andre601** [comment]
You can close it yourself as the author. I do not have the permissions to do this
