### ISSUE TITLE
1.19.1 player avatars and usernames don't always match.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#690]
Paper 1.19.1 Build 96
BungeeTabListPlus 3.6.0 Build 1121

**Video**: https://youtu.be/xV5zt2rZm3g
Notice in the video when switching servers, players avatars get mis-matched. Sometimes all become default.
Take note of the player name andrewkm in the top left corner of tab as well. Near the end of the video you will see the avatar switch with a player named ClarinetPhoenix.

More information and possible theories can be found here: https://ecocitycraft.com/forum/threads/tab-menu-mismatch.218034/
Possibly something to do with the social interactions page and player reporting once players are offline.

"I have a theory what might be happening to tab and the bot. My theory is the social interactions page keeps players that leave the server on the list to allow other players to report them if they go offline. Since the bot is essentially the whole social interactions page, it's messing up with cached players that have logged off." **Video**: https://www.youtube.com/watch?v=Xbsi9gl0M48

Config: https://pastebin.com/UFN6vMTT
Configs from video (Main and MainNorth servers):
Main: https://pastebin.com/qzYrp07t
MainNorth: https://pastebin.com/mXwx1D1N

If there's any other information I can provide to help track this down let me know.

**Comment by CodeCrafter47** [comment]
From looking at the videos, I think it is more likely an issue in BTLP itself, and does not have anything to do with the social interactions page. Can you check whether the latest dev-build improves anything? I have fixed a bug in the code that could be related.

**Comment by andrewkm** [comment]
Unfortunately the latest build hasn't fixed anything.
Tab list avatars are still acting up quite wildly.

**Comment by andrewkm** [comment]
This has now been fixed, confirmed.
Thank you @CodeCrafter47!
