### ISSUE TITLE
Error when joining because of Geyser compatibility 

### ISSUE THREAD

**Issue by andrew121410** [CodeCrafter47/BungeeTabListPlus#701]
Latest Waterfall and Geyser and running latest dev build of BungeeTabListPlus

https://mclo.gs/rlO17TV

**Comment by Leomelonseeds** [comment]
Until the dev fixes this, you can use this patched version I made that works with latest Geyser and Bungeecord: 
[BungeeTabListPlus-GeyserFix.zip](https://github.com/CodeCrafter47/BungeeTabListPlus/files/10224061/BungeeTabListPlus-GeyserFix.zip)

**Comment by Andre601** [comment]
Quote from CodeCrafter on Discord:

> The latest dev-build (https://ci.codecrafter47.de/job/BungeeTabListPlus/) has now gained support for 1.19.3. If you are feeling experimental you can help test it.
> 
> What to expect: It works on the latest BungeeCord with 1.19.3 spigot and 1.19.3 clients.
> 
> What is not tested:
>  * Using the latest BungeeCord and older spigot or client versions. I expect this works fine.
>  * Using an older BungeeCord without 1.19.3 support. I expect that this will not work. If that is the case, then future versions of the plugin might print a warning and refuse to start.
>  * Not using ip-forwarding (this is probably fine)
>  * Using ViaVersion on BungeeCord with a 1.19.3 spigot and 1.7.10 client. I have no idea if this will work.
> 
> What won't work:
>  * Using Geyser. I plan to look into that next weekend.
