### ISSUE TITLE
morePlayersLines

### ISSUE THREAD

**Issue by alexbegt** [CodeCrafter47/BungeeTabListPlus#71]
Hello, How do i get the morePlayersLines to work, It keeps putting the user off the side list, even tho I only wanted it to be in the 0th column, and not to go over the onto the second column

**Comment by CodeCrafter47** [comment]
I'm not sure what you want to do. Can you maybe post your config and/or a screen shot of the issue?

**Comment by alexbegt** [comment]
I have the tab list in vertical mode, and I want to list staff members in the first column, but I do not want them to go over onto the second column because I would be using the top for how many players are on each server.

**Comment by CodeCrafter47** [comment]
You can use [MAXPLAYERS=?] for that: https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Advanced-Configuration#filling-in-players

**Comment by alexbegt** [comment]
@CodeCrafter47 Will it show "and 7 others" or?

**Comment by CodeCrafter47** [comment]
You put the [MAXPLAYERS=?] thing before {fillplayers:...}. It will not prevent that the "and X others " is shown. If you use [MAXPLAYERS=19] It will either show up to 19 players or it will show 18 players and the "and X others"

**Comment by alexbegt** [comment]
Oh cool, thanks!
