### ISSUE TITLE
Getting kicked from server with PlayerListItem error on Paper 1.19.3

### ISSUE THREAD

**Issue by DeathChain01** [CodeCrafter47/BungeeTabListPlus#714]
Hello!

When BTLP 3.5.2 is present on my BungeeCord server (Build 1675) that connects to four Paper 1.19.3 Build 380 servers, players get kicked after a few seconds and the console throws the output here:
https://hastebin.com/buhaqefixa.css
Players also get the same error upon getting kicked.

I've tried a different BungeeCord version (1674), tried different Paper versions (380, 379, 378, 320), and the issue persists. I've started the Paper servers both with and without the BukkitBridge plugin, and it persists. It didn't manifest when we were running BTLP 3.5.1, BungeeCord #1655, and Paper 1.19.00 #77.

**We don't run ViaVersion**, as some other reports about the PlayerListItem error mentioned. I can provide a plugin list or otherwise test whatever you want.

JAVA VERSION (in case it's useful):
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

**Comment by Andre601** [comment]
Trythe latest dev build please. It fixes 1.19.3 issues

**Comment by DeathChain01** [comment]
Using #1130 and the server's happy now, thanks!
