### ISSUE TITLE
No config generation

### ISSUE THREAD

**Issue by Kraxous** [CodeCrafter47/BungeeTabListPlus#715]
Currently running `Purpur 1.19.3` and `BungeeTabListPlus_BukkitBridge` | `BungeeTabListPlus-3.6.0` dev builds.

The plugin initialises but doesn't generate any form of configuration files and thus, doesn't work. Extracts from the config below.

`[12:03:25] [Server thread/ERROR]: Ambiguous plugin name BungeeTabListPlus for files plugins/BungeeTabListPlus_BukkitBridge-3.6.0-SNAPSHOT.jar and plugins/BungeeTabListPlus-3.6.0-SNAPSHOT.jar in plugins`
`[12:03:25] [Server thread/WARN]: [org.bukkit.craftbukkit.v1_19_R2.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!`

`[12:03:34] [Server thread/INFO]: [BungeeTabListPlus] Loading BungeeTabListPlus v3.6.0-SNAPSHOT`

`[12:04:10] [Server thread/INFO]: [BungeeTabListPlus] Enabling BungeeTabListPlus v3.6.0-SNAPSHOT`

I've checked for conflicts but cannot find anything that stands out. The only two plugins I am also running are CMI and UltimatePermissions but the feature for handling the tablist is disabled.

TIA.

**Comment by Andre601** [comment]
BungeeTabListPlus is a **BungeeCord** plugin. It's in the name.

You can't use a BungeeCord plugin in a Spigot (And by extension Purpur) server. They are incompatible APIs.

If you're not running a server network, meaning you don't have a BungeeCord proxy, should you use [AdvancedTabOverlay](https://github.com/CodeCrafter47/AdvancedTabOverlay) as that one is specifically made for single servers.
Tho, as of right now is the plugin not supporting 1.19.3 yet and there is no ETA for any updates to fix that.

**Comment by Kraxous** [comment]
Do apologise, just read the full requirements. Thanks.
