### ISSUE TITLE
None of the icons seems to be displayed

### ISSUE THREAD

**Issue by CodeZhangBorui** [CodeCrafter47/BungeeTabListPlus#716]
It seems that none of the icons are displayed

![image](https://user-images.githubusercontent.com/61909157/213959417-b809ccf1-e63e-4e04-84b9-30f2969633e5.png)

Use [BungeeTabListPlus Jenkins Build #1130](https://ci.codecrafter47.de/job/BungeeTabListPlus/1130/) at WaterfallMC 1.19.3 server. Use Minecraft 1.19.2 joined.

See TabList file at [https://pastebin.com/Nfbpv7sh](https://pastebin.com/Nfbpv7sh)

**Comment by CodeCrafter47** [comment]
Icons are not displayed in offline mode, because they require an internet connections (icons are stored on Mojang servers). If your server is connected to the internet, disable offline mode to see the icons.

**Comment by CodeZhangBorui** [comment]
Solved by enable online-mode in `server.properties`, thank you.
