### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheSparkPlays** [CodeCrafter47/BungeeTabListPlus#72]
When i load the plugin is says this:

10:06:17 [SEVERE] Exception in thread "main"
10:06:17 [SEVERE] while scanning for the next token
found character      '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 24, column 1:

    ^

10:06:17 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:231)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
10:06:17 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
10:06:17 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:61)
10:06:17 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:64)
10:06:17 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:248)
10:06:17 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
10:06:17 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by CodeCrafter47** [comment]
Don't use tabs in the config file.
