### ISSUE TITLE
BungeeTabListPlus and RedisBungee : prefix are not show properly.

### ISSUE THREAD

**Issue by zebigboss72** [CodeCrafter47/BungeeTabListPlus#73]
Hi
I' using Bungeetablistplus since few months, and 1 week ago, i start using RedisBungee with 2 bungeecord servers. All work well, but the tablist show only player prefix when players are in the same bungeecord proxy. I took 2 screenshots to explain better what i say.
![tablistbug1](https://cloud.githubusercontent.com/assets/12184142/12672824/473f0e9e-c679-11e5-84e1-5d9388ed612c.png)
![tablistbug2](https://cloud.githubusercontent.com/assets/12184142/12672823/473a97f6-c679-11e5-83d5-0bf24a711d9e.png)
Jer_cof and I where connected to a different bungeecord instance when we took these screens. i can see my prefix, but not jer_cof's one, and jer_cof can see his prefix but not mine.

About my server configuration, i'm using 2 bungeecord servers (1.8-SNAPSHOT:79dbdea:1105), with redisbungee 0.3.6, bungeetablistplus 2.3.2 and some other plugins who don't interact with your's (bungee side)
I got many spigots servers, with bungeetablistplus_bukkitbridge 2.3.2, essentials-2.x, permissionEx 1.23.2... if you need more details about the plugins i use, ask me.

The bungeetablistplus config is this one : http://pastebin.com/sVRJ2hEj

I saw someone with the same problem on spigot forums. Is there any way to display player prefix connected to another bungeecord server, by using redisbungee? you can see in the config file that i use prefixs from BUKKIT/vault .

cordially,
zebigboss_72

**Comment by CodeCrafter47** [comment]
Same as #65

**Comment by zebigboss72** [comment]
sorry, i didn't saw this bug was report here before.

**Comment by CodeCrafter47** [comment]
That doesn't matter. I think you described the issue more accurate.

**Comment by CodeCrafter47** [comment]
fix as of 6c56c624dde8376b2ff8cc6a2682d576b4fe8533
