### ISSUE TITLE
Latest bungeecord/waterfall breaks BungeeTabListPlus

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#735]
Tested against Waterfall 549. https://github.com/PaperMC/Waterfall/commit/dc0595653d238694435dfe6d83d1805fc56c4e9a
Broken due to md_5's latest snapshot update for the next version of MC.

https://pastebin.com/raw/pLZgg6sL
https://pastebin.com/raw/R3DWFAn8

**Comment by Sylensky** [comment]
can confirm seeing the same issue on my side.

**Comment by SirvydasS** [comment]
Having same problem

**Comment by JuergenUniVie** [comment]
same issue

**Comment by CodeCrafter47** [comment]
I'll look into it on the weekend.

**Comment by VicenteRD** [comment]
`PlayerListHeaderFooter`'s builder now takes two `BaseComponent`s instead of two strings (as per [this commit](https://github.com/SpigotMC/BungeeCord/commit/0f5f09b6c5f073130515c8cd435541c5c68bcba8#diff-725633d8174c197cf42d46c59d5eed2ac1ef6033fa09363d29c65f516043bca7R21)) - Looking at what's currently being sent and what the API offers, I think instantiating two empty `TextComponent`s should do the trick.
Would you like me to send a PR? I have no way of testing as I am just reading the code and have no idea (or time, really) to test myself, but I wanted to help somehow anyways.
Thanks for your work!

**Comment by andreasdc** [comment]
Still broken after the latest update

**Comment by andrewkm** [comment]
Fixed on latest Bungee and latest BTLP, thanks!

**Comment by andreasdc** [comment]
> Fixed on latest Bungee and latest BTLP, thanks!

You don't have the latest bungee and without the latest bungee there will be connections problems.

**Comment by andrewkm** [comment]
Yes, we DO have the latest bungee and have no issues.

**Comment by andrewkm** [comment]
> > Fixed on latest Bungee and latest BTLP, thanks!
> 
> You don't have the latest bungee and without the latest bungee there will be connections problems.

Ok I see what you mean now, you didn't really specify it properly before, stating "without the latest bungee" there will be connection problems. When reporting issues, it's best to be detailed, and provide the errors as well.

Anyways, connections on the latest bungee and bungeetablistplus work fine, however console is once again throwing issues.
This is as of: https://github.com/PaperMC/Waterfall/commit/9ac9f375b16305ab5bf0c2e52d1be12dbf9aec80
Issue on player login: https://pastebin.com/raw/AzLSCgv4

@CodeCrafter47

**Comment by andreasdc** [comment]
Exactly, basically without the latest bungee in some situations clients under 1.13 won't be able to connect to the server. With the latest bungee BTLP doesn't work yet, I can't wait for the patch 🚀

**Comment by andrewkm** [comment]
That part I cannot reproduce. We are NOT on the latest bungee as of this post, and 1.12.2 clients connect just fine.

**Comment by andreasdc** [comment]
You need scoreboard objective that has space in it, but it is already fixed in the latest bungeecord. We just need to wait for BTLP patch for the latest bungee.

**Comment by andrewkm** [comment]
Tested and fixed, thank you! :)

**Comment by andreasdc** [comment]
Actually it will crash users on 1.8 and probably all below 1.13, still needs a fix :(

**Comment by andrewkm** [comment]
> Actually it will crash users on 1.8 and probably all below 1.13, still needs a fix :(

No one cares, this has nothing to do with the original issue in #735
Make your own detailed issue, instead of spamming your problems everywhere.

**Comment by andreasdc** [comment]
Have your server bugged or delete it, i'm just telling you that it won't work, genius XD

**Comment by andrewkm** [comment]
> Have your server bugged or delete it, i'm just telling you that it won't work, genius XD

No one cares.

**Comment by Andre601** [comment]
> Have your server bugged or delete it, i'm just telling you that it won't work, genius XD

Do everyone a favour and don't annoy people on other issues. This, as andrekm mentioned, is not related to the issue in question here, so there is absolutely no need to now try and insert your own issue here.

You already have your own issue, stating the problems, so use that.

**Comment by andreasdc** [comment]
The latest patch breaks it even more, I'm just informing.

**Comment by andrewkm** [comment]
> The latest patch breaks it even more, I'm just informing.

The latest patch has not broken the reported issue here in #735 "even more".
It in-face has corrected and solved it.

If you have an issue, once again, make a proper report.
State your server/proxy version/build numbers.
State your plugin version/build numbers.

Provide full logs. Etc.

Zero effort will **always** equal zero help.

**Comment by andreasdc** [comment]
> > The latest patch breaks it even more, I'm just informing.
> 
> The latest patch has not broken the reported issue here in #735 "_even more_". It in-fact has corrected and solved it.
> 
> If you have an issue, once again, make a proper report. State your server/proxy version/build numbers. State your plugin version/build numbers.
> 
> Provide full logs. Etc.
> 
> Zero effort will **always** equal zero help.

That's fine, you can live in your imaginary world. I guess someone made zero effort towards you and you don't understand simple facts. I'm not responding to you anymore.
