### ISSUE TITLE
BTLP prevents 1.8.8 clients joining 1.8.8 servers.

### ISSUE THREAD

**Issue by andrewkm** [CodeCrafter47/BungeeTabListPlus#739]
Testing Environment:
OS: Windows 11 V: 22H2
Proxy: Waterfall compiled against https://github.com/PaperMC/Waterfall/commit/9ac9f375b16305ab5bf0c2e52d1be12dbf9aec80
Server: Paper 1.8.8 Build 445 grabbed via https://api.papermc.io/v2/projects/paper/versions/1.8.8/builds/445/downloads/paper-1.8.8-445.jar
Client: Default 1.8.8

Testing Scenario: No proxy plugins, no server plugins.
Proxy log with 3 logins: https://pastebin.com/raw/K9f5eikH 
Server log with 3 logins: https://pastebin.com/raw/rmQUGNbH

Testing Scenario: Proxy includes BTLP compiled against https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9c56d1b048ebff69837bf402025838690b8d5674 w/ (default generated config) & no server plugins.
Proxy log with 1 login followed by crash: https://pastebin.com/raw/syrVb62s
Server log with 1 login followed by crash: https://pastebin.com/raw/290E7R3F
Client crash screenshot: https://i.imgur.com/MfVw01Z.png
Client crash report: https://pastebin.com/raw/KHTa0ViG

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at avo.a(SourceFile:276)
	at bfk.a(SourceFile:1021)
	at ave.av(SourceFile:915)
	at ave.a(SourceFile:325)
	at net.minecraft.client.main.Main.main(SourceFile:124)
```

For reference: Installing BTLP bukkit bridge onto the server produces same results.

Rolling BTLP back to https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9c56d1b048ebff69837bf402025838690b8d5674 and keeping the exact same stated environment allows login and functionality.

The problem could very well rest in **Bungee** just as well as it could in **BTLP**, thus time will tell.

I've asked someone on our development team who works closely with waterfall to take a look.

PS: _I did these tests and made this issue simply because I have time this morning and appreciate the BTLP plugin very much, and although I do not use 1.8.8 in any regard, after reading #738 resulted in lowering my IQ I felt I had to effort a bit to restore a point or two._

**Comment by electronicboy** [comment]
Because andrew hates me and I'm a sucket for pain, It's worth noting that the OG report for this has some more useful info in the crash itself;

` Cannot invoke "a.b()" because the return value of "aul.l()" is null`

`aul.l().b()` seems to map to `scoreplayerteam.getChatFormat().getColorIndex()`, the only way that that could be the case is if the color index is too high, looks like mojangs code handles it being too low, but

Forge:
```java
    public static EnumChatFormatting func_175744_a(int p_175744_0_)
    {
        if (p_175744_0_ < 0)
        {
            return RESET;
        }
        else
        {
            for (EnumChatFormatting enumchatformatting : values())
            {
                if (enumchatformatting.getColorIndex() == p_175744_0_)
                {
                    return enumchatformatting;
                }
            }

            return null;
        }
    }
    ```

**Comment by electronicboy** [comment]
https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9b6f6133333b78a2e6e5b005d06d4f1b4189e00b#diff-584f6ebab5f5ad6a3b8d93bec7724117bebd470662a887af56104cd4c6aad3ebL998

This is what broke it, 1.13+ uses the enum ordinal, 21 = reset; prior to that, it uses its own index ID, of which -1 = reset

**Comment by MacTh3Mac** [comment]
Nothing technical to add except confirm Andrews report tested on bungee & waterfall, errors produced client side on 1.12.2 vanilla virtually identical to @andrewkm 's pastes.

BTLP: https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9c56d1b048ebff69837bf402025838690b8d5674
BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:bd8d114:1769
Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:cc856ed:552
Backend Servers: 1.18.2, 1.12.2, 1.20.1, 1.20.2 all identical result.

**Comment by andreasdc** [comment]
Weird that noone is attacking you for this report, but yea, it will be nice to get the fix.

**Comment by andrewkm** [comment]
> Weird that noone is attacking you for this report, but yea, it will be nice to get the fix.

You should be thanking me for even having this looked into properly lmao... I'm actually amazed at your comment, but it's alright. You won't get far in any industry the way you behave.

**Comment by andreasdc** [comment]
> > Weird that noone is attacking you for this report, but yea, it will be nice to get the fix.
> 
> You should be thanking and apologizing to the group here for us even having someone like electronicboy look into this swiftly after your behaviour earlier lol... I'm actually amazed at your comment, but it's alright. You won't get far in any industry the way you behave. It's no wonder I've been informed that several repos have already banned you completely. @CodeCrafter47 should do the same and just be rid of you.
> 
> Rest assured you won't get such help from my team and I again. 😅

I gave you everything what you wanted yesterday, that's not my fault that you didn't understand something and you wanted to behave that way.

**Comment by andrewkm** [comment]
Nvm, you're not worth my time anymore, some people just can't be helped.

**Comment by Andre601** [comment]
Let's just ignore that guy.
He clearly seeks the attention(probs even being narcistic) or is just an idiot.

We should stop feeding into his behaviour, as entertaining as it may be.

He clearly can't or won't realize his bad behaviours.

**Comment by andreasdc** [comment]
You are talking about yourself actually, don't attack if you don't know how to defend, cheers guys.

**Comment by Andre601** [comment]
> He clearly can't or won't realize his bad behaviours.

Case in point:
> You are talking about yourself actually, don't attack if you don't know how to defend, cheers guys.

(Tho, that's the last thing I will say in relation to that loser.)

**Comment by andreasdc** [comment]
> [9b6f613#diff-584f6ebab5f5ad6a3b8d93bec7724117bebd470662a887af56104cd4c6aad3ebL998](https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9b6f6133333b78a2e6e5b005d06d4f1b4189e00b#diff-584f6ebab5f5ad6a3b8d93bec7724117bebd470662a887af56104cd4c6aad3ebL998)
> 
> This is what broke it, 1.13+ uses the enum ordinal, 21 = reset; prior to that, it uses its own index ID, of which -1 = reset

Are you sure that's it? Maybe you can create a for with the fix or that's not possible?

**Comment by andrewkm** [comment]
> > [9b6f613#diff-584f6ebab5f5ad6a3b8d93bec7724117bebd470662a887af56104cd4c6aad3ebL998](https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9b6f6133333b78a2e6e5b005d06d4f1b4189e00b#diff-584f6ebab5f5ad6a3b8d93bec7724117bebd470662a887af56104cd4c6aad3ebL998)
> 
> > 
> 
> > This is what broke it, 1.13+ uses the enum ordinal, 21 = reset; prior to that, it uses its own index ID, of which -1 = reset
> 
> 
> 
> Are you sure that's it? Maybe you can create a for with the fix or that's not possible?

Believe me buddy electronicboy won't put in a single ounce more time into this due to your attitude. If you'd like the help of my time we charge $30USD/Hour.

I don't use 1.8.8 thus this issue means nothing to me.

**Comment by MacTh3Mac** [comment]
Have Tested PR #741  compiled Java 16.0.1 Appears to compile correctly and resolve issue on Waterfall B522, Multiple clients above and below 1.13 and maintains tab lists both global and per server after multiple server changes.

Screenshots added to PR Review thread.

**Comment by MacTh3Mac** [comment]
Note @PrinceBunBun981 your fork won't compile.   But when I merge your changes into my local copy of BTLP https://github.com/CodeCrafter47/BungeeTabListPlus/commit/9c56d1b048ebff69837bf402025838690b8d5674 from this repository it compiles correctly.  so PR should be fine.   Cheers.
