### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by Ironic8b498** [CodeCrafter47/BungeeTabListPlus#74]
can't seem to figure out how to use prefixes for permissionex in the tablist I have changed permission source to BUKKITPERMISSIONSEX. I have left out the ranks that are numbers in case they were my problem, when I change the permissionsource back to AUTO I get a prefix for admin rest of players don't get anything since the default one has nothing in it. is this me or the the plugin with a bug?

**Comment by CodeCrafter47** [comment]
You need to install BungeeTabListPlus_BukkitBridge.jar on all your bukkit/ spigot servers and it will magically work.
