### ISSUE TITLE
BungeeTabListPlus: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by foodornt** [CodeCrafter47/BungeeTabListPlus#743]
Running BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT and BungeeTabListPlus version 3.4.4 prompts me this error:
https://pastebin.com/S60fGz6M
I have seen others facing the same error with the latest release, but not the older one
similar error is prompted on the latest version:
https://pastebin.com/gE4iWr59

**Comment by Andre601** [comment]
Try the latest dev build.
