### ISSUE TITLE
Bold text is no longer bold in 1.20.2

### ISSUE THREAD

**Issue by hraponssi** [CodeCrafter47/BungeeTabListPlus#749]
Text that is set to bold in a tablist doesn't display as bold after updating to 1.20.2. This happens on both an old upgraded install and a new install using an example tablist from the codecrafter discord.
On the new install this part of the tablist saying "to codecrafter" should be in bold, but isn't displayed as such:
![image](https://github.com/CodeCrafter47/BungeeTabListPlus/assets/8525166/3eeb1f61-8a2f-4027-95cc-27d3a87ebf43)
Relevant part of the tablist config:
![image](https://github.com/CodeCrafter47/BungeeTabListPlus/assets/8525166/39809b6b-c989-47f6-8093-21c07cf69358)
There are no errors in the console, and the server is running the latest development build.

**Comment by FireML** [comment]
this is also happening to me on 1.20.4 latest dev build

**Comment by DJ-Daniel** [comment]
I also have this issue with all formatting except colors.

**Comment by hraponssi** [comment]
Looks like this was fixed in the latest release
