### ISSUE TITLE
Can't connect waterfall server

### ISSUE THREAD

**Issue by sherry5299** [CodeCrafter47/BungeeTabListPlus#757]
The client and server versions are 1.20.4 , but it kick the player when they try to connect the server .
[12:06:43 WARN] [BungeeTabListPlus.sherry912]: [sherry912] Cannot correctly update tablist for player sherry912
The client and server versions do not match. Client < 1.19.3, server >= 1.19.3.
Use ViaVersion on the spigot server for the best experience.

**Comment by Andre601** [comment]
In case anyone else finds this issue and wonders about the fix:

The issue was the usage of ViaVersion on the Proxy. ViaVersion should not be used there and instead only be used on the backend servers. The above issue was probably caused by exactly that (ViaVersion messing with the client version).
