### ISSUE TITLE
yaml error in schedule using placeholders

### ISSUE THREAD

**Issue by LadyHaley** [CodeCrafter47/BungeeTabListPlus#763]
Its not accepting placeholders, I tried surrounding the command with " " and ' ' which usually helps in the case of a syntax error, but it did nothing here. I saw mention in an issue https://github.com/Zrips/CMI/discussions/3702 from 2020 about not knowing how to proceed with the syntax error.

would alternate placeholder symbol be preferable here?

**Comment by Andre601** [comment]
First of all: What is the exact error?

Second: What is your configuration file that has the issues?

**Comment by LadyHaley** [comment]
I send this on the wrong project I think, this is what I get for staying up past 11... Sorry about that jhsabshudjfbds
