### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by Ironic8b498** [CodeCrafter47/BungeeTabListPlus#77]
I can't get the prefix's to work, I'm running PermissionsEx 1.23.3, Spigot 1.8.8, BungeeTabList 2.3.3. I left out the ranks that are numbers in case that was mu=y issue still don't work

Config.yml
http://pastebin.com/5ZwbPG8G

**Comment by CodeCrafter47** [comment]
The plugin will use the prefixes from pex, not the ones in the config.

**Comment by CodeCrafter47** [comment]
Ignore my last message. The plugin will use the prefixes in the config. In your case it probably fails to detect the primary group of the player correctly.

Try using the latest dev-build of BungeeTabListPlus-BukkitBridge from http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/
It contains some changes in how the primary group of a player is detected when using PEX.

If that doesn't fix your issue please give an example of how your PEX groups are configured (ranks, ladders, which groups does a player have).

**Comment by Ironic8b498** [comment]
I updated to the dev-build and still don't show prefix.yml I added the config.yml, default and my pex permission file. Not sure if  files are setup right and my permissions work just not sure if It is set up so other plugins will see things correct.


Config.yml
http://pastebin.com/XMmaZ5X3
Default.yml
http://pastebin.com/tB6yYRp7
permission.yml
http://pastebin.com/r3Vn7SuD

**Comment by CodeCrafter47** [comment]
If you run /plugins on your bukkit server, does it list BungeeTabListPlus?

**Comment by Ironic8b498** [comment]
no, should it?

**Comment by CodeCrafter47** [comment]
Yes. The BungeeTabListPlus_BukkitBridge-version.jar file which you need to install on all bukkit/spigot servers if you want the plugin to use the permission groups from PEX will list itself as BungeeTabListPlus there.

**Comment by Ironic8b498** [comment]
does the bridge version need to be on bungee server?

**Comment by CodeCrafter47** [comment]
No, you put the BungeeTabListPlus-_version_.jar on BungeeCord and the BungeeTabListPlus_BukkitBridge-_version_.jar on Bukkit/ Spigot.

It's also explained in the [wiki](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Installation).

**Comment by Ironic8b498** [comment]
I don't recall reading the wiki, I would skip things over next new plugin I run. Thanks for the help
