### ISSUE TITLE
Users not displaying in tab

### ISSUE THREAD

**Issue by Developaws** [CodeCrafter47/BungeeTabListPlus#78]
Getting reports that some users aren't being put into the tab list. (have confirmed this myself as well).

No further information as there's no error reports etc. that are being thrown.

**Comment by CodeCrafter47** [comment]
Which version of the plugin and of BungeeCord are you using? How have you configured the plugin?

**Comment by cblair91** [comment]
Plugin: 2.3.3, bungee: 1116.

Config: http://pastebin.com/vZniB8A4

**Comment by CodeCrafter47** [comment]
Your setup is fine. It will show all players which are either on the Survival or the Creative server.

Possible reasons why some players are missing could be
 1. They are hidden by some vanish plugin which causes the m not to appear in the tab list
 2. They are connected directly to one of your servers, not through BungeeCord

**Comment by cblair91** [comment]
1. Our vanish plugin is a custom system (so wouldn't be detected by you), and also, they're members, so not accessible to this.
2. We only allow connection via BC, no direct connection.

**Comment by CodeCrafter47** [comment]
Then I don't know why some players would be missing from the tab list. If it happens again you could compare the player counts shown in the tab list with the ones shown by /glist.

**Comment by cblair91** [comment]
Will compare when the bug is next seen and update accordingly.
