### ISSUE TITLE
Client 1.8 bug

### ISSUE THREAD

**Issue by lapry34** [CodeCrafter47/BungeeTabListPlus#82]
Hello! when i join on the server i get this exception: http://pastebin.com/gGGPG006

**Comment by CodeCrafter47** [comment]
Which version of the plugin, bungeecord and which forge version are you using?

**Comment by lapry34** [comment]
Bungee:1109 
Forge: 11.14.4.1563

**Comment by CodeCrafter47** [comment]
I tested these versions and had no issues.

**Comment by CodeCrafter47** [comment]
does de15872fe27f666a9d64f02603db6aaada74936f fix this?
