### ISSUE TITLE
Perfix's

### ISSUE THREAD

**Issue by Ironic8b498** [CodeCrafter47/BungeeTabListPlus#84]
I was running non vertical tab-list I switched to vertical cause I have 6 servers now on my network so I can show all servers, I got it work work, just can't seem to get the prefix's to show up?

**Comment by CodeCrafter47** [comment]
I recommend you click the wiki tab above and see if you can find something about prefixes there.

If you can't get it to work, describe what you tried so far and what the results were.

**Comment by Ironic8b498** [comment]
my issue was I was pressing tab key while on a server under construction and I had my installed the BungeeTabListPlus_BukkitBridge yet, It had worked from the start didn't know
