### ISSUE TITLE
Bug when more than 100 players & reload cmd (and hide too)

### ISSUE THREAD

**Issue by RealRunSpace** [CodeCrafter47/BungeeTabListPlus#85]
I think that this is the Best plugin to have a global view from your servers, but now my Network have more than 100 users,and when it reach 100~105 player it just stop working AMD go into a bukkit normal tablist, and the reload command send an error and don't reload the configs. Please still updating this, thanks!
(Copied from spigot comment :P)

**Comment by CodeCrafter47** [comment]
Can you post the errors that appear in the server log here?

**Comment by RealRunSpace** [comment]
I don't see any errors,it just get disabled or something, even if I make a 80 slots TAB with limited by 5 players pero server, i'll try to record it

**Comment by mariolars** [comment]
I have the same problem.. There is no errors , server is not overloaded but more than 200 players joining to the game for tablist takes up to 10 minutes to send it to the player.

**Comment by CodeCrafter47** [comment]
@RealRunSpace you mentioned an error when using the reload command.

**Comment by RealRunSpace** [comment]
Ok wait a second

**Comment by RealRunSpace** [comment]
Ok we were on an old versión, now looks correct, if something goes wrong I will advise you, thanks
