### ISSUE TITLE
tablistUpdateInterval doesnt work property

### ISSUE THREAD

**Issue by Hester** [CodeCrafter47/BungeeTabListPlus#86]
In config file we can found option: "tablistUpdateInterval", if you set it to -1 or any other value will it be still updating every second

**Comment by CodeCrafter47** [comment]
That depends on your configuration. If you use variables that require being updated any second, then the plugin will set the update interval to every second.

**Comment by Hester** [comment]
When you set this option to -1 TabList constantly refreshes every 1s. It is the same in the case of setting this eg for the 30s, TabList further refresh every second

**Comment by CodeCrafter47** [comment]
As I already said. The plugin automatically increases the update interval if required by your configuration.

The use of the following placeholders will set the update interval to 1 second: {time}, {seconds}, {color}.

If you use a header/ footer animation the update interval will be set at least to the animation update interval.

**Comment by CodeCrafter47** [comment]
The option was removed with 0ca1d81ccbe14fc626897bce4f0e2baa3375728d
