### ISSUE TITLE
Ran out of memory error

### ISSUE THREAD

**Issue by smessie** [CodeCrafter47/BungeeTabListPlus#88]
Once a day my bungeecord server crashes with an ERROR of the memory.
Most of the times there isnt an ERROR but I had this 2 times I had an ERROR and it comes of your plugin :/
I gave my bungeecord server a maximum ram of 3GB and I have around the 15 players max. I hope you could fix it beacause it is not funny anymore.
Here you have screenshots of my ERROR: http://m.imgur.com/j61buw1,DIe5xai

**Comment by CodeCrafter47** [comment]
Please create a heap dump when the issue happens. Without a heap dump it is impossible to tell why your server runs out of memory. See https://stackoverflow.com/questions/10944082/can-sun-jdk-generate-core-heap-dump-files-when-jvm-crashes

Also for 15 players you don't need 3GB ram.

**Comment by smessie** [comment]
Yeah, but I gave my server more ram beacause it crashes with ranoutofmemory error. It was to show that it takes to much ram.
Where need I set that for that head dump?

**Comment by CodeCrafter47** [comment]
I gave you a link. You need to set the -XX:+HeapDumpOnOutOfMemoryError java option.

**Comment by smessie** [comment]
Yes but I don't know where :/
And Maybe good ro know is that When the server crashes my processor becomes 100%

**Comment by CodeCrafter47** [comment]
instead of running `java -jar BungeeCord.jar` you run `java -XX:+HeapDumpOnOutOfMemoryError -jar BungeeCord.jar`

**Comment by smessie** [comment]
Here it is. I hope you can resolve it now.
http://imgur.com/P1UGR9j

**Comment by CodeCrafter47** [comment]
That's a screen shot, not a heap dump. But as you can see in the screen shot it has written a heap dump to a file.

**Comment by smessie** [comment]
i've uploaded it: http://mab.to/iAaClTk57
I hope it is these beacause it took my 1-2 hours to load it to that site xD 
it is almost 3Gb :o
so i hope you could fix it now :)

**Comment by CodeCrafter47** [comment]
The issue is caused by your custom plugin.

The main cause of the issue is that you plugin does not close mysql statements and result sets after use. At the time the heap dump was created ~800000 com.mysql.jdbc.JDBC4PreparedStatement objects each occupied about 2GB ram.

Another small issue is your custom plugin keeping references to disconnected players in the ChatEvent class. At the time of the heap dump there are 63 ProxiedPlayer objects kept in memory.

**Comment by smessie** [comment]
oh sorry for the false report and thank you to help me with my own problem.
