### ISSUE TITLE
Error with 2.4.2 in 1.9 R1

### ISSUE THREAD

**Issue by PapaHarni** [CodeCrafter47/BungeeTabListPlus#89]
Get Error on Start Up :

`[WARNUNG] [BungeeTabListPlus] You used [ROW=20] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=40] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=60] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=73] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=20] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=40] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=60] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=73] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=20] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=40] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=60] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=73] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=20] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=40] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=60] but the tablist only has 20 rows. Setting row to 19
[WARNUNG] [BungeeTabListPlus] You used [ROW=73] but the tablist only has 20 rows. Setting row to 19`

and the other by running:
`[BungeeTabListPlus] Error while updating tablist
Minimum size the given layout would need is 86 but tab_size is only 80
	at codecrafter47.bungeetablistplus.layout.TablistLayoutManager.calculateLayout0(TablistLayoutManager.java:57)
	at codecrafter47.bungeetablistplus.layout.TablistLayoutManager.calculateLayout(TablistLayoutManager.java:34)
	at codecrafter47.bungeetablistplus.tablistproviders.ConfigTabListProvider.fillTabList(ConfigTabListProvider.java:101)
	at codecrafter47.bungeetablistplus.ResendThread.update(ResendThread.java:164)
	at codecrafter47.bungeetablistplus.ResendThread.run(ResendThread.java:109)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

This error is in the Tablist ingame too.

**Comment by CodeCrafter47** [comment]
That is a configuration error.

The maximum tab_size is 80. This results in a tab list with 4 columns and 20 rows. If you tell the plugin to put something on the 60th row that is obviously not going to work as there are only 20 rows. That is what all the errors on startup are telling you.

The second error happens because the plugin calculated that you config would require the tab list to have at least 86 slots while it has only 80 slots. Most likely this error will disappear as you fix the issues in your config files, the plugin notices at startup.

**Comment by PapaHarni** [comment]
But it's the same config before i have update the plugin. And it have work. So u has change row as field numbers to colums and row?

**Comment by PapaHarni** [comment]
Ok thanks, works now with colum and row in vertical mode ;-) In an old version it works with row 0-79 in vertical Mode ;-)
