### ISSUE TITLE
Spewing errors 1.8

### ISSUE THREAD

**Issue by Wosp95** [CodeCrafter47/BungeeTabListPlus#9]
Hiya, I'm running bungee spigot 1.8 servers and am really impressed with the bungee plugin. However I tried to run the bukkit bridge on each individual server and it caused a mass of errors. From what I could see and my plugin knowledge they were .getonlineplayers() errors, caused by the plugin getting back a Collection rather than an Array. There are very few differences as I'm sure you're aware and I would really appreciate an 1.8 version of the plugin.
Thanks

**Comment by CodeCrafter47** [comment]
The plugin is running fine one spigot 1.8.

If you have any issues please post those errors.

Yes the plugin expects getOnlinePlayers() to return an array. In previous version of bukkit the version returning a collection has not been available, but the plugin also needs to support these. The version returning an array is also available on the 1.8 builds of the spigot server. (Actually a there's a maven plugin called overmapped which makes it possible to have two methods with the same name and parameter list but different return types).

**Comment by Wosp95** [comment]
The error that I am getting is as follows and repeatedly puts this to the console every second.
26.01 20:48:54 [Server] INFO ... 3 more
26.01 20:48:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
26.01 20:48:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71)
26.01 20:48:54 [Server] INFO at codecrafter47.bungeetablistplus.bukkitbridge.GeneralInformationUpdateTask.run(GeneralInformationUpdateTask.java:49)
26.01 20:48:54 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
26.01 20:48:54 [Server] INFO at java.lang.Thread.run(Thread.java:745)
26.01 20:48:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
26.01 20:48:54 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
26.01 20:48:54 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
26.01 20:48:54 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BungeeTabListPlus_BukkitBridge v7 generated an exception while executing task 10
26.01 20:48:54 [Server] WARN Exception in thread "Craft Scheduler Thread - 77"

**Comment by CodeCrafter47** [comment]
I just compiled 1.8 spigot from the latest git and I didn't experience these errors.

How did you obtain your build of spigot?
