### ISSUE TITLE
Console spamming Alias map does not exist

### ISSUE THREAD

**Issue by Leiath** [CodeCrafter47/BungeeTabListPlus#94]
Updated to 2.4.3/java8 today and started getting this error in console.Updated to 2.4.4 and still getting the error.

05.04 09:43:39 [Server] WARNING Configuration Error: Server "server1" used in the alias map does not exist.
05.04 09:43:39 [Server] WARNING Configuration Error: Server "server2" used in the alias map does not exist.
05.04 09:43:39 [Server] WARNING Configuration Error: Server "server3" used in the alias map does not exist.

**Comment by CodeCrafter47** [comment]
The warning is referring to an issue in the configuration. Look for the serverAlias option in [config.yml](https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/config.yml).
