### ISSUE TITLE
BungeePerms groups used in wrong order for prefixes

### ISSUE THREAD

**Issue by zedwick** [CodeCrafter47/BungeeTabListPlus#95]
Using BungeePerms, the prefix for a player is taken from the group with the highest weight, rather than the lowest.

'Weight: Determines which group is the primary group of a player. The group with the lowest value of all groups the player is in is the primary group. (default: 1000 (1500 on group creation))'
https://github.com/weaondara/BungeePerms/wiki/Groups

BungeePerms: 3.0 dev b52
BungeeTabListPlus: 2.4.4

**Comment by CodeCrafter47** [comment]
This is a BungeePerms issue.

BungeeTabListPlus doesn't care about groups, it just asks BungeePerms which prefix to display for a user.

**Comment by zedwick** [comment]
Ah, alright. Thank you.

I have reported this here: https://github.com/weaondara/BungeePerms/issues/253

**Comment by CodeCrafter47** [comment]
Closing as this is a BungeePerms issue.

**Comment by zedwick** [comment]
Just wanted to add that using the new variables for BungeePerms primary group prefixes fixes this issue for me, thanks.
