### ISSUE TITLE
request/help on API

### ISSUE THREAD

**Issue by James137137** [CodeCrafter47/BungeeTabListPlus#96]
Would it be possible to add some sort of API to allow custom plugins to set the prefix/suffix/group of the player?

**Comment by James137137** [comment]
ok I see there is something at https://github.com/CodeCrafter47/BungeeTabListPlus/wiki/Developers

could you give a list of  registers?

**Comment by CodeCrafter47** [comment]
Look at the javadoc:
http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/codecrafter47.bungeetablistplus%24bungeetablistplus-api-bukkit/javadoc/
and
http://ci.codecrafter47.dyndns.eu/job/BungeeTabListPlus/codecrafter47.bungeetablistplus%24bungeetablistplus-api-bungee/javadoc/
