### ISSUE TITLE
Faction List Online Members

### ISSUE THREAD

**Issue by Zendrex** [CodeCrafter47/BungeeTabListPlus#97]
As the title says, would be nice if you could list your online faction members (if in one). I'm currently using placeholder api and mvdwplaceholderapi for this however its very buggy and shows all members whether they are online or off. It also doesn't show player heads.

**Comment by Zendrex** [comment]
What I have when you arent in a faction:

![NoFaction](https://i.gyazo.com/cdfcb11bc0e3c219abfed81bc3418431.png)

When you are in a faction, however where i am bugged.
![InFactionBug](https://i.gyazo.com/ead56391481ea73153de2d42baf4cd92.png)

**Comment by Zendrex** [comment]
@CodeCrafter47 Thanks for still keeping this feature in the back of your mind for a future update!

I didnt have the time to read the full post you made in reference to #113 however would a feature like [center] work? For example, say you have a line with {ping}. Obviously for some people it would be 2 numbers while for others it will possibly 3. At this point the text would be off center for them. Get where im going with it?

**Comment by CodeCrafter47** [comment]
Issue #113 is about a huge change to the config files to make them easier to understand and more extensible. It will also allow for showing a list of faction members.

A possibility for centered text will eventually also be added, but I can't say whether it will already be there in 2.6.0.

**Comment by CodeCrafter47** [comment]
With version 2.6.0 you can do all of this.

**Comment by Zendrex** [comment]
@CodeCrafter47 Think you can give me some insight on how the playerSet filter would work for something like this to show online players within your faction?
