### ISSUE TITLE
SpongeAPI bridge support

### ISSUE THREAD

**Issue by hunter688** [CodeCrafter47/BungeeTabListPlus#98]
Will be possible create SpongeAPI bridge (plugin) too?

**Comment by CodeCrafter47** [comment]
I plan to create a SpongeAPI bridge in the future, however that will most likely not make it in the next update.

**Comment by i9hdkill** [comment]
Would be quite cool! We build our own btlp sponge brigde, but with our own methods, Would be great to have an official version of it. Sponge gets quite interesting now.
